const $=s=>document.querySelector(s);const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const templates={
url:`<div class="workspace-head"><div><span class="tag">LINKS & WEB</span><h2>URL Cleaner</h2><p class="desc">Remove common marketing/tracking parameters locally.</p></div><button class="btn alt" onclick="closeTool()">Close</button></div><div class="field"><label>URL</label><textarea id="urlInput" rows="4" placeholder="https://example.com/page?utm_source=newsletter&fbclid=..."></textarea></div><div class="actions"><button class="btn" onclick="cleanUrl()">Clean URL</button></div><div id="urlOut"></div>`,
text:`<div class="workspace-head"><div><span class="tag">TEXT</span><h2>Text Cleaner</h2><p class="desc">Normalize text without sending it anywhere.</p></div><button class="btn alt" onclick="closeTool()">Close</button></div><div class="field"><label>Text</label><textarea id="textInput" rows="10" placeholder="Paste messy text…"></textarea></div><div class="actions"><button class="btn" onclick="cleanText()">Clean whitespace</button><button class="btn alt" onclick="caseText('upper')">UPPERCASE</button><button class="btn alt" onclick="caseText('lower')">lowercase</button><button class="btn alt" onclick="caseText('title')">Title Case</button><button class="btn alt" onclick="copyVal('textInput')">Copy</button></div><div id="textStats" class="result">0 words · 0 characters</div>`,
compare:`<div class="workspace-head"><div><span class="tag">TEXT</span><h2>Compare Text</h2><p class="desc">Line-level comparison for policies, notes, clauses and other text.</p></div><button class="btn alt" onclick="closeTool()">Close</button></div><div class="grid2"><div class="field"><label>Version A</label><textarea id="a" rows="12"></textarea></div><div class="field"><label>Version B</label><textarea id="b" rows="12"></textarea></div></div><button class="btn" onclick="compareText()">Compare</button><div id="diffOut"></div>`,
decision:`<div class="workspace-head"><div><span class="tag">PRODUCTIVITY</span><h2>Decision Matrix</h2><p class="desc">Score two options using your own criteria and weights.</p></div><button class="btn alt" onclick="closeTool()">Close</button></div><div class="grid2"><div class="field"><label>Option A</label><input id="optA" value="Option A"></div><div class="field"><label>Option B</label><input id="optB" value="Option B"></div></div><div class="field"><label>Criteria (name, weight, A score 1-10, B score 1-10)</label><textarea id="criteria" rows="7">Cost,3,8,6\nEase of use,2,7,9\nQuality,5,8,7</textarea></div><button class="btn" onclick="decision()">Calculate</button><div id="decisionOut"></div>`,
remediation:`<div class="workspace-head"><div><span class="tag">COMPLIANCE & AML</span><h2>KYC Remediation Planner</h2><p class="desc">Capacity planning — not a regulatory determination.</p></div><button class="btn alt" onclick="closeTool()">Close</button></div><div class="grid2"><div class="field"><label>Total files</label><input id="files" type="number" min="0" value="3600"></div><div class="field"><label>Already completed</label><input id="done" type="number" min="0" value="0"></div><div class="field"><label>Analysts</label><input id="analysts" type="number" min="1" value="21"></div><div class="field"><label>Working days remaining</label><input id="days" type="number" min="1" value="60"></div><div class="field"><label>Files per analyst / day</label><input id="rate" type="number" min=".1" step=".1" value="2.5"></div></div><button class="btn" onclick="remediation()">Calculate plan</button><div id="remOut"></div>`,
ubo:`<div class="workspace-head"><div><span class="tag">COMPLIANCE & AML</span><h2>UBO Ownership Calculator</h2><p class="desc">Simple direct-holding calculator. Complex indirect/control analysis requires a fuller ownership model.</p></div><button class="btn alt" onclick="closeTool()">Close</button></div><div class="field"><label>Review threshold (%)</label><input id="threshold" type="number" min="0" max="100" value="25"></div><table class="owners"><thead><tr><th>Owner</th><th>Ownership %</th></tr></thead><tbody id="ownerRows"></tbody></table><div class="actions"><button class="btn alt" onclick="addOwner()">+ Add owner</button><button class="btn" onclick="calcUbo()">Calculate</button></div><div id="uboOut"></div>`,
qa:`<div class="workspace-head"><div><span class="tag">COMPLIANCE & AML</span><h2>KYC QA Checker</h2><p class="desc">Generic quality-control aid. Configure to your institution's policy.</p></div><button class="btn alt" onclick="closeTool()">Close</button></div><div id="qaList"></div><div class="field"><label>Reviewer notes</label><textarea id="qaNotes" rows="4"></textarea></div><button class="btn" onclick="qaResult()">Generate QA result</button><div id="qaOut"></div>`};
function openTool(n){const w=$("#workspace");w.innerHTML=templates[n];w.classList.add("active");w.dataset.tool=n;w.scrollIntoView({behavior:"smooth",block:"start"});if(n==="ubo"){addOwner("Owner 1",60);addOwner("Owner 2",40)}if(n==="qa")renderQa();if(n==="text")$("#textInput").addEventListener("input",textStats)}
function closeTool(){$("#workspace").classList.remove("active")}
function routeIntent(){const q=$("#intent").value.toLowerCase();let n=q.match(/kyc|remediat|capacity|analyst/)?"remediation":q.match(/ubo|owner|ownership|beneficial/)?"ubo":q.match(/qa|quality|checklist/)?"qa":q.match(/compare|diff|change/)?"compare":q.match(/decision|choose|matrix/)?"decision":q.match(/url|link|tracking|utm/)?"url":q.match(/text|whitespace|case|clean/)?"text":null;if(n){$("#intentResult").textContent="✓ I found a matching tool.";openTool(n)}else $("#intentResult").textContent="Try describing a link, text, comparison, decision, KYC remediation, UBO or QA task."}
function cleanUrl(){const raw=$("#urlInput").value.trim(),out=$("#urlOut");try{const u=new URL(raw),removed=[],exact=["fbclid","gclid","dclid","msclkid","mc_cid","mc_eid","igshid","yclid","_hsenc","_hsmi"];[...u.searchParams.keys()].forEach(k=>{if(k.toLowerCase().startsWith("utm_")||exact.includes(k.toLowerCase())){removed.push(k);u.searchParams.delete(k)}});out.innerHTML='<div class="result"><strong>Clean URL</strong>\n'+esc(u.href)+'\n\n<strong>Removed</strong>\n'+(removed.length?removed.map(x=>"• "+esc(x)).join("\n"):"Nothing — no recognized tracking parameters found.")+'</div>';navigator.clipboard?.writeText(u.href)}catch{out.innerHTML='<div class="result">Enter a complete valid URL, including https://</div>'}}
function cleanText(){const e=$("#textInput");e.value=e.value.replace(/\r\n/g,"\n").split("\n").map(x=>x.replace(/[ \t]+/g," ").trim()).join("\n").replace(/\n{3,}/g,"\n\n").trim();textStats()}
function caseText(t){const e=$("#textInput");e.value=t==="upper"?e.value.toUpperCase():t==="lower"?e.value.toLowerCase():e.value.toLowerCase().replace(/\b\p{L}/gu,c=>c.toUpperCase());textStats()}
function textStats(){const v=$("#textInput").value,w=v.trim()?v.trim().split(/\s+/).length:0;$("#textStats").textContent=w+" words · "+[...v].length+" characters"}
async function copyVal(id){await navigator.clipboard.writeText($("#"+id).value)}
function compareText(){const A=$("#a").value.split("\n"),B=$("#b").value.split("\n"),removed=A.filter(x=>!B.includes(x)),added=B.filter(x=>!A.includes(x));$("#diffOut").innerHTML='<div class="metricgrid"><div class="metric"><small>Added lines</small><strong>'+added.length+'</strong></div><div class="metric"><small>Removed lines</small><strong>'+removed.length+'</strong></div></div><div class="grid2"><div class="result"><strong>Removed</strong>\n'+(removed.map(x=>"− "+esc(x)).join("\n")||"None")+'</div><div class="result"><strong>Added</strong>\n'+(added.map(x=>"+ "+esc(x)).join("\n")||"None")+'</div></div>'}
function decision(){const rows=$("#criteria").value.split("\n").map(r=>r.split(",").map(x=>x.trim())).filter(r=>r.length>=4),a=$("#optA").value,b=$("#optB").value;let wa=0,wb=0,tw=0,detail=[];rows.forEach(r=>{let w=+r[1],sa=+r[2],sb=+r[3];if(w>=0&&sa>=1&&sa<=10&&sb>=1&&sb<=10){tw+=w;wa+=w*sa;wb+=w*sb;detail.push(r[0]+": weight "+w+", "+a+" "+sa+"/10, "+b+" "+sb+"/10")}});if(!tw)return $("#decisionOut").innerHTML='<div class="result">Enter valid criteria.</div>';$("#decisionOut").innerHTML='<div class="metricgrid"><div class="metric"><small>'+esc(a)+'</small><strong>'+(wa/tw).toFixed(2)+'</strong></div><div class="metric"><small>'+esc(b)+'</small><strong>'+(wb/tw).toFixed(2)+'</strong></div></div><div class="result">'+esc(detail.join("\n"))+'\n\nHigher weighted score reflects only the criteria, weights and scores you entered.</div>'}
function remediation(){const total=+$("#files").value,done=+$("#done").value,n=+$("#analysts").value,d=+$("#days").value,r=+$("#rate").value,remain=Math.max(0,total-done),req=remain/d,cap=n*r,short=Math.max(0,remain-cap*d),needed=Math.ceil(req/r),extra=Math.max(0,needed-n),msg=short?"At the entered productivity, projected shortfall by deadline: "+Math.ceil(short).toLocaleString()+" files.":"Entered capacity is sufficient for the stated population and deadline.";$("#remOut").innerHTML='<div class="metricgrid"><div class="metric"><small>Files remaining</small><strong>'+remain.toLocaleString()+'</strong></div><div class="metric"><small>Required / day</small><strong>'+req.toFixed(1)+'</strong></div><div class="metric"><small>Current capacity / day</small><strong>'+cap.toFixed(1)+'</strong></div><div class="metric"><small>Additional analysts</small><strong>'+extra+'</strong></div></div><div class="result">'+msg+'\n\nAssumption-based planning result. Validate productivity, working days, case complexity and operational constraints.</div>'}
function addOwner(name="",pct=""){const tr=document.createElement("tr");tr.innerHTML='<td><input class="oname" value="'+esc(name)+'" placeholder="Owner name"></td><td><input class="opct" type="number" min="0" max="100" step=".01" value="'+pct+'"></td>';$("#ownerRows").appendChild(tr)}
function calcUbo(){const th=+$("#threshold").value,rows=[...document.querySelectorAll("#ownerRows tr")].map(r=>({n:r.querySelector(".oname").value||"Unnamed",p:+r.querySelector(".opct").value||0})),sum=rows.reduce((s,x)=>s+x.p,0),flags=rows.filter(x=>x.p>=th);$("#uboOut").innerHTML='<div class="metricgrid"><div class="metric"><small>Total entered</small><strong>'+sum.toFixed(2)+'%</strong></div><div class="metric"><small>At/above '+th+'%</small><strong>'+flags.length+'</strong></div></div><div class="result">'+(flags.length?flags.map(x=>esc(x.n)+": "+x.p.toFixed(2)+"%").join("\n"):"No entered direct holding meets the selected threshold.")+'\n\nThis does not determine legal UBO status. Control rights, indirect ownership, aggregation and jurisdiction-specific rules may change the analysis.</div>'}
const qaItems=["Identity / legal existence evidence complete","Ownership and control information complete","Risk rating documented and supported","Screening evidence reviewed","Purpose / nature of relationship documented","Expected activity captured","Source of funds / wealth addressed where required","Approvals and exceptions evidenced"];
function renderQa(){$("#qaList").innerHTML=qaItems.map((x,i)=>'<div class="field"><label><input type="checkbox" class="qac" data-i="'+i+'"> '+x+'</label></div>').join("")}
function qaResult(){const checked=[...document.querySelectorAll(".qac")],miss=checked.filter(x=>!x.checked).map(x=>qaItems[+x.dataset.i]),score=Math.round((checked.length-miss.length)/checked.length*100);$("#qaOut").innerHTML='<div class="metricgrid"><div class="metric"><small>Checklist completion</small><strong>'+score+'%</strong></div><div class="metric"><small>Open items</small><strong>'+miss.length+'</strong></div></div><div class="result"><strong>Items requiring review</strong>\n'+(miss.length?miss.map(x=>"• "+esc(x)).join("\n"):"None on this generic checklist.")+'\n\nReviewer notes: '+esc($("#qaNotes").value||"None")+'\n\nThis checklist is generic and should be aligned to your institution\'s approved KYC/AML procedures.</div>'}