const tools=[
["url-cleaner","Links & Web","URL Cleaner","Strip common tracking parameters from a URL."],["url-inspector","Links & Web","URL Inspector","Break a URL into host, path and parameters."],["utm-builder","Links & Web","UTM Builder","Build campaign URLs without manual query-string editing."],["qr-payload","Links & Web","QR Payload Prep","Validate and normalize text or URLs before QR creation."],
["text-cleaner","Text","Text Cleaner","Normalize whitespace and blank lines."],["case-converter","Text","Case Converter","Convert text to upper, lower or title case."],["line-tools","Text","Line Tools","Sort, trim and remove duplicate lines."],["text-compare","Text","Compare Text","Find line-level additions and removals."],["word-stats","Text","Word & Reading Stats","Count words, characters, lines and reading time."],["ai-signals","Text","AI Writing Signals","Inspect stylistic patterns sometimes associated with generated text — signals, not proof."],["style-compare","Text","Writing Style Compare","Compare measurable writing-style characteristics across two samples."],
["decision-matrix","Productivity","Decision Matrix","Compare options using weighted criteria."],["percentage-change","Productivity","Percentage Change","Calculate absolute and percentage change."],["deadline-planner","Productivity","Deadline Planner","Turn workload and time into a daily target."],["meeting-cost","Productivity","Meeting Cost","Estimate the people-cost of a meeting."],["habit-insights","Productivity","Habit Insights","Analyze your own daily habit data for correlations and patterns, locally."],
["json-formatter","Developer","JSON Formatter","Validate and pretty-print JSON locally."],["base64","Developer","Base64 Encode / Decode","Encode or decode UTF-8 text locally."],["timestamp","Developer","Timestamp Converter","Convert Unix timestamps and ISO dates."],["slug","Developer","Slug Generator","Turn a title into a clean URL slug."],
["password","Privacy & Safety","Password Generator","Generate a strong random password in your browser."],["tracking-check","Privacy & Safety","Tracking Parameter Detector","Identify common tracking parameters without changing the URL."],["lookalike","Privacy & Safety","Domain Lookalike Check","Highlight suspicious characters and punycode in a hostname."],["metadata","Privacy & Safety","Text Metadata Check","Spot emails, phone-like numbers and URL parameters in pasted text."],
["kyc-remediation","Compliance & AML","KYC Remediation Planner","Calculate throughput and staffing needs."],["ubo-direct","Compliance & AML","UBO Direct Ownership","Flag direct holdings against a selected threshold."],["ownership-chain","Compliance & AML","Ownership Chain Calculator","Calculate indirect ownership across a simple chain."],["kyc-qa","Compliance & AML","KYC QA Checker","Run a generic file-quality checklist."],["kyc-refresh","Compliance & AML","KYC Refresh Calculator","Calculate a next-review date from a chosen cycle."],["sla-aging","Compliance & AML","KYC SLA Aging","Calculate case age and remaining SLA days."],["control-sample","Compliance & AML","Control Sample Calculator","Calculate a simple percentage-based review sample."],["risk-matrix","Compliance & AML","Risk Matrix","Combine likelihood and impact into a transparent score."],["investigation-timeline","Compliance & AML","Investigation Timeline","Sort case events into a clean chronology."],["sow-sof","Compliance & AML","SoW / SoF Checklist","Generate a generic evidence checklist by stated source."],["change-impact","Compliance & AML","Change Impact Worksheet","Structure regulatory-change impact and actions."]
];
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function renderCatalog(){const box=$("#toolCatalog");if(!box)return;const q=($("#toolSearch")?.value||"").toLowerCase().trim(),cat=$("#categoryFilter")?.value||"All categories";const visible=tools.filter(t=>t[1]!=="Compliance & AML"&&(cat==="All categories"||t[1]===cat)&&(!q||t.join(" ").toLowerCase().includes(q)));box.innerHTML=visible.length?visible.map(t=>'<div class="toolcard"><span class="tag">'+t[1]+'</span><h3>'+t[2]+'</h3><p>'+t[3]+'</p><button class="btn alt" onclick="openTool(\''+t[0]+'\')">Open</button></div>').join(""):'<div class="empty">No matching tools. Try another search or category.</div>'}
const field=(id,label,type="text",val="")=>'<div class="field"><label>'+label+'</label><input id="'+id+'" type="'+type+'" value="'+val+'"></div>';
function shell(t,body){return '<div class="workspace-head"><div><span class="tag">'+t[1]+'</span><h2>'+t[2]+'</h2><p class="desc">'+t[3]+'</p></div><button class="btn alt" onclick="closeTool()">Close</button></div>'+body+'<div id="out"></div>'}
function openTool(id){const t=tools.find(x=>x[0]===id),w=$("#workspace");let b="";
if(id==="url-cleaner"||id==="url-inspector"){b='<div class="field"><label>URL</label><textarea id="v" rows="4"></textarea></div><button class="btn" onclick="urlTool(\''+id+'\')">Run</button>'}
else if(id==="utm-builder"){b=field("base","Destination URL")+field("source","Source")+field("medium","Medium")+field("campaign","Campaign")+'<button class="btn" onclick="utm()">Build URL</button>'}
else if(id==="qr-payload"){b='<div class="field"><label>Text or URL</label><textarea id="v" rows="6"></textarea></div><button class="btn" onclick="qrPrep()">Prepare</button>'}
else if(id==="case-converter"){b='<div class="field"><label>Text</label><textarea id="v" rows="10"></textarea></div><div class="actions"><button class="btn" onclick="caseConvert(\'upper\')">UPPER</button><button class="btn alt" onclick="caseConvert(\'lower\')">lower</button><button class="btn alt" onclick="caseConvert(\'title\')">Title Case</button><button class="btn alt" onclick="caseConvert(\'sentence\')">Sentence case</button></div>'}
else if(["text-cleaner","line-tools","word-stats"].includes(id)){b='<div class="field"><label>Text</label><textarea id="v" rows="10"></textarea></div><div class="actions"><button class="btn" onclick="textTool(\''+id+'\')">Run</button></div>'}
else if(id==="ai-signals"){b='<div class="field"><label>Text to inspect</label><textarea id="v" rows="12"></textarea></div><button class="btn" onclick="aiSignals()">Analyze signals</button>'}
else if(id==="style-compare"){b='<div class="grid2"><div class="field"><label>Reference sample</label><textarea id="a" rows="10"></textarea></div><div class="field"><label>Comparison sample</label><textarea id="b" rows="10"></textarea></div></div><button class="btn" onclick="styleCompare()">Compare style</button>'}
else if(id==="text-compare"){b='<div class="grid2"><div class="field"><label>Version A</label><textarea id="a" rows="10"></textarea></div><div class="field"><label>Version B</label><textarea id="b" rows="10"></textarea></div></div><button class="btn" onclick="compare()">Compare</button>'}
else if(id==="decision-matrix"){b=field("oa","Option A")+field("ob","Option B")+'<div class="field"><label>Criteria: name, weight, A score, B score</label><textarea id="v" rows="6">Cost,3,8,6\nQuality,5,8,7</textarea></div><button class="btn" onclick="decision()">Calculate</button>'}
else if(id==="percentage-change"){b=field("old","Old value","number","100")+field("newv","New value","number","120")+'<button class="btn" onclick="pct()">Calculate</button>'}
else if(id==="deadline-planner"){b=field("work","Work items","number","500")+field("days","Working days","number","20")+'<button class="btn" onclick="deadline()">Calculate</button>'}
else if(id==="meeting-cost"){b=field("people","People","number","6")+field("mins","Minutes","number","60")+field("hourly","Average hourly cost","number","100")+'<button class="btn" onclick="meeting()">Calculate</button>'}
else if(id==="habit-insights"){b='<p class="note">Paste CSV-style rows: date,sleep_hours,exercise_minutes,focus_score (1-10). Your data stays in this browser.</p><div class="field"><label>Daily data</label><textarea id="v" rows="11">2026-09-15,7.5,30,8\n2026-09-16,6,0,5\n2026-09-17,8,45,9</textarea></div><button class="btn" onclick="habitInsights()">Analyze patterns</button>'}
else if(id==="json-formatter"){b='<div class="field"><label>JSON</label><textarea id="v" rows="12"></textarea></div><button class="btn" onclick="jsonFmt()">Format</button>'}
else if(id==="base64"){b='<div class="field"><label>Text</label><textarea id="v" rows="8"></textarea></div><div class="actions"><button class="btn" onclick="b64(1)">Encode</button><button class="btn alt" onclick="b64(0)">Decode</button></div>'}
else if(id==="timestamp"){b=field("v","Unix seconds, Unix milliseconds, or ISO date/time")+'<button class="btn" onclick="timeConvert()">Convert</button>'}
else if(id==="slug"){b=field("v","Title or phrase")+'<button class="btn" onclick="slugify()">Generate</button>'}
else if(id==="password"){b=field("len","Length","number","20")+'<button class="btn" onclick="passwordGen()">Generate</button>'}
else if(id==="tracking-check"){b=field("v","URL")+'<button class="btn" onclick="trackingCheck()">Inspect</button>'}
else if(id==="lookalike"){b=field("v","Domain or URL")+'<button class="btn" onclick="lookalike()">Check</button>'}
else if(id==="metadata"){b='<div class="field"><label>Text</label><textarea id="v" rows="10"></textarea></div><button class="btn" onclick="metadataCheck()">Check</button>'}
else if(id==="kyc-remediation"){b=field("total","Total files","number","3600")+field("done","Completed","number","0")+field("analysts","Analysts","number","21")+field("days","Working days","number","60")+field("rate","Files / analyst / day","number","2.5")+'<button class="btn" onclick="remediation()">Calculate</button>'}
else if(id==="ubo-direct"){b=field("threshold","Review threshold %","number","25")+'<div class="field"><label>Owners: name, percentage (one per line)</label><textarea id="v" rows="7">Owner 1,60\nOwner 2,40</textarea></div><button class="btn" onclick="ubo()">Calculate</button>'}
else if(id==="ownership-chain"){b='<p class="note">Example: Person owns 60% of HoldCo; HoldCo owns 70% of Target.</p>'+field("p1","First ownership %","number","60")+field("p2","Second ownership %","number","70")+'<button class="btn" onclick="chain()">Calculate indirect ownership</button>'}
else if(id==="kyc-qa"){b='<div id="qa"></div><button class="btn" onclick="qa()">Generate result</button>'}
else if(id==="kyc-refresh"){b=field("date","Last review date","date")+field("months","Review cycle (months)","number","12")+'<button class="btn" onclick="refresh()">Calculate</button>'}
else if(id==="sla-aging"){b=field("start","Case start date","date")+field("sla","SLA days","number","10")+'<button class="btn" onclick="aging()">Calculate</button>'}
else if(id==="control-sample"){b=field("population","Population","number","1000")+field("samplepct","Sample %","number","10")+'<button class="btn" onclick="sample()">Calculate</button>'}
else if(id==="risk-matrix"){b=field("likelihood","Likelihood (1-5)","number","3")+field("impact","Impact (1-5)","number","4")+'<button class="btn" onclick="risk()">Calculate</button>'}
else if(id==="investigation-timeline"){b='<div class="field"><label>Events: YYYY-MM-DD | event</label><textarea id="v" rows="9"></textarea></div><button class="btn" onclick="timeline()">Sort timeline</button>'}
else if(id==="sow-sof"){b='<div class="field"><label>Stated source</label><select id="source"><option>Salary</option><option>Business ownership</option><option>Inheritance</option><option>Property sale</option><option>Investment</option></select></div><button class="btn" onclick="sow()">Generate generic checklist</button>'}
else if(id==="change-impact"){b=field("change","Regulatory change")+field("area","Affected business / process")+field("owner","Action owner")+field("due","Due date","date")+'<button class="btn" onclick="impact()">Build worksheet</button>'}
w.innerHTML=shell(t,b);w.classList.add("active");w.scrollIntoView({behavior:"smooth"});if(id==="kyc-qa")$("#qa").innerHTML=["Identity/legal existence","Ownership/control","Risk rating","Screening","Purpose/nature","Expected activity","Approvals/exceptions"].map((x,i)=>'<div class="field"><label><input class="q" type="checkbox"> '+x+'</label></div>').join("")}
function closeTool(){$("#workspace").classList.remove("active")}function result(x){$("#out").innerHTML='<div class="result">'+x+'</div>'}
function urlTool(id){try{let u=new URL($("#v").value.trim());if(!/^https?:$/.test(u.protocol))return result("Use a complete http:// or https:// URL.");if(id==="url-inspector")return result("<strong>Host</strong> "+esc(u.host)+"\n<strong>Path</strong> "+esc(u.pathname)+"\n<strong>Parameters</strong>\n"+([...u.searchParams].map(x=>esc(x[0])+" = "+esc(x[1])).join("\n")||"None"));const explain={fbclid:"Facebook click identifier",gclid:"Google Ads click identifier",msclkid:"Microsoft Ads click identifier",mc_cid:"Mailchimp campaign identifier",mc_eid:"Mailchimp recipient identifier",igshid:"Instagram sharing identifier"};let rm=[];[...u.searchParams.keys()].forEach(k=>{const low=k.toLowerCase();if(low.startsWith("utm_")||low in explain){rm.push([k,low.startsWith("utm_")?"Campaign attribution parameter":explain[low]]);u.searchParams.delete(k)}});result("<strong>Clean URL</strong>\n"+esc(u.href)+"\n\n<strong>Removed</strong>\n"+(rm.length?rm.map(x=>esc(x[0])+" — "+esc(x[1])).join("\n"):"No common tracking parameters found.")+"\n\nOnly known tracking parameters are removed; destination and other query parameters are preserved.")}catch{result("Enter a valid complete URL, including https://.")}}
function utm(){try{let u=new URL($("#base").value);[["utm_source","#source"],["utm_medium","#medium"],["utm_campaign","#campaign"]].forEach(x=>{let v=$(x[1]).value.trim();if(v)u.searchParams.set(x[0],v)});result(esc(u.href))}catch{result("Enter a valid destination URL.")}}
function qrPrep(){let v=$("#v").value.trim();try{let u=new URL(v);v=u.href}catch{}result("Normalized payload:\n"+esc(v)+"\n\nReady to pass to a QR renderer. No QR image is generated in this v1 utility.")}
function textTool(id){let v=$("#v").value;if(id==="text-cleaner")v=v.split("\n").map(x=>x.replace(/[ \t]+/g," ").trim()).join("\n").replace(/\n{3,}/g,"\n\n").trim();if(id==="case-converter")v=v.toLowerCase().replace(/\b\p{L}/gu,c=>c.toUpperCase());if(id==="line-tools")v=[...new Set(v.split("\n").map(x=>x.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b)).join("\n");if(id==="word-stats"){let words=v.trim()?v.trim().split(/\s+/).length:0;return result(words+" words · "+[...v].length+" characters · "+v.split("\n").length+" lines · ~"+Math.max(1,Math.ceil(words/200))+" min read")}$("#v").value=v;result("Updated locally.")}
function caseConvert(mode){let v=$("#v").value;if(mode==="upper")v=v.toUpperCase();else if(mode==="lower")v=v.toLowerCase();else if(mode==="title")v=v.toLowerCase().replace(/\b\p{L}/gu,x=>x.toUpperCase());else v=v.toLowerCase().replace(/(^|[.!?]\s+)\p{L}/gu,x=>x.toUpperCase());$("#v").value=v;result(esc(v))}
function lcsDiff(A,B){const n=A.length,m=B.length,dp=Array.from({length:n+1},()=>new Uint16Array(m+1));for(let i=n-1;i>=0;i--)for(let j=m-1;j>=0;j--)dp[i][j]=A[i]===B[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0,out=[];while(i<n||j<m){if(i<n&&j<m&&A[i]===B[j]){out.push([" ",A[i]]);i++;j++}else if(j<m&&(i===n||dp[i][j+1]>=dp[i+1][j]))out.push(["+",B[j++]]);else out.push(["-",A[i++]])}return out}
function compare(){let A=$("#a").value.split("\n"),B=$("#b").value.split("\n"),d=lcsDiff(A,B),changed=d.filter(x=>x[0]!==" ");result("<strong>Changes: "+changed.length+"</strong>\n"+esc(d.map(x=>x[0]+" "+x[1]).join("\n"))+"\n\n+ added · - removed · unchanged lines retained for context.")}
function decision(){let rows=$("#v").value.split("\n").map(x=>x.map(y=>y.trim())).filter(r=>r.some(Boolean)),tw=0,a=0,b=0,used=0;for(const r of rows){const w=Number(r[1]),x=Number(r[2]),y=Number(r[3]);if(r.length<4||!Number.isFinite(w)||w<=0||!Number.isFinite(x)||!Number.isFinite(y))continue;tw+=w;a+=w*x;b+=w*y;used++}if(!used||!tw)return result("Add at least one valid criterion: name, positive weight, Option A score, Option B score.");const oa=$("#oa").value.trim()||"Option A",ob=$("#ob").value.trim()||"Option B";result("<strong>Weighted scores</strong>\n"+esc(oa)+": "+(a/tw).toFixed(2)+"\n"+esc(ob)+": "+(b/tw).toFixed(2)+"\nCriteria used: "+used+"\n\nScores reflect only your inputs; the tool does not choose for you.")}
function pct(){let a=+$("#old").value,b=+$("#newv").value;if(!Number.isFinite(a)||!Number.isFinite(b))return result("Enter two valid numbers.");const absolute=b-a;if(a===0)return result("Absolute change: "+absolute.toFixed(2)+"\nPercentage change: not defined when the starting value is zero.");const p=absolute/Math.abs(a)*100;result("Absolute change: "+absolute.toFixed(2)+"\nPercentage change: "+p.toFixed(2)+"%\nDirection: "+(absolute>0?"increase":absolute<0?"decrease":"no change"))}
function deadline(){const work=+$("#work").value,days=+$("#days").value;if(!Number.isFinite(work)||work<0)return result("Enter a valid workload of 0 or more.");if(!Number.isFinite(days)||days<=0)return result("Working days must be greater than zero.");result("Required average: "+(work/days).toFixed(2)+" items per working day.")}
function meeting(){const p=+$("#people").value,m=+$("#mins").value,h=+$("#hourly").value;if(!Number.isFinite(p)||p<1||!Number.isFinite(m)||m<=0||!Number.isFinite(h)||h<0)return result("Enter at least 1 person, a duration greater than zero, and a valid hourly cost.");result("Estimated meeting cost: "+(p*(m/60)*h).toFixed(2)+" (in the currency of your hourly-cost input).")}
function remediation(){let rem=Math.max(0,+$("#total").value-+$("#done").value),d=+$("#days").value,n=+$("#analysts").value,r=+$("#rate").value,req=rem/d,cap=n*r,need=Math.ceil(req/r);result("Files remaining: "+rem+"\nRequired/day: "+req.toFixed(1)+"\nCurrent capacity/day: "+cap.toFixed(1)+"\nAdditional analysts at entered rate: "+Math.max(0,need-n)+"\n\nPlanning aid; validate assumptions.")}
function ubo(){let th=+$("#threshold").value,rows=$("#v").value.split("\n").map(x=>x.split(",")),sum=0,flags=[];rows.forEach(r=>{let p=+r[1];sum+=p;if(p>=th)flags.push(r[0].trim()+": "+p+"%")});result("Total entered: "+sum.toFixed(2)+"%\nAt/above selected threshold:\n"+esc(flags.join("\n")||"None")+"\n\nThreshold flagging is not a legal UBO determination.")}
function chain(){result("Indirect ownership: "+((+$("#p1").value/100)*(+$("#p2").value/100)*100).toFixed(2)+"%\n\nMultiply each ownership link in the chain. Control and aggregation rules may require separate analysis.")}
function qa(){let q=[...document.querySelectorAll(".q")],miss=q.filter(x=>!x.checked).length;result("Checklist completion: "+Math.round((q.length-miss)/q.length*100)+"%\nOpen items: "+miss+"\n\nGeneric QA aid; align it to approved procedures.")}
function refresh(){let d=new Date($("#date").value+"T00:00:00");if(isNaN(d))return result("Choose a valid date.");d.setMonth(d.getMonth()+ +$("#months").value);result("Calculated next review date: "+d.toISOString().slice(0,10)+"\n\nUses the cycle you entered; it does not prescribe a regulatory frequency.")}
function aging(){let s=new Date($("#start").value+"T00:00:00"),now=new Date();if(isNaN(s))return result("Choose a valid start date.");let age=Math.floor((now-s)/86400000),sla=+$("#sla").value;result("Calendar age: "+age+" days\nRemaining to entered SLA: "+(sla-age)+" days\n\nCalendar-day calculation.")}
function sample(){let n=Math.ceil(+$("#population").value*+$("#samplepct").value/100);result("Calculated sample: "+n+" items.\n\nThis is percentage-based sizing only, not a statistical assurance methodology.")}
function risk(){let l=+$("#likelihood").value,i=+$("#impact").value,s=l*i;result("Risk score: "+s+" / 25\nLikelihood × impact = "+l+" × "+i+".\n\nInterpretation thresholds should come from your approved methodology.")}
function timeline(){let rows=$("#v").value.split("\n").filter(Boolean).sort((a,b)=>a.localeCompare(b));result(esc(rows.join("\n")))}
function sow(){let m={"Salary":["Employment evidence","Recent payslips / income evidence","Relevant account evidence"],"Business ownership":["Ownership evidence","Business financial/income evidence","Distribution/dividend evidence where relevant"],"Inheritance":["Inheritance/probate evidence","Evidence of receipt / transfer"],"Property sale":["Sale agreement","Ownership evidence","Evidence of sale proceeds"],"Investment":["Investment statements","Evidence of disposal/redemption and proceeds"]};result("<strong>Generic prompts for "+esc($("#source").value)+"</strong>\n• "+m[$("#source").value].join("\n• ")+"\n\nActual evidence depends on risk, facts, policy and jurisdiction.")}
function impact(){result("<strong>Change</strong> "+esc($("#change").value)+"\n<strong>Affected area</strong> "+esc($("#area").value)+"\n<strong>Owner</strong> "+esc($("#owner").value)+"\n<strong>Due</strong> "+esc($("#due").value)+"\n\nNext: assess applicability → map controls/policies → evidence decision → track action.")}
function routeIntent(){const q=$("#intent").value.toLowerCase().trim();if(!q)return $("#intentResult").textContent="Describe what you want to do.";const rules=[["url-cleaner",/clean|remove.*track|tracking.*remove|strip.*url/],["tracking-check",/detect.*track|tracking.*param|inspect.*track/],["url-inspector",/inspect.*url|url.*parts|query.*param/],["utm-builder",/utm|campaign.*url/],["json-formatter",/json/],["base64",/base64|encode|decode/],["timestamp",/timestamp|unix|epoch/],["slug",/slug|url.*title/],["password",/password|random.*pass/],["text-compare",/compare.*text|diff|version.*text/],["text-cleaner",/clean.*text|whitespace|blank.*line/],["case-converter",/uppercase|lowercase|title case|sentence case/],["word-stats",/word count|character count|reading time/],["ai-signals",/ai.*writ|generated.*text|ai.*text/],["style-compare",/writing style|compare.*style|voice.*compare/],["decision-matrix",/decision|compare.*option|weighted.*criteria/],["percentage-change",/percentage.*change|percent.*change/],["deadline-planner",/deadline|daily target|workload/],["meeting-cost",/meeting.*cost/],["habit-insights",/habit|sleep.*focus|correlation/],["lookalike",/lookalike|suspicious.*domain|punycode/],["metadata",/metadata|personal.*info|email.*phone/]];const hit=rules.find(r=>r[1].test(q));if(hit){$("#intentResult").textContent="Opening the best matching tool…";return openTool(hit[0])}const words=q.split(/\W+/).filter(w=>w.length>3),ranked=tools.filter(t=>t[1]!=="Compliance & AML").map(t=>({t,score:words.reduce((s,w)=>s+(t.slice(2).join(" ").toLowerCase().includes(w)?1:0),0)})).sort((a,b)=>b.score-a.score);if(ranked[0]?.score){$("#intentResult").textContent="Opening "+ranked[0].t[2]+"…";openTool(ranked[0].t[0])}else $("#intentResult").textContent="No confident match yet. Browse or search the tools below."}
document.addEventListener("DOMContentLoaded",renderCatalog);
function copyResult(){const e=$("#out .result");if(e&&navigator.clipboard)navigator.clipboard.writeText(e.innerText)}
const _result=result;result=function(x){_result(x);const o=$("#out");if(o&&o.querySelector(".result"))o.insertAdjacentHTML("beforeend",'<div class="actions"><button class="btn alt" onclick="copyResult()">Copy result</button></div>')};

function downloadResult(){
 const e=$("#out .result"); if(!e)return;
 const blob=new Blob([e.innerText],{type:"text/plain;charset=utf-8"});
 const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="intellitools-result.txt";a.click();URL.revokeObjectURL(a.href);
}
function clearWorkspace(){
 document.querySelectorAll("#workspace input").forEach(x=>{if(x.type==="checkbox")x.checked=false;else x.value=""});
 document.querySelectorAll("#workspace textarea").forEach(x=>x.value="");
 const o=$("#out");if(o)o.innerHTML="";
}
const _result2=result;result=function(x){
 _result2(x);const o=$("#out");if(o&&!o.querySelector(".export-actions"))o.insertAdjacentHTML("beforeend",'<div class="actions export-actions"><button class="btn alt" onclick="downloadResult()">Download .txt</button><button class="btn alt" onclick="clearWorkspace()">Clear</button></div>');
};

function jsonFmt(){try{const x=JSON.stringify(JSON.parse($("#v").value),null,2);$("#v").value=x;result(esc(x))}catch(e){result("Invalid JSON: "+esc(e.message))}}
function b64(enc){try{const v=$("#v").value;const out=enc?btoa(unescape(encodeURIComponent(v))):decodeURIComponent(escape(atob(v.trim())));$("#v").value=out;result(esc(out))}catch{result("Unable to process this input.")}}
function timeConvert(){let v=$("#v").value.trim(),d;if(/^\d{10}$/.test(v))d=new Date(+v*1000);else if(/^\d{13}$/.test(v))d=new Date(+v);else d=new Date(v);if(isNaN(d))return result("Enter a valid Unix timestamp or date/time.");result("ISO: "+d.toISOString()+"\nUnix seconds: "+Math.floor(d.getTime()/1000)+"\nUnix milliseconds: "+d.getTime())}
function slugify(){const s=$("#v").value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");result(esc(s||"Nothing to convert."))}
function passwordGen(){let n=Math.min(128,Math.max(8,+$("#len").value||20)),chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*_-",a=new Uint32Array(n);crypto.getRandomValues(a);result(esc([...a].map(x=>chars[x%chars.length]).join(""))+"\n\nGenerated locally with browser cryptographic randomness.")}
function trackingCheck(){try{const u=new URL($("#v").value.trim()),known=["fbclid","gclid","msclkid","mc_cid","mc_eid","igshid"],hits=[...u.searchParams.keys()].filter(k=>k.toLowerCase().startsWith("utm_")||known.includes(k.toLowerCase()));result(hits.length?"Tracking-like parameters found:\n"+esc(hits.join("\n")):"No common tracking parameters detected.")}catch{result("Enter a valid complete URL.")}}
function lookalike(){try{let v=$("#v").value.trim();if(!/^https?:\/\//i.test(v))v="https://"+v;const h=new URL(v).hostname,non=/[^\x00-\x7F]/.test(h),puny=h.includes("xn--");result("Hostname: "+esc(h)+"\nPunycode: "+(puny?"Yes":"No")+"\nNon-ASCII characters: "+(non?"Yes":"No")+"\n\nThis is a structural warning only, not a reputation or malware check.")}catch{result("Enter a valid domain or URL.")}}
function metadataCheck(){const v=$("#v").value,emails=v.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[],phones=v.match(/(?:\+?\d[\d ()-]{7,}\d)/g)||[],urls=v.match(/https?:\/\/\S+/gi)||[];result("Emails found: "+emails.length+"\nPhone-like strings: "+phones.length+"\nURLs: "+urls.length+"\nURLs with query parameters: "+urls.filter(x=>x.includes("?")).length+"\n\nReview before sharing if the text may contain personal or tracking information.")}

function styleMetrics(v){const s=(v.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[]).map(x=>x.trim()).filter(Boolean),w=v.toLowerCase().match(/[\p{L}\p{N}']+/gu)||[],uniq=new Set(w),lens=s.map(x=>(x.match(/[\p{L}\p{N}']+/gu)||[]).length),avg=lens.length?lens.reduce((a,b)=>a+b,0)/lens.length:0,variance=lens.length?lens.reduce((a,b)=>a+(b-avg)**2,0)/lens.length:0;return{words:w.length,sent:s.length,avg,sd:Math.sqrt(variance),lex:w.length?uniq.size/w.length:0,paras:v.split(/\n\s*\n/).filter(x=>x.trim()).length,punct:(v.match(/[;:—-]/g)||[]).length}}
function aiSignals(){const v=$("#v").value.trim();if(v.length<200)return result("Add a longer sample (at least about 200 characters) for a more meaningful signal check.");const m=styleMetrics(v),lower=v.toLowerCase(),trans=["moreover","furthermore","additionally","in conclusion","overall","however","therefore"],hits=trans.reduce((n,x)=>n+(lower.split(x).length-1),0),signals=[];if(m.sent>=5&&m.sd<5)signals.push("Sentence lengths are unusually uniform");if(m.words>100&&m.lex<.45)signals.push("Vocabulary repetition is relatively high");if(hits>=3)signals.push("Repeated formal transition phrases detected");if(m.paras>=3&&m.sent/m.paras>=2&&m.sent/m.paras<=5)signals.push("Paragraph structure is fairly regular");const level=signals.length>=3?"Elevated":signals.length>=1?"Some":"Few";result("<strong>AI-associated writing signals: "+level+"</strong>\n"+(signals.length?"• "+esc(signals.join("\n• ")):"No strong signals in the limited checks used.")+"\n\nThis cannot determine authorship. Human and AI-assisted writing can produce the same patterns; editing can substantially change them.")}
function styleCompare(){const a=$("#a").value.trim(),b=$("#b").value.trim();if(a.length<150||b.length<150)return result("Use two reasonably sized samples (about 150+ characters each).");const x=styleMetrics(a),y=styleMetrics(b),diff=(p,scale)=>Math.min(1,Math.abs(x[p]-y[p])/scale),d=(diff("avg",15)+diff("sd",12)+diff("lex",.35)+diff("punct",20))/4,similar=d<.22?"Broadly similar":d<.45?"Mixed":"Noticeably different";result("<strong>Style comparison: "+similar+"</strong>\nAverage sentence length: "+x.avg.toFixed(1)+" vs "+y.avg.toFixed(1)+" words\nSentence-length variation: "+x.sd.toFixed(1)+" vs "+y.sd.toFixed(1)+"\nLexical diversity: "+x.lex.toFixed(2)+" vs "+y.lex.toFixed(2)+"\n\nThis compares surface writing characteristics only. It does not establish identity, authorship, or AI use.")}

function pearson(a,b){const n=a.length;if(n<3)return null,ma=a.reduce((x,y)=>x+y,0)/n,mb=b.reduce((x,y)=>x+y,0)/n;let num=0,da=0,db=0;for(let i=0;i<n;i++){let x=a[i]-ma,y=b[i]-mb;num+=x*y;da+=x*x;db+=y*y}return da&&db?num/Math.sqrt(da*db):null}
function habitInsights(){const rows=$("#v").value.split("\n").map(x=>x.trim()).filter(Boolean).map(x=>x.split(",")).filter(r=>r.length>=4).map(r=>({date:r[0],sleep:+r[1],exercise:+r[2],focus:+r[3]})).filter(r=>Number.isFinite(r.sleep)&&Number.isFinite(r.exercise)&&Number.isFinite(r.focus));if(rows.length<3)return result("Add at least 3 valid daily rows. More observations will make the pattern analysis more meaningful.");const sleep=pearson(rows.map(r=>r.sleep),rows.map(r=>r.focus)),exercise=pearson(rows.map(r=>r.exercise),rows.map(r=>r.focus)),avg=x=>x.reduce((a,b)=>a+b,0)/x.length,fmt=x=>x==null?"Not enough variation":(x>=.5?"Positive":x<=-.5?"Negative":"Weak/mixed")+" (r="+x.toFixed(2)+")";result("<strong>"+rows.length+" days analyzed locally</strong>\nAverage sleep: "+avg(rows.map(r=>r.sleep)).toFixed(1)+" h\nAverage exercise: "+avg(rows.map(r=>r.exercise)).toFixed(0)+" min\nAverage focus: "+avg(rows.map(r=>r.focus)).toFixed(1)+"/10\n\nSleep ↔ focus: "+fmt(sleep)+"\nExercise ↔ focus: "+fmt(exercise)+"\n\nThese are associations in your entered data, not evidence that one factor caused another. Larger, consistent datasets are more informative.")}
