const tools=[
["url-cleaner","Links & Web","URL Cleaner","Strip common tracking parameters from a URL."],["url-inspector","Links & Web","URL Inspector","Break a URL into host, path and parameters."],["utm-builder","Links & Web","UTM Builder","Build campaign URLs without manual query-string editing."],["qr-payload","Links & Web","QR Payload Prep","Validate and normalize text or URLs before QR creation."],
["text-cleaner","Text","Text Cleaner","Normalize whitespace and blank lines."],["case-converter","Text","Case Converter","Convert text to upper, lower or title case."],["line-tools","Text","Line Tools","Sort, trim and remove duplicate lines."],["text-compare","Text","Compare Text","Find line-level additions and removals."],["word-stats","Text","Word & Reading Stats","Count words, characters, lines and reading time."],
["decision-matrix","Productivity","Decision Matrix","Compare options using weighted criteria."],["percentage-change","Productivity","Percentage Change","Calculate absolute and percentage change."],["deadline-planner","Productivity","Deadline Planner","Turn workload and time into a daily target."],["meeting-cost","Productivity","Meeting Cost","Estimate the people-cost of a meeting."],
["json-formatter","Developer","JSON Formatter","Validate and pretty-print JSON locally."],["base64","Developer","Base64 Encode / Decode","Encode or decode UTF-8 text locally."],["timestamp","Developer","Timestamp Converter","Convert Unix timestamps and ISO dates."],["slug","Developer","Slug Generator","Turn a title into a clean URL slug."],
["password","Privacy & Safety","Password Generator","Generate a strong random password in your browser."],["tracking-check","Privacy & Safety","Tracking Parameter Detector","Identify common tracking parameters without changing the URL."],["lookalike","Privacy & Safety","Domain Lookalike Check","Highlight suspicious characters and punycode in a hostname."],["metadata","Privacy & Safety","Text Metadata Check","Spot emails, phone-like numbers and URL parameters in pasted text."],
["kyc-remediation","Compliance & AML","KYC Remediation Planner","Calculate throughput and staffing needs."],["ubo-direct","Compliance & AML","UBO Direct Ownership","Flag direct holdings against a selected threshold."],["ownership-chain","Compliance & AML","Ownership Chain Calculator","Calculate indirect ownership across a simple chain."],["kyc-qa","Compliance & AML","KYC QA Checker","Run a generic file-quality checklist."],["kyc-refresh","Compliance & AML","KYC Refresh Calculator","Calculate a next-review date from a chosen cycle."],["sla-aging","Compliance & AML","KYC SLA Aging","Calculate case age and remaining SLA days."],["control-sample","Compliance & AML","Control Sample Calculator","Calculate a simple percentage-based review sample."],["risk-matrix","Compliance & AML","Risk Matrix","Combine likelihood and impact into a transparent score."],["investigation-timeline","Compliance & AML","Investigation Timeline","Sort case events into a clean chronology."],["sow-sof","Compliance & AML","SoW / SoF Checklist","Generate a generic evidence checklist by stated source."],["change-impact","Compliance & AML","Change Impact Worksheet","Structure regulatory-change impact and actions."]
];
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function renderCatalog(){const box=$("#toolCatalog");if(!box)return;const q=($("#toolSearch")?.value||"").toLowerCase().trim(),cat=$("#categoryFilter")?.value||"All categories";const visible=tools.filter(t=>t[1]!=="Compliance & AML"&&(cat==="All categories"||t[1]===cat)&&(!q||t.join(" ").toLowerCase().includes(q)));box.innerHTML=visible.length?visible.map(t=>'<div class="toolcard"><span class="tag">'+t[1]+'</span><h3>'+t[2]+'</h3><p>'+t[3]+'</p><button class="btn alt" onclick="openTool(\''+t[0]+'\')">Open</button></div>').join(""):'<div class="empty">No matching tools. Try another search or category.</div>'}
const field=(id,label,type="text",val="")=>'<div class="field"><label>'+label+'</label><input id="'+id+'" type="'+type+'" value="'+val+'"></div>';
function shell(t,body){return '<div class="workspace-head"><div><span class="tag">'+t[1]+'</span><h2>'+t[2]+'</h2><p class="desc">'+t[3]+'</p></div><button class="btn alt" onclick="closeTool()">Close</button></div>'+body+'<div id="out"></div>'}
function openTool(id){const t=tools.find(x=>x[0]===id),w=$("#workspace");let b="";
if(id==="url-cleaner"||id==="url-inspector"){b='<div class="field"><label>URL</label><textarea id="v" rows="4"></textarea></div><button class="btn" onclick="urlTool(\''+id+'\')">Run</button>'}
else if(id==="utm-builder"){b=field("base","Destination URL")+field("source","Source")+field("medium","Medium")+field("campaign","Campaign")+'<button class="btn" onclick="utm()">Build URL</button>'}
else if(id==="qr-payload"){b='<div class="field"><label>Text or URL</label><textarea id="v" rows="6"></textarea></div><button class="btn" onclick="qrPrep()">Prepare</button>'}
else if(["text-cleaner","case-converter","line-tools","word-stats"].includes(id)){b='<div class="field"><label>Text</label><textarea id="v" rows="10"></textarea></div><div class="actions"><button class="btn" onclick="textTool(\''+id+'\')">Run</button></div>'}
else if(id==="text-compare"){b='<div class="grid2"><div class="field"><label>Version A</label><textarea id="a" rows="10"></textarea></div><div class="field"><label>Version B</label><textarea id="b" rows="10"></textarea></div></div><button class="btn" onclick="compare()">Compare</button>'}
else if(id==="decision-matrix"){b=field("oa","Option A")+field("ob","Option B")+'<div class="field"><label>Criteria: name, weight, A score, B score</label><textarea id="v" rows="6">Cost,3,8,6\nQuality,5,8,7</textarea></div><button class="btn" onclick="decision()">Calculate</button>'}
else if(id==="percentage-change"){b=field("old","Old value","number","100")+field("newv","New value","number","120")+'<button class="btn" onclick="pct()">Calculate</button>'}
else if(id==="deadline-planner"){b=field("work","Work items","number","500")+field("days","Working days","number","20")+'<button class="btn" onclick="deadline()">Calculate</button>'}
else if(id==="meeting-cost"){b=field("people","People","number","6")+field("mins","Minutes","number","60")+field("hourly","Average hourly cost","number","100")+'<button class="btn" onclick="meeting()">Calculate</button>'}
else if(id==="json-formatter"){b='<div class="field"><label>JSON</label><textarea id="v" rows="12"></textarea></div><button class="btn" onclick="jsonFmt()">Format</button>'}
else if(id==="base64"){b='<div class="field"><label>Text</label><textarea id="v" rows="8"></textarea></div><div class="actions"><button class="btn" onclick="b64(1)">Encode</button><button class="btn alt" onclick="b64(0)">Decode</button></div>'}
else if(id==="timestamp"){b=field("v","Unix seconds, Unix milliseconds, or ISO date/time")+'<button class="btn" onclick="timeConvert()">Convert</button>'}
else if(id==="slug"){b=field("v","Title or phrase")+'<button class="btn" onclick="slugify()">Generate</button>'}
else if(id==="password"){b=field("len","Length","number","20")+'<button class="btn" onclick="passwordGen()">Generate</button>'}
else if(id==="tracking-check"){b=field("v","URL")+'<button class="btn" onclick="trackingCheck()">Inspect</button>'}
else if(id==="lookalike"){b=field("v","Domain or URL")+'<button class="btn" onclick="lookalike()">Check</button>'}
else if(id==="metadata"){b='<div class="field"><label>Text</label><textarea id="v" rows="10"></textarea></div><button class="btn" onclick="metadataCheck()">Check</button>'}
else if(id==="kyc-remediation"){b=field("total","Total files","number","3600")+field("done","Completed","number","0")+field("analysts","Analysts","number","21")+field("days","Working days","number","60")+field("rate","Files / analyst / day","number","2.5")+'<button class="btn" onclick="remediation()">Calculate</button>'}
else if(id==="ubo-direct"){b=field("threshold","Review threshold %","number","25")+'<div class="field"><label>Owners: name, percentage (one per line)</label><textarea id="v" rows="7">Owner 1,60\nOwner 2,40</textarea></div><button class="btn" onclick="ubo()">Calculate</button>'}
else if(id==="ownership-chain"){b='<p class="note">Example: Person owns 60% of HoldCo; HoldCo owns 70% of Target.</p>'+field("p1","First ownership %","number","60")+field("p2","Second ownership %","number","70")+'<button class="btn" onclick="chain()">Calculate indirect ownership</button>'}
else if(id==="kyc-qa"){b='<div id="qa"></div><button class="btn" onclick="qa()">Generate result</button>'}
else if(id==="kyc-refresh"){b=field("date","Last review date","date")+field("months","Review cycle (months)","number","12")+'<button class="btn" onclick="refresh()">Calculate</button>'}
else if(id==="sla-aging"){b=field("start","Case start date","date")+field("sla","SLA days","number","10")+'<button class="btn" onclick="aging()">Calculate</button>'}
else if(id==="control-sample"){b=field("population","Population","number","1000")+field("samplepct","Sample %","number","10")+'<button class="btn" onclick="sample()">Calculate</button>'}
else if(id==="risk-matrix"){b=field("likelihood","Likelihood (1-5)","number","3")+field("impact","Impact (1-5)","number","4")+'<button class="btn" onclick="risk()">Calculate</button>'}
else if(id==="investigation-timeline"){b='<div class="field"><label>Events: YYYY-MM-DD | event</label><textarea id="v" rows="9"></textarea></div><button class="btn" onclick="timeline()">Sort timeline</button>'}
else if(id==="sow-sof"){b='<div class="field"><label>Stated source</label><select id="source"><option>Salary</option><option>Business ownership</option><option>Inheritance</option><option>Property sale</option><option>Investment</option></select></div><button class="btn" onclick="sow()">Generate generic checklist</button>'}
else if(id==="change-impact"){b=field("change","Regulatory change")+field("area","Affected business / process")+field("owner","Action owner")+field("due","Due date","date")+'<button class="btn" onclick="impact()">Build worksheet</button>'}
w.innerHTML=shell(t,b);w.classList.add("active");w.scrollIntoView({behavior:"smooth"});if(id==="kyc-qa")$("#qa").innerHTML=["Identity/legal existence","Ownership/control","Risk rating","Screening","Purpose/nature","Expected activity","Approvals/exceptions"].map((x,i)=>'<div class="field"><label><input class="q" type="checkbox"> '+x+'</label></div>').join("")}
function closeTool(){$("#workspace").classList.remove("active")}function result(x){$("#out").innerHTML='<div class="result">'+x+'</div>'}
function urlTool(id){try{let u=new URL($("#v").value.trim());if(id==="url-inspector")return result("<strong>Host</strong> "+esc(u.host)+"\n<strong>Path</strong> "+esc(u.pathname)+"\n<strong>Parameters</strong>\n"+([...u.searchParams].map(x=>esc(x[0])+" = "+esc(x[1])).join("\n")||"None"));let rm=[],keys=["fbclid","gclid","msclkid","mc_cid","mc_eid","igshid"];[...u.searchParams.keys()].forEach(k=>{if(k.toLowerCase().startsWith("utm_")||keys.includes(k.toLowerCase())){rm.push(k);u.searchParams.delete(k)}});result(esc(u.href)+"\n\nRemoved: "+(rm.join(", ")||"none"))}catch{result("Enter a valid complete URL.")}}
function utm(){try{let u=new URL($("#base").value);[["utm_source","#source"],["utm_medium","#medium"],["utm_campaign","#campaign"]].forEach(x=>{let v=$(x[1]).value.trim();if(v)u.searchParams.set(x[0],v)});result(esc(u.href))}catch{result("Enter a valid destination URL.")}}
function qrPrep(){let v=$("#v").value.trim();try{let u=new URL(v);v=u.href}catch{}result("Normalized payload:\n"+esc(v)+"\n\nReady to pass to a QR renderer. No QR image is generated in this v1 utility.")}
function textTool(id){let v=$("#v").value;if(id==="text-cleaner")v=v.split("\n").map(x=>x.replace(/[ \t]+/g," ").trim()).join("\n").replace(/\n{3,}/g,"\n\n").trim();if(id==="case-converter")v=v.toLowerCase().replace(/\b\p{L}/gu,c=>c.toUpperCase());if(id==="line-tools")v=[...new Set(v.split("\n").map(x=>x.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b)).join("\n");if(id==="word-stats"){let words=v.trim()?v.trim().split(/\s+/).length:0;return result(words+" words · "+[...v].length+" characters · "+v.split("\n").length+" lines · ~"+Math.max(1,Math.ceil(words/200))+" min read")}$("#v").value=v;result("Updated locally.")}
function compare(){let A=$("#a").value.split("\n"),B=$("#b").value.split("\n"),del=A.filter(x=>!B.includes(x)),add=B.filter(x=>!A.includes(x));result("<strong>Removed</strong>\n"+esc(del.join("\n")||"None")+"\n\n<strong>Added</strong>\n"+esc(add.join("\n")||"None"))}
function decision(){let rows=$("#v").value.split("\n").map(x=>x.split(",")),tw=0,a=0,b=0;rows.forEach(r=>{let w=+r[1],x=+r[2],y=+r[3];if(w&&x&&y){tw+=w;a+=w*x;b+=w*y}});result(esc($("#oa").value)+": "+(a/tw).toFixed(2)+"\n"+esc($("#ob").value)+": "+(b/tw).toFixed(2)+"\n\nScores reflect only your inputs.")}
function pct(){let a=+$("#old").value,b=+$("#newv").value;result("Absolute change: "+(b-a).toFixed(2)+"\nPercentage change: "+(a?((b-a)/Math.abs(a)*100).toFixed(2):"undefined")+"%")}
function deadline(){result("Required average: "+(+$ ("#work").value/+$ ("#days").value).toFixed(2)+" items per working day.")}
function meeting(){result("Estimated meeting cost: "+((+$("#people").value)*(+$("#mins").value/60)*(+$("#hourly").value)).toFixed(2)+" (in the currency of your hourly-cost input).")}
function remediation(){let rem=Math.max(0,+$("#total").value-+$("#done").value),d=+$("#days").value,n=+$("#analysts").value,r=+$("#rate").value,req=rem/d,cap=n*r,need=Math.ceil(req/r);result("Files remaining: "+rem+"\nRequired/day: "+req.toFixed(1)+"\nCurrent capacity/day: "+cap.toFixed(1)+"\nAdditional analysts at entered rate: "+Math.max(0,need-n)+"\n\nPlanning aid; validate assumptions.")}
function ubo(){let th=+$("#threshold").value,rows=$("#v").value.split("\n").map(x=>x.split(",")),sum=0,flags=[];rows.forEach(r=>{let p=+r[1];sum+=p;if(p>=th)flags.push(r[0].trim()+": "+p+"%")});result("Total entered: "+sum.toFixed(2)+"%\nAt/above selected threshold:\n"+esc(flags.join("\n")||"None")+"\n\nThreshold flagging is not a legal UBO determination.")}
function chain(){result("Indirect ownership: "+((+$("#p1").value/100)*(+$("#p2").value/100)*100).toFixed(2)+"%\n\nMultiply each ownership link in the chain. Control and aggregation rules may require separate analysis.")}
function qa(){let q=[...document.querySelectorAll(".q")],miss=q.filter(x=>!x.checked).length;result("Checklist completion: "+Math.round((q.length-miss)/q.length*100)+"%\nOpen items: "+miss+"\n\nGeneric QA aid; align it to approved procedures.")}
function refresh(){let d=new Date($("#date").value+"T00:00:00");if(isNaN(d))return result("Choose a valid date.");d.setMonth(d.getMonth()+ +$("#months").value);result("Calculated next review date: "+d.toISOString().slice(0,10)+"\n\nUses the cycle you entered; it does not prescribe a regulatory frequency.")}
function aging(){let s=new Date($("#start").value+"T00:00:00"),now=new Date();if(isNaN(s))return result("Choose a valid start date.");let age=Math.floor((now-s)/86400000),sla=+$("#sla").value;result("Calendar age: "+age+" days\nRemaining to entered SLA: "+(sla-age)+" days\n\nCalendar-day calculation.")}
function sample(){let n=Math.ceil(+$("#population").value*+$("#samplepct").value/100);result("Calculated sample: "+n+" items.\n\nThis is percentage-based sizing only, not a statistical assurance methodology.")}
function risk(){let l=+$("#likelihood").value,i=+$("#impact").value,s=l*i;result("Risk score: "+s+" / 25\nLikelihood × impact = "+l+" × "+i+".\n\nInterpretation thresholds should come from your approved methodology.")}
function timeline(){let rows=$("#v").value.split("\n").filter(Boolean).sort((a,b)=>a.localeCompare(b));result(esc(rows.join("\n")))}
function sow(){let m={"Salary":["Employment evidence","Recent payslips / income evidence","Relevant account evidence"],"Business ownership":["Ownership evidence","Business financial/income evidence","Distribution/dividend evidence where relevant"],"Inheritance":["Inheritance/probate evidence","Evidence of receipt / transfer"],"Property sale":["Sale agreement","Ownership evidence","Evidence of sale proceeds"],"Investment":["Investment statements","Evidence of disposal/redemption and proceeds"]};result("<strong>Generic prompts for "+esc($("#source").value)+"</strong>\n• "+m[$("#source").value].join("\n• ")+"\n\nActual evidence depends on risk, facts, policy and jurisdiction.")}
function impact(){result("<strong>Change</strong> "+esc($("#change").value)+"\n<strong>Affected area</strong> "+esc($("#area").value)+"\n<strong>Owner</strong> "+esc($("#owner").value)+"\n<strong>Due</strong> "+esc($("#due").value)+"\n\nNext: assess applicability → map controls/policies → evidence decision → track action.")}
function routeIntent(){let q=$("#intent").value.toLowerCase(),m=tools.find(t=>t.slice(2).join(" ").toLowerCase().split(" ").some(w=>w.length>4&&q.includes(w)));if(m)openTool(m[0]);else $("#intentResult").textContent="Browse the launch tools below — more intelligent routing is coming."}
document.addEventListener("DOMContentLoaded",renderCatalog);
function copyResult(){const e=$("#out .result");if(e&&navigator.clipboard)navigator.clipboard.writeText(e.innerText)}
const _result=result;result=function(x){_result(x);const o=$("#out");if(o&&o.querySelector(".result"))o.insertAdjacentHTML("beforeend",'<div class="actions"><button class="btn alt" onclick="copyResult()">Copy result</button></div>')};

function downloadResult(){
 const e=$("#out .result"); if(!e)return;
 const blob=new Blob([e.innerText],{type:"text/plain;charset=utf-8"});
 const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="intellitools-result.txt";a.click();URL.revokeObjectURL(a.href);
}
function clearWorkspace(){
 document.querySelectorAll("#workspace input").forEach(x=>{if(x.type==="checkbox")x.checked=false;else x.value=""});
 document.querySelectorAll("#workspace textarea").forEach(x=>x.value="");
 const o=$("#out");if(o)o.innerHTML="";
}
const _result2=result;result=function(x){
 _result2(x);const o=$("#out");if(o&&!o.querySelector(".export-actions"))o.insertAdjacentHTML("beforeend",'<div class="actions export-actions"><button class="btn alt" onclick="downloadResult()">Download .txt</button><button class="btn alt" onclick="clearWorkspace()">Clear</button></div>');
};

function jsonFmt(){try{const x=JSON.stringify(JSON.parse($("#v").value),null,2);$("#v").value=x;result(esc(x))}catch(e){result("Invalid JSON: "+esc(e.message))}}
function b64(enc){try{const v=$("#v").value;const out=enc?btoa(unescape(encodeURIComponent(v))):decodeURIComponent(escape(atob(v.trim())));$("#v").value=out;result(esc(out))}catch{result("Unable to process this input.")}}
function timeConvert(){let v=$("#v").value.trim(),d;if(/^\d{10}$/.test(v))d=new Date(+v*1000);else if(/^\d{13}$/.test(v))d=new Date(+v);else d=new Date(v);if(isNaN(d))return result("Enter a valid Unix timestamp or date/time.");result("ISO: "+d.toISOString()+"\nUnix seconds: "+Math.floor(d.getTime()/1000)+"\nUnix milliseconds: "+d.getTime())}
function slugify(){const s=$("#v").value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");result(esc(s||"Nothing to convert."))}
function passwordGen(){let n=Math.min(128,Math.max(8,+$("#len").value||20)),chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*_-",a=new Uint32Array(n);crypto.getRandomValues(a);result(esc([...a].map(x=>chars[x%chars.length]).join(""))+"\n\nGenerated locally with browser cryptographic randomness.")}
function trackingCheck(){try{const u=new URL($("#v").value.trim()),known=["fbclid","gclid","msclkid","mc_cid","mc_eid","igshid"],hits=[...u.searchParams.keys()].filter(k=>k.toLowerCase().startsWith("utm_")||known.includes(k.toLowerCase()));result(hits.length?"Tracking-like parameters found:\n"+esc(hits.join("\n")):"No common tracking parameters detected.")}catch{result("Enter a valid complete URL.")}}
function lookalike(){try{let v=$("#v").value.trim();if(!/^https?:\/\//i.test(v))v="https://"+v;const h=new URL(v).hostname,non=/[^\x00-\x7F]/.test(h),puny=h.includes("xn--");result("Hostname: "+esc(h)+"\nPunycode: "+(puny?"Yes":"No")+"\nNon-ASCII characters: "+(non?"Yes":"No")+"\n\nThis is a structural warning only, not a reputation or malware check.")}catch{result("Enter a valid domain or URL.")}}
function metadataCheck(){const v=$("#v").value,emails=v.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[],phones=v.match(/(?:\+?\d[\d ()-]{7,}\d)/g)||[],urls=v.match(/https?:\/\/\S+/gi)||[];result("Emails found: "+emails.length+"\nPhone-like strings: "+phones.length+"\nURLs: "+urls.length+"\nURLs with query parameters: "+urls.filter(x=>x.includes("?")).length+"\n\nReview before sharing if the text may contain personal or tracking information.")}
