/* IntelliTools V2.1 browser-first utilities */
const v21Tools=[
["agentic-workflow-generator","Productivity","Agentic Workflow Generator","Design a multi-agent workflow with roles, handoffs, guardrails and outputs."],
["link-fingerprint","Links & Web","Link Fingerprint Inspector","Inspect URL structure, trackers and short-link signals without opening the destination."],
["oauth-jwt-decoder","Developer","OAuth & JWT Claim Decoder","Decode JWT claims and review OAuth scopes/state locally."],
["cookie-impact-estimator","Privacy & Safety","Cookie Impact Estimator","Pre-audit cookie and browser-storage descriptions for likely consent impact."],
["sql-mock-builder","Developer","SQL & Mock Data Builder","Generate a CREATE TABLE statement and JSON mock record from a simple schema."],
["env-diff","Developer",".env Diff & Drift Checker","Compare environment keys and secret-value drift without displaying values."],
["table-formatter","Writing & Text","Markdown Table ↔ Spreadsheet Formatter","Turn pasted spreadsheet or CSV rows into a Markdown table."],
["cron-humanizer","Developer","Cron Humanizer & Collision Checker","Explain common five-field cron expressions and flag obvious collisions."],
["prompt-diff","Productivity","Prompt Diff & Regression Inspector","Compare prompt versions and surface instruction additions and removals."],
["keyword-balancer","Writing & Text","Semantic Keyword Density Balancer","Measure keyword repetition across a draft without claiming ranking impact."],
["email-preview","Writing & Text","Email Subject & Inbox Preview Clipper","Preview subject and preheader lengths and likely compact-view clipping."],
["hourly-rate","Money & Calculators","Effective Hourly Rate Calculator","Estimate real hourly value after costs and unpaid work."],
["saas-economics","Money & Calculators","SaaS Unit Economics & Runway","Estimate MRR, simple LTV/CAC and cash runway."],
["expense-splitter","Money & Calculators","Fair Expense & Currency Splitter","Split shared payments and calculate who owes or receives."]
];
tools.push(...v21Tools);
// V2 rendered the catalogue before this script loaded; refresh counts/cards after V2.1 tools are registered.
if(typeof renderCatalog==="function")renderCatalog();
if(typeof renderDiscoveryShelf==="function")renderDiscoveryShelf();
const v21Ids=new Set(v21Tools.map(t=>t[0])),v21OpenTool=openTool;
const E=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const V=id=>document.getElementById(id)?.value||"", L=s=>String(s||"").split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
const F=(id,label,ph="",type="text")=>'<div class="field"><label for="'+id+'">'+label+'</label><input id="'+id+'" type="'+type+'" placeholder="'+E(ph)+'"></div>';
const T=(id,label,ph="",rows=8)=>'<div class="field"><label for="'+id+'">'+label+'</label><textarea id="'+id+'" rows="'+rows+'" placeholder="'+E(ph)+'"></textarea></div>';
const B=id=>'<div class="actions"><button class="btn" type="button" onclick="runV21(\''+id+'\')">Generate result</button></div>';
function O(x){document.getElementById("v21out").innerHTML=x}
function v21Shell(t,b){return '<div class="workspace-head"><div><span class="tag">'+E(t[1])+'</span><span class="tag new-tag">NEW</span><h2>'+E(t[2])+'</h2><p class="desc">'+E(t[3])+'</p></div><button class="btn alt no-print" onclick="closeTool()">Close</button></div>'+b+'<div id="v21out" class="result" aria-live="polite"></div>'}
function runV21(id){let h="";
if(id==="agentic-workflow-generator"){const goal=V("awGoal"),agents=[["Planner","decompose goal and acceptance criteria"],["Researcher","collect and validate inputs"],["Builder","execute the core tasks"],["Reviewer","test evidence, constraints and quality"],["Orchestrator","manage handoffs, retries and final assembly"]],spec={goal,inputs:L(V("awInputs")),tools:L(V("awTools")),guardrails:L(V("awGuards")),agents:agents.map((a,i)=>({order:i+1,role:a[0],responsibility:a[1],handoff:i<4?agents[i+1][0]:"final output"})),failure_policy:"Stop on failed guardrails or missing evidence; return the blocker instead of inventing data."};h='<h3>Agentic workflow</h3><ol>'+agents.map(a=>'<li><strong>'+a[0]+'</strong> — '+a[1]+'</li>').join("")+'</ol><pre>'+E(JSON.stringify(spec,null,2))+'</pre>'}
else if(id==="link-fingerprint"){try{const u=new URL(V("lfUrl")),keys=[...u.searchParams.keys()],track=keys.filter(k=>/^(utm_|gclid|fbclid|mc_|ref|affiliate)/i.test(k)),short=/^(bit\.ly|t\.co|tinyurl\.com|ow\.ly|buff\.ly)$/i.test(u.hostname);h='<p><b>Host:</b> '+E(u.hostname)+'</p><p><b>HTTPS:</b> '+(u.protocol==="https:"?"Yes":"No")+'</p><p><b>Parameters:</b> '+keys.length+'</p><p><b>Tracking-like:</b> '+E(track.join(", ")||"None detected")+'</p><p><b>Short-link signal:</b> '+(short?"Likely":"Not detected")+'</p><p class="note">Local inspection only; redirects are not followed and destination safety is not guaranteed.</p>'}catch{h="Enter a valid absolute URL."}}
else if(id==="oauth-jwt-decoder"){try{const p=V("ojToken").trim().split("."),dec=x=>JSON.parse(decodeURIComponent(escape(atob(x.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(x.length/4)*4,"=")))));if(p.length<2)throw 0;h='<h3>Header</h3><pre>'+E(JSON.stringify(dec(p[0]),null,2))+'</pre><h3>Claims</h3><pre>'+E(JSON.stringify(dec(p[1]),null,2))+'</pre><p><b>Scopes:</b> '+E(V("ojScopes")||"Not supplied")+'</p><p><b>State supplied:</b> '+(V("ojState").trim()?"Yes":"No")+'</p><p class="note">Decode only: signature, issuer, audience and validity are not verified.</p>'}catch{h="Could not decode this JWT."}}
else if(id==="cookie-impact-estimator"){const a=L(V("ciData"));h=a.length?'<table><tr><th>Item</th><th>Pre-audit signal</th></tr>'+a.map(x=>'<tr><td>'+E(x)+'</td><td>'+(/analytics|advert|track|pixel|marketing|third.?party/i.test(x)?"Review consent / likely non-essential":/session|auth|security|csrf/i.test(x)?"Likely functional; verify necessity":"Needs classification")+'</td></tr>').join("")+'</table><p class="note">This is a triage aid, not a legal determination.</p>':"Add one item per line."}
else if(id==="sql-mock-builder"){const fs=L(V("smFields")).map(x=>x.split(":").map(y=>y.trim())),name=(V("smTable")||"example").replace(/\W/g,"_"),map={string:"TEXT",number:"NUMERIC",integer:"INTEGER",boolean:"BOOLEAN",date:"DATE"},mock=Object.fromEntries(fs.map(([n,t])=>[n,t==="number"||t==="integer"?1:t==="boolean"?true:t==="date"?"2026-01-01":"sample"]));h='<pre>'+E('CREATE TABLE '+name+' (\n  id INTEGER PRIMARY KEY,\n  '+fs.map(x=>x[0]+' '+(map[(x[1]||"string").toLowerCase()]||"TEXT")).join(",\n  ")+'\n);\n\n'+JSON.stringify(mock,null,2))+'</pre>'}
else if(id==="env-diff"){const P=s=>Object.fromEntries(L(s).filter(x=>x.includes("=")).map(x=>{const i=x.indexOf("=");return[x.slice(0,i).trim(),x.slice(i+1)]})),a=P(V("edA")),b=P(V("edB")),ks=[...new Set([...Object.keys(a),...Object.keys(b)])].sort();h='<table><tr><th>Key</th><th>Status</th></tr>'+ks.map(k=>'<tr><td>'+E(k)+'</td><td>'+(!Object.hasOwn(a,k)?"Missing from A":!Object.hasOwn(b,k)?"Missing from B":a[k]===b[k]?"Same":"Value differs")+'</td></tr>').join("")+'</table><p class="note">Secret values are intentionally not displayed.</p>'}
else if(id==="table-formatter"){const raw=V("tfInput").trim(),r=raw.split(/\r?\n/).map(x=>x.includes("\t")?x.split("\t"):x.split(",").map(y=>y.trim()));h=!raw?"Paste tabular data first.":'<pre>'+E('| '+r[0].join(" | ")+' |\n| '+r[0].map(()=> "---").join(" | ")+' |\n'+r.slice(1).map(x=>'| '+x.join(" | ")+' |').join("\n"))+'</pre>'}
else if(id==="cron-humanizer"){const X=c=>{const p=c.trim().split(/\s+/);return p.length===5?'minute '+p[0]+', hour '+p[1]+', day '+p[2]+', month '+p[3]+', weekday '+p[4]:"Use five cron fields."},a=V("crA"),b=V("crB");h='<p><b>A:</b> '+E(X(a))+'</p><p><b>B:</b> '+E(X(b))+'</p><p><b>Obvious collision:</b> '+(a.trim()&&a.trim()===b.trim()?"Yes — identical expressions":"Not proven")+'</p><p class="note">Complex cron dialects, timezone and DST behavior are not fully expanded.</p>'}
else if(id==="prompt-diff"){const a=L(V("pdA")),b=L(V("pdB"));h='<h3>Removed</h3><pre>'+E(a.filter(x=>!b.includes(x)).join("\n")||"None")+'</pre><h3>Added</h3><pre>'+E(b.filter(x=>!a.includes(x)).join("\n")||"None")+'</pre><p class="note">Line-level comparison; this does not prove model performance changed.</p>'}
else if(id==="keyword-balancer"){const txt=V("kbText").toLowerCase(),ks=V("kbKeys").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean),wc=(txt.match(/\b[\w-]+\b/g)||[]).length;h='<table><tr><th>Keyword</th><th>Count</th><th>Density</th></tr>'+ks.map(k=>{let n=0,pos=0;while((pos=txt.indexOf(k,pos))>=0){n++;pos+=Math.max(k.length,1)}return'<tr><td>'+E(k)+'</td><td>'+n+'</td><td>'+((n/Math.max(wc,1))*100).toFixed(2)+'%</td></tr>'}).join("")+'</table><p class="note">Descriptive density only; not an SEO ranking score.</p>'}
else if(id==="email-preview"){const s=V("epSubject"),p=V("epPre");h='<h3>'+E(s||"(No subject)")+'</h3><p>'+E(p||"(No preheader)")+'</p><p>Subject: '+s.length+' chars '+(s.length>60?"— may clip":"")+'</p><p>Preheader: '+p.length+' chars '+(p.length>100?"— may clip":"")+'</p>'}
else if(id==="hourly-rate"){const r=+V("hrRevenue")||0,c=+V("hrCosts")||0,b=+V("hrBill")||0,u=+V("hrUnpaid")||0,t=b+u;h='<p><b>Net income:</b> '+(r-c).toFixed(2)+'</p><p><b>Effective hourly rate:</b> '+(t?(r-c)/t:0).toFixed(2)+'</p><p><b>Billable utilization:</b> '+(t?b/t*100:0).toFixed(1)+'%</p>'}
else if(id==="saas-economics"){const n=+V("seCustomers")||0,a=+V("seArpu")||0,ch=(+V("seChurn")||0)/100,cac=+V("seCac")||0,cash=+V("seCash")||0,burn=+V("seBurn")||0,ltv=ch?a/ch:0;h='<p><b>MRR:</b> '+(n*a).toFixed(2)+'</p><p><b>Simple LTV:</b> '+ltv.toFixed(2)+'</p><p><b>LTV:CAC:</b> '+(cac?ltv/cac:0).toFixed(2)+'×</p><p><b>Cash runway:</b> '+(burn?cash/burn:0).toFixed(1)+' months</p><p class="note">Simplified planning estimates; excludes cohorts, gross margin and expansion revenue.</p>'}
else if(id==="expense-splitter"){const ns=L(V("esPeople")),paid=Object.fromEntries(ns.map(n=>[n,0]));let total=0;for(const x of L(V("esExpenses"))){const i=x.lastIndexOf(":"),who=x.slice(0,i).trim(),amt=+x.slice(i+1)||0;if(i>0&&who in paid){paid[who]+=amt;total+=amt}}const rate=+V("esRate")||1,share=ns.length?total/ns.length:0;h='<p><b>Total:</b> '+(total*rate).toFixed(2)+'</p><p><b>Equal share:</b> '+(share*rate).toFixed(2)+'</p><table><tr><th>Person</th><th>Balance</th></tr>'+ns.map(n=>'<tr><td>'+E(n)+'</td><td>'+((paid[n]-share)*rate).toFixed(2)+'</td></tr>').join("")+'</table><p class="note">Positive receives; negative owes. Currency conversion uses your supplied rate.</p>'}
O(h)}
function v21Template(id){switch(id){
case"agentic-workflow-generator":return T("awGoal","Goal","What should the system achieve?",5)+T("awInputs","Inputs / context","One per line",5)+T("awTools","Available tools / systems","One per line",5)+T("awGuards","Guardrails / constraints","One per line",5)+B(id);
case"link-fingerprint":return F("lfUrl","URL","https://example.com/path?utm_source=...")+B(id);
case"oauth-jwt-decoder":return T("ojToken","JWT","Paste encoded JWT",5)+F("ojScopes","OAuth scopes","openid profile email")+F("ojState","OAuth state","optional")+B(id);
case"cookie-impact-estimator":return T("ciData","Cookies / storage items","_ga analytics cookie\nsession_id authentication cookie",10)+B(id);
case"sql-mock-builder":return F("smTable","Table name","customers")+T("smFields","Fields","name:string\nage:integer\nactive:boolean",8)+B(id);
case"env-diff":return '<div class="grid2">'+T("edA","Environment A","API_URL=...\nAPI_KEY=...",10)+T("edB","Environment B","API_URL=...\nAPI_KEY=...",10)+'</div>'+B(id);
case"table-formatter":return T("tfInput","Spreadsheet / CSV rows","Name\tRole\nAlex\tAnalyst",10)+B(id);
case"cron-humanizer":return F("crA","Cron A","0 9 * * 1-5")+F("crB","Cron B","0 9 * * 1-5")+B(id);
case"prompt-diff":return '<div class="grid2">'+T("pdA","Prompt A","",10)+T("pdB","Prompt B","",10)+'</div>'+B(id);
case"keyword-balancer":return F("kbKeys","Keywords","privacy tools, pdf tools")+T("kbText","Draft text","",12)+B(id);
case"email-preview":return F("epSubject","Subject","A useful update for you")+F("epPre","Preheader","A short preview of the message")+B(id);
case"hourly-rate":return F("hrRevenue","Project revenue","5000","number")+F("hrCosts","Direct costs","500","number")+F("hrBill","Billable hours","40","number")+F("hrUnpaid","Unpaid/admin hours","10","number")+B(id);
case"saas-economics":return F("seCustomers","Customers","100","number")+F("seArpu","Monthly ARPU","20","number")+F("seChurn","Monthly churn %","5","number")+F("seCac","CAC","100","number")+F("seCash","Cash balance","50000","number")+F("seBurn","Monthly net burn","5000","number")+B(id);
case"expense-splitter":return T("esPeople","Participants","Alex\nSam\nRiya",6)+T("esExpenses","Payments (Name:Amount)","Alex:120\nSam:60",8)+F("esRate","Conversion rate","1","number")+B(id);
default:return"<p>Tool unavailable.</p>"}}
openTool=function(id){if(!v21Ids.has(id))return v21OpenTool(id);rememberTool(id);const t=v21Tools.find(x=>x[0]===id),w=document.getElementById("workspace");w.innerHTML=v21Shell(t,v21Template(id));w.classList.add("active");w.focus({preventScroll:true});w.scrollIntoView({behavior:"smooth",block:"start"})};
