const {firefox,webkit}=require('playwright');
const fs=require('fs');const path=require('path');const assert=require('assert');
const out=process.env.QA_OUT||path.join(__dirname,'browser-results');fs.mkdirSync(out,{recursive:true});const cases=[['how do I connect an AI agent to Gmail','gmail-for-ai-agents'],['How can an AI agent access Gmail?','gmail-for-ai-agents'],['is gmail.readonly a restricted scope','gmail-api-scopes-and-verification'],['mcp authorization','mcp-authorization'],['how does oauth work for mcp servers','mcp-authorization'],['how to secure an mcp server','mcp-security'],['planner and worker agents','multi-agent-systems']];
const targets={local:'http://127.0.0.1:8765/knowledge/',staging:'https://intellitools-knowledge-v3-release.onrender.com/knowledge/'};const report=[];
const http=require('http'); const server=http.createServer((req,res)=>{let f=path.join(process.env.QA_ROOT||process.cwd(),decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end('Not found')}const ext=path.extname(f);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css'})[ext]||'application/octet-stream');fs.createReadStream(f).pipe(res)});
(async()=>{await new Promise(r=>server.listen(8765,'127.0.0.1',r));for(const [engine,type] of Object.entries({firefox,webkit})){let browser;try{browser=await type.launch({headless:true,timeout:10000,env:process.env});}catch(e){report.push({engine,status:'BLOCKED',phase:'launch',error:String(e)});continue;}
for(const [target,url] of Object.entries(targets).filter(([name])=>!process.env.QA_TARGET||name===process.env.QA_TARGET))for(const width of [1280,375]){const entry={engine,version:browser.version(),target,width,checks:[],errors:[],network:[],screenshots:[]};report.push(entry);console.log('START',engine,target,width);const ctx=await browser.newContext({viewport:{width,height:900},ignoreHTTPSErrors:process.env.QA_IGNORE_TLS==='1'});const page=await ctx.newPage();page.setDefaultTimeout(12000);let injected=false;
page.on('pageerror',e=>entry.errors.push({kind:'pageerror',message:e.message,injected}));page.on('console',m=>{if(m.type()==='error')entry.errors.push({kind:'console',message:m.text(),injected});});page.on('requestfailed',r=>entry.network.push({kind:'failed',url:r.url(),failure:r.failure(),injected}));page.on('response',r=>{if(r.status()>=400)entry.network.push({kind:'http',url:r.url(),status:r.status(),injected});});
const check=async(name,fn)=>{try{await fn();entry.checks.push({name,status:'PASS'});console.log('PASS',name);}catch(e){entry.checks.push({name,status:'FAIL',error:String(e)});console.log('FAIL',name,String(e));}};
const overflow=async()=>{const v=await page.evaluate(()=>({viewport:innerWidth,doc:document.documentElement.scrollWidth,body:document.body.scrollWidth}));assert(v.doc<=v.viewport+1 && v.body<=v.viewport+1,JSON.stringify(v));};
const shot=async(label)=>{const file=`${target}-${engine}-${width}-${label}.png`;try{await page.screenshot({path:path.join(out,file),timeout:12000});entry.screenshots.push(file);}catch(e){entry.checks.push({name:'screenshot '+label,status:'BLOCKED',error:String(e)});}};
try{const response=await page.goto(url,{waitUntil:'load',timeout:25000});assert(response&&response.ok(),'Homepage HTTP '+response?.status());}catch(e){entry.status='BLOCKED';entry.blocker=String(e);await ctx.close();continue;}
await check('homepage',async()=>{assert(await page.locator('h1').isVisible());assert(await page.locator('#kn-q').isVisible());await overflow();});await shot('home');
for(const [q,id] of cases)await check('query '+q,async()=>{await page.locator('#kn-q').fill(q);await page.locator('#kn-q').press('Enter');const a=page.getByRole('link',{name:'Read the guide',exact:true});await a.waitFor({state:'visible'});assert.equal(await a.getAttribute('href'),id+'.html');await overflow();await a.click();await page.waitForURL('**/'+id+'.html');assert(await page.locator('h1').isVisible());await overflow();await page.goBack({waitUntil:'load'});await page.getByRole('link',{name:'Read the guide',exact:true}).waitFor();assert.equal(await page.locator('#kn-q').inputValue(),q);});
await shot('search');
await check('keyboard navigation',async()=>{await page.goto(url);await page.locator('body').click({position:{x:2,y:2}});await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur()});let found=false;for(let i=0;i<30;i++){await page.keyboard.press('Tab');if(await page.locator('#kn-q').evaluate(e=>e===document.activeElement)){found=true;break;}}assert(found,'Tab did not reach input');await page.keyboard.type('mcp authorization');await page.keyboard.press('Enter');await page.getByRole('link',{name:'Read the guide',exact:true}).waitFor();found=false;for(let i=0;i<30;i++){await page.keyboard.press('Tab');if(await page.evaluate(()=>document.activeElement?.textContent==='Read the guide')){found=true;break;}}assert(found,'Tab did not reach guide');await page.keyboard.press('Enter');await page.waitForURL('**/mcp-authorization.html');await overflow();await page.goto(url);});
await check('no-match messages',async()=>{await page.locator('#kn-q').fill('zzzxqv987654321');await page.locator('#kn-q').press('Enter');await page.getByText('No confident match found.',{exact:true}).waitFor();await page.getByText('No Knowledge guide matched this query.',{exact:true}).waitFor();await overflow();});await shot('no-match');
await check('empty and whitespace searches',async()=>{for(const q of ['', '   ']){await page.locator('#kn-q').fill(q);await page.locator('#kn-q').press('Enter');await page.waitForFunction(()=>document.querySelector('#kn-search-results').children.length===0);assert(!new URL(page.url()).searchParams.has('q'));}});
for(const mode of ['index-abort','lexicon-500'])await check('load failure '+mode,async()=>{injected=true;const pattern=mode==='index-abort'?'**/search-index.json':'**/search-lexicon.json';await page.route(pattern,r=>mode==='index-abort'?r.abort('failed'):r.fulfill({status:500,contentType:'application/json',body:'{}'}));await page.goto(url,{waitUntil:'load'});const msg='Search could not be loaded. Refresh the page and try again.';await page.locator('#kn-search-results').getByText(msg,{exact:true}).waitFor();assert.equal(await page.locator('#kn-search-status').textContent(),msg);await page.locator('#kn-q').fill('mcp authorization');await page.locator('#kn-q').press('Enter');await page.locator('#kn-search-results').getByText(msg,{exact:true}).waitFor();await overflow();await shot(mode);await page.unroute(pattern);injected=false;});
entry.checks.push({name:'unexpected JavaScript errors',status:entry.errors.filter(e=>e.kind==='pageerror'||!e.injected).length?'FAIL':'PASS'});entry.checks.push({name:'unexpected network failures',status:entry.network.filter(e=>!e.injected).length?'FAIL':'PASS'});entry.status=entry.checks.some(c=>c.status==='FAIL')?'FAIL':'PASS';await ctx.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));}
await browser.close();}fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));server.close();process.exitCode=report.some(x=>x.status!=='PASS')?1:0;console.log(JSON.stringify(report.map(({engine,target,width,status,checks,blocker,error})=>({engine,target,width,status,failed:checks?.filter(c=>c.status!=='PASS'),blocker,error})),null,2));})();
