import { E } from './entity-model.mjs';
const P = 'Agent Protocols, Frameworks & Runtimes', R = 'Agent & RAG Patterns';
export const entities = [
E('a2a-protocol', 'A2A (Agent2Agent) Protocol', 'protocol', P, {
  summary: 'A2A is an open protocol for communication between independent AI agents — discovering each other\'s capabilities, exchanging tasks and returning results — complementing MCP, which connects agents to tools.',
  short: 'A2A lets **agents built by different teams or vendors collaborate**: they advertise capabilities (an "agent card"), delegate tasks, stream updates and return artifacts. MCP connects an agent to tools; A2A connects agents to agents. Details are version-dependent — verify against the current spec.',
  plain: `MCP is how an agent plugs into tools and data. A2A is how one agent talks to *another agent* — possibly built by a different company on a different framework. They publish what they can do, hand tasks to each other and send back results, so agents can cooperate without sharing internals.`,
  technical: `A2A was announced by Google on 9 April 2025 and contributed to the Linux Foundation, which launched the Agent2Agent project on 23 June 2025; the project released its first stable specification, version 1.0.0, in 2026 (time-sensitive). Core concepts as commonly described: an Agent Card (a JSON description of an agent\'s identity, endpoint, skills and auth requirements, served at a well-known URL — /.well-known/agent-card.json in the current specification); tasks with lifecycle states; messages made of typed parts; artifacts as outputs; and streaming/push updates for long-running work. The current specification separates an abstract data model and operations from protocol bindings, and defines JSON-RPC 2.0, gRPC and HTTP/REST bindings, with Server-Sent Events for streaming. The specification is evolving, so field names, paths and transports must be checked in the current spec.`,
  aliases: ['A2A', 'Agent2Agent', 'agent to agent protocol', 'agent-to-agent communication', 'agent card', 'A2A protocol', 'Google A2A', 'interoperable agents'],
  intents: ['make agents from different frameworks interoperate', 'understand how A2A relates to MCP'],
  questions: ['What is the A2A protocol?', 'What is an agent card?', 'How is A2A different from MCP?', 'Do I need A2A for a multi-agent system?', 'Who maintains A2A?'],
  pre: ['ai-agents', 'multi-agent-systems', 'mcp'], rel: ['a2a-vs-mcp', 'agent-protocol-landscape', 'agent-frameworks-compared', 'mcp-security', 'agentic-workflows', 'ai-privacy-and-security'],
  vs: [['mcp', 'MCP connects a model/host to tools, resources and prompts; A2A connects autonomous agents to each other.'], ['function-calling', 'Function calling is a model-API feature for requesting a function run; A2A is a network protocol between agent services.']],
  tech: ['A2A SDKs (Python, JavaScript and others)', 'JSON-RPC / HTTP', 'Server-Sent Events', 'OAuth/OIDC for authentication'],
  patterns: ['Publish an agent card describing skills and auth for remote agents.', 'Delegate a long-running task and subscribe to status updates.', 'Wrap an existing framework agent behind an A2A server.', 'Gateway pattern: one orchestrator discovers and routes to specialist agents.'],
  fails: ['Treating a remote agent\'s output as trusted input (see [[prompt-injection]]).', 'Weak authentication between agents.', 'Spec/version mismatch between client and server.', 'Over-engineering a single-team system that a function call would solve.', 'Unbounded delegation loops.'],
  fix: [['Client cannot find the agent', 'Check the well-known card path and version in the current spec.'], ['Task hangs', 'Check task state handling, timeouts and streaming support on both sides.'], ['Unexpected actions from a remote agent', 'Treat results as untrusted; restrict permissions and require confirmation.']],
  guide: ['Check whether you need cross-team/vendor interoperability at all.', 'Read the current spec and pick SDKs.', 'Define agent skills and publish a card.', 'Implement authentication and authorisation.', 'Add timeouts, logging and result validation.'],
  when: 'Consider when independently owned agents must interoperate; for in-process orchestration use your framework\'s native multi-agent features.',
  sources: [['A2A protocol specification and documentation', 'a2a-protocol.org (verify current canonical location)'], ['A2A project repository', 'github.com/a2aproject/A2A (verify)'], ['Google announcement of A2A (April 2025)', null]],
  fresh: 'volatile', tsc: ['Governance and hosting of the project (announced by Google; Linux Foundation involvement to be verified).', 'Agent-card path, field names and transport bindings by version.', 'SDK availability and maturity.', 'Industry adoption claims.'],
  keywords: ['agent interoperability', 'agent card', 'delegation']
}),

E('agent-protocol-landscape', 'Agent Protocol Landscape (MCP, A2A and Others)', 'concept', P, {
  summary: 'Several protocols are emerging for agent interoperability. They operate at different layers: tools and context, agent-to-agent messaging, discovery and payments/identity.',
  short: 'Think in **layers**: tool/context access (MCP), agent-to-agent collaboration (A2A), agent discovery/identity, and application-level UI/streaming conventions. The landscape moves fast — treat any list of protocols as a snapshot to re-verify.',
  plain: `Agents need ways to connect to tools, to each other and to users. Different protocols are being proposed for different jobs, much like the web has separate standards for transport, identity and page content. Knowing which layer each solves keeps you from comparing apples to oranges.`,
  technical: `Layer view: (1) model ↔ tools/data — function calling APIs and [[mcp]]; (2) agent ↔ agent — [[a2a-protocol]] and framework-specific messaging; (3) identity and authorisation — OAuth/OIDC patterns applied to agents; (4) agent ↔ user interface — streaming and UI-event conventions that vary by vendor; (5) commerce/payment and discovery proposals that are early and unsettled. Standards bodies, governance and adoption change rapidly; this entry deliberately names no "winner".`,
  aliases: ['agent protocols', 'agent interoperability standards', 'MCP vs A2A vs ACP', 'agent communication protocols', 'agent standards', 'AI agent protocol stack'],
  intents: ['map the agent protocol ecosystem', 'decide which protocol layer you need'],
  questions: ['What agent protocols exist?', 'How do MCP and A2A fit together?', 'Which agent protocol should I use?', 'Are there standards for agent identity?'],
  pre: ['ai-agents', 'mcp'], rel: ['a2a-protocol', 'a2a-vs-mcp', 'function-calling-vs-mcp', 'agent-frameworks-compared', 'mcp-security', 'api-authentication'],
  vs: [['function-calling-vs-mcp', 'Layer 1 comparison.'], ['a2a-vs-mcp', 'Layer 1 vs layer 2.']],
  tech: ['MCP', 'A2A', 'OAuth 2.x / OIDC', 'OpenAPI'],
  patterns: ['Start at layer 1; add layer 2 only when independent agents must interoperate.', 'Isolate protocol adapters so you can swap them.', 'Pin protocol versions and test conformance.'],
  fails: ['Betting on a protocol because of hype rather than ecosystem fit.', 'Building bespoke wire formats where a standard exists.', 'Assuming protocol support implies security.'],
  fix: [['Unsure what you need', 'Write down who owns each agent/tool and whether they are in the same trust domain.']],
  guide: ['List your agents/tools and owners.', 'Identify trust boundaries.', 'Pick the lowest layer that solves the problem.', 'Check current specs and SDK support.', 'Re-review quarterly.'],
  when: 'Use as a map before choosing integration standards.',
  sources: [['MCP specification', 'modelcontextprotocol.io'], ['A2A specification', 'a2a-protocol.org (verify)'], ['Current comparisons by standards bodies or vendors (identify at time of writing)', null]],
  fresh: 'volatile', tsc: ['Which protocols exist, their governance, versions and adoption.', 'Any statement about protocol convergence or merger.'],
  keywords: ['standards', 'interoperability', 'layers']
}),

E('a2a-vs-mcp', 'A2A vs MCP', 'concept', P, {
  page_kind: 'comparison',
  summary: 'MCP connects an AI application to tools, resources and prompts; A2A connects independent agents to one another. They are complementary layers, not rivals.',
  short: '**MCP**: agent ↔ tools/data. **A2A**: agent ↔ agent. Use MCP when an agent needs capabilities; use A2A when separate agents must delegate tasks to each other. Many systems use both.',
  plain: `A useful picture: MCP is how an agent picks up tools; A2A is how agents talk to colleagues. A research agent might use MCP to read files and search the web, and A2A to ask a specialist agent from another company to analyse the data.`,
  technical: `| | MCP | A2A |\n|---|---|---|\n| Connects | Host/client to server exposing tools, resources, prompts | Agent (client) to remote agent (server) |\n| Unit of work | Tool call / resource read | Task with lifecycle, messages, artifacts |\n| Remote party is | A capability provider | An autonomous agent with its own reasoning |\n| Discovery | Capability listing after connection | Agent card describing skills |\n| Typical trust concern | Tool poisoning, over-privileged tools ([[mcp-security]]) | Untrusted agent output, delegation chains |\n\nSpecifications evolve; confirm details in current documents.`,
  aliases: ['MCP vs A2A', 'A2A versus MCP', 'Agent2Agent vs Model Context Protocol', 'do I need A2A and MCP', 'MCP or A2A', 'difference between MCP and A2A'],
  intents: ['choose between MCP and A2A', 'combine both in an architecture'],
  questions: ['What is the difference between A2A and MCP?', 'Should I use MCP or A2A?', 'Can MCP and A2A be used together?', 'Does A2A replace MCP?'],
  pre: ['mcp', 'a2a-protocol'], rel: ['agent-protocol-landscape', 'multi-agent-systems', 'mcp-vs-api'],
  vs: [['mcp', 'Tools and context.'], ['a2a-protocol', 'Agent collaboration.']],
  tech: ['MCP SDKs', 'A2A SDKs'],
  patterns: ['Each agent uses MCP for its tools and A2A to delegate to peers.', 'Orchestrator calls specialist agents via A2A; specialists call tools via MCP.'],
  fails: ['Using A2A for what is really a tool call.', 'Using MCP tools to emulate autonomous agents without lifecycle handling.'],
  fix: [['Unsure which applies', 'If the remote side only executes a function, it is a tool (MCP); if it reasons and may take many steps, it is an agent (A2A).']],
  guide: ['Classify each remote capability as tool or agent.', 'Implement MCP for tools.', 'Add A2A where agents must interoperate.', 'Secure both ([[mcp-security]]).'],
  when: 'Use MCP by default for capabilities; add A2A for cross-agent delegation.',
  sources: [['MCP specification', 'modelcontextprotocol.io'], ['A2A specification', 'a2a-protocol.org (verify)']],
  fresh: 'volatile', tsc: ['Current versions and any overlap or convergence between the specifications.'],
  keywords: ['comparison', 'protocols']
}),

E('mcp-security', 'MCP Security Risks and Mitigations', 'technique', P, {
  summary: 'MCP servers can read data and take actions for an AI application, so they carry risks: malicious or compromised servers, tool-description poisoning, over-broad permissions and prompt injection through tool results.',
  short: 'Treat every MCP server as **code with access to your data**. Review before installing, grant least privilege, require human approval for sensitive tools, isolate credentials, and treat tool descriptions and results as untrusted input.',
  plain: `An MCP server is a plug-in that can touch your files, accounts and APIs. A bad or hijacked one — or good one that returns booby-trapped text — can trick an assistant into leaking data or doing something harmful. The defence is the same as for any software supply chain, plus care about what the model is allowed to do on its own.`,
  technical: `Risk classes widely discussed for MCP and similar tool ecosystems: untrusted or malicious servers (supply-chain); tool-description injection ("tool poisoning") where metadata contains hidden instructions; indirect prompt injection via tool results ([[prompt-injection]]); excessive permissions and token scope; confused-deputy problems when a server uses its own credentials on a user\'s behalf; credential exposure in configs; rug-pull updates that change behaviour after approval; and cross-server data leakage when several servers share one context. The MCP specification and its security guidance, plus OWASP LLM guidance, describe mitigations; details evolve.`,
  aliases: ['MCP risks', 'tool poisoning', 'MCP prompt injection', 'secure MCP servers', 'MCP authorization', 'MCP best practices security', 'malicious MCP server', 'MCP supply chain', 'confused deputy MCP'],
  intents: ['assess whether an MCP server is safe', 'harden an MCP deployment'],
  questions: ['Is MCP secure?', 'What is tool poisoning in MCP?', 'How do I secure an MCP server?', 'Is it safe to install a community MCP server?', 'How should MCP authentication work?'],
  pre: ['mcp', 'mcp-servers-and-clients', 'prompt-injection'], rel: ['ai-privacy-and-security', 'owasp-llm-top-10', 'agent-tools', 'api-authentication', 'ai-guardrails', 'a2a-protocol'],
  vs: [['prompt-injection', 'Prompt injection is the general attack class; MCP security is its application to a tool ecosystem and supply chain.']],
  tech: ['MCP specification security guidance', 'OAuth 2.x', 'sandboxing (containers, microVMs)', 'secret managers', 'allow-lists'],
  patterns: ['Vendor review and pinning of server versions/hashes.', 'Per-server least-privilege credentials, short-lived tokens.', 'Human confirmation for writes, deletes, payments and external sends.', 'Run local servers in a sandbox with restricted file/network access.', 'Log tool calls and review anomalies.'],
  fails: ['Auto-approving all tool calls.', 'One server with a broad personal access token.', 'Secrets in shared config files.', 'Trusting tool descriptions as safe.', 'Ignoring updates that change tool behaviour.'],
  fix: [['Unexpected outbound requests', 'Block egress by default; allow-list destinations; inspect server code.'], ['Model follows odd instructions after a tool call', 'Treat the result as untrusted; strip/flag instructions; require confirmation for actions.']],
  guide: ['Inventory connected servers and their permissions.', 'Remove unused ones.', 'Scope credentials narrowly.', 'Sandbox local servers.', 'Require approvals for sensitive tools.', 'Monitor and rotate secrets.'],
  when: 'Apply to every MCP deployment, especially with third-party servers.',
  sources: [['MCP specification, security and authorization guidance', 'modelcontextprotocol.io (locate current security pages)'], ['OWASP Top 10 for LLM Applications', 'genai.owasp.org']],
  fresh: 'volatile', tsc: ['Current MCP authorization requirements and security best-practice guidance.', 'Named attack techniques and their prevalence.'],
  keywords: ['tool poisoning', 'least privilege', 'supply chain']
}),

E('langchain', 'LangChain', 'framework', P, {
  overlay: true,
  summary: 'LangChain is an open-source framework (Python and JavaScript/TypeScript) with building blocks — model wrappers, prompts, tools, retrievers, chains — for LLM applications.',
  short: 'LangChain offers **integrations and abstractions** for models, tools, retrieval and agent loops. It speeds prototyping and standardises integrations; abstractions and APIs have changed substantially across versions, so pin versions and prefer reading current docs.',
  plain: `LangChain is a popular toolkit that bundles ready-made pieces for AI apps: connectors to many models and databases, prompt templates, tools and agent helpers. It saves writing glue code, at the cost of learning its abstractions.`,
  technical: `LangChain provides model/provider interfaces, prompt and output-parser utilities, tool interfaces, retrievers and vector-store integrations, and agent constructors, with a composable runnable interface. Its stateful orchestration library is [[langgraph]]. The project has restructured packages and recommended APIs several times (e.g., moving from legacy chain classes to newer agent and runnable abstractions), so tutorials may be stale. Observability and evaluation are offered via the vendor\'s separate commercial platform (verify).`,
  aliases: ['langchain python', 'langchain js', 'LCEL', 'LangChain expression language', 'langchain agents', 'langchain tutorial', 'langchain vs llamaindex', 'what is langchain'],
  intents: ['decide whether to use LangChain', 'debug version-related LangChain issues'],
  questions: ['What is LangChain?', 'Do I need LangChain to build an LLM app?', 'Why does my LangChain code break after upgrading?', 'LangChain vs calling the API directly?'],
  pre: ['function-calling', 'rag'], rel: ['langgraph', 'llamaindex', 'agent-frameworks-compared', 'what-is-an-ai-framework', 'framework-vs-direct-api', 'choosing-an-agent-framework', 'ai-sdks'],
  vs: [['langgraph', 'LangGraph focuses on stateful, controllable agent workflows as graphs; LangChain provides broader integrations and components.'], ['llamaindex', 'LlamaIndex centres on data ingestion, indexing and retrieval; LangChain is broader orchestration.'], ['framework-vs-direct-api', 'Direct API calls avoid abstraction at the cost of writing glue.']],
  tech: ['LangChain (Python / JS)', 'LangGraph', 'LangSmith', 'vector-store integrations'],
  patterns: ['Use provider integrations for quick comparisons across models.', 'Keep business logic outside framework classes to ease migration.', 'Pin package versions and read the current migration notes.', 'Use tracing to debug chains and agents.'],
  fails: ['Following outdated tutorials using deprecated APIs.', 'Deep abstraction stacks hiding prompts and making debugging hard.', 'Dependency bloat.', 'Assuming every integration is equally maintained.'],
  fix: [['ImportError after upgrade', 'Check which package now provides the class (core/community/provider packages) in current docs.'], ['Cannot see the actual prompt sent', 'Enable tracing/debug logging and inspect model inputs.']],
  guide: ['Prototype with direct API calls first.', 'Adopt LangChain where its integrations save real time.', 'Pin versions.', 'Add tracing and tests.'],
  when: 'Useful for rapid prototyping and breadth of integrations; weigh against direct SDK use for simple apps.',
  sources: [['LangChain documentation', 'docs.langchain.com (verify current URL)'], ['LangChain repository', 'github.com/langchain-ai/langchain']],
  fresh: 'volatile', tsc: ['Current package structure, recommended APIs and version numbers.', 'Company and product relationships (LangSmith, LangGraph platform).', 'Licensing and pricing of commercial offerings.'],
  keywords: ['framework', 'chains', 'integrations']
}),

E('langgraph', 'LangGraph', 'framework', P, {
  summary: 'LangGraph is a library for building stateful, multi-step agent workflows as graphs of nodes and edges, with persistence, human-in-the-loop checkpoints and streaming.',
  short: 'LangGraph models an agent as a **graph with shared state**: nodes do work, edges (including conditional ones) decide what happens next, and checkpoints enable pause/resume and human approval. It gives control over loops that free-running agents lack.',
  plain: `LangGraph lets you draw your agent\'s process as a flowchart in code: steps, decisions and loops, with a shared notebook of state. Because you define the flow, it is easier to add approvals, retries and reliable resumption than in a free-form agent.`,
  technical: `Core concepts commonly described: state schema, nodes (functions/agents), edges and conditional routing, reducers for state updates, persistence via checkpointers, interrupts for human-in-the-loop, and streaming. It is developed by the LangChain team but can be used without LangChain components. APIs and product tiers evolve; check current docs.`,
  aliases: ['langgraph agents', 'stateful agents graph', 'agent graph framework', 'langgraph checkpoint', 'langgraph human in the loop', 'langgraph vs langchain'],
  intents: ['build controllable multi-step agents', 'add approvals and persistence to an agent'],
  questions: ['What is LangGraph?', 'LangGraph vs LangChain: what is the difference?', 'How do I add human approval in a LangGraph agent?', 'How does LangGraph persistence work?'],
  pre: ['ai-agents', 'agentic-workflows'], rel: ['langchain', 'agent-frameworks-compared', 'multi-agent-systems', 'agent-memory', 'ai-evaluation'],
  vs: [['langchain', 'Broader component library; LangGraph focuses on orchestration.'], ['crewai', 'CrewAI is role-based and higher level; LangGraph is lower-level graph control.']],
  tech: ['LangGraph (Python/JS)', 'checkpointer backends', 'LangSmith tracing'],
  patterns: ['Router node plus specialist nodes.', 'Plan-execute-verify loops with retry limits.', 'Interrupt before sensitive tool calls for approval.', 'Persist state per thread for resumable conversations.'],
  fails: ['Unbounded loops without recursion/step limits.', 'State schema growth bloating context.', 'Tangled graphs hard to test.', 'Coupling business logic to graph internals.'],
  fix: [['Graph loops forever', 'Set recursion limits and explicit termination conditions.'], ['State too large', 'Store references to large data; summarise.']],
  guide: ['Sketch the workflow on paper.', 'Define the state schema.', 'Implement nodes as testable functions.', 'Add checkpointing and approvals.', 'Evaluate end-to-end ([[ai-evaluation]]).'],
  when: 'Choose when you need explicit control, persistence and human-in-the-loop in agent flows.',
  sources: [['LangGraph documentation', 'langchain-ai.github.io/langgraph (verify current URL)'], ['LangGraph repository', 'github.com/langchain-ai/langgraph']],
  fresh: 'volatile', tsc: ['API surface, hosted-platform offerings and versions.', 'Relationship to LangChain packages.'],
  keywords: ['graph', 'state machine', 'checkpoints']
}),

E('llamaindex', 'LlamaIndex', 'framework', P, {
  overlay: true,
  summary: 'LlamaIndex is an open-source framework centred on connecting LLMs to your data: loaders, indexing, retrieval, query engines and agents.',
  short: 'LlamaIndex specialises in **data ingestion, indexing and retrieval pipelines** (RAG) with many connectors and index types; it also provides agent and workflow tooling. Check current docs, as APIs evolve.',
  plain: `If LangChain is a general toolbox, LlamaIndex is the specialist for "chat with your data": it reads your documents, splits and indexes them, retrieves the right parts and feeds them to a model.`,
  technical: `Components: data connectors/readers, node parsers (chunking), index structures (vector, keyword, tree, graph), retrievers, rerankers, response synthesisers and query engines; plus agent and workflow abstractions and a commercial document-parsing/cloud offering (verify). Formerly named GPT Index. Interfaces change between versions.`,
  aliases: ['llama index', 'LlamaIndex RAG', 'GPT Index', 'llamaindex query engine', 'llamaindex vs langchain', 'llamaparse'],
  intents: ['build RAG over documents quickly', 'choose between LlamaIndex and LangChain'],
  questions: ['What is LlamaIndex?', 'LlamaIndex vs LangChain for RAG?', 'How do I build a RAG pipeline with LlamaIndex?', 'Do I need LlamaIndex for RAG?'],
  pre: ['rag', 'embeddings', 'chunking'], rel: ['langchain', 'vector-databases', 'hybrid-search-and-reranking', 'agent-frameworks-compared', 'rag-with-python', 'framework-vs-direct-api'],
  vs: [['langchain', 'LangChain is broader orchestration; LlamaIndex is deeper on data and retrieval.'], ['framework-vs-direct-api', 'You can build RAG with a vector store client and an LLM SDK alone.']],
  tech: ['LlamaIndex (Python/TS)', 'vector store integrations', 'LlamaParse (commercial parsing service)'],
  patterns: ['Ingest → chunk → embed → index → query engine.', 'Metadata filters and rerankers for precision.', 'Evaluate retrieval separately from generation.', 'Pin versions.'],
  fails: ['Default chunking not suited to your documents.', 'Opaque pipelines hiding what was retrieved.', 'Version drift in examples.', 'Sending private data to cloud parsing without review.'],
  fix: [['Wrong passages retrieved', 'Inspect retrieved nodes; tune chunking, add metadata filters, rerank.'], ['Examples fail', 'Match the example\'s version or use the current docs.']],
  guide: ['Start with a small document set.', 'Inspect nodes and retrieval results.', 'Evaluate on question–answer pairs.', 'Add reranking/hybrid search if needed.'],
  when: 'Good fit for document-heavy RAG prototypes and production pipelines when its abstractions suit you.',
  sources: [['LlamaIndex documentation', 'docs.llamaindex.ai (verify current URL)'], ['LlamaIndex repository', 'github.com/run-llama/llama_index']],
  fresh: 'volatile', tsc: ['APIs, packages and versions.', 'Commercial offerings and pricing.'],
  keywords: ['RAG framework', 'data framework', 'retrieval']
}),

E('dspy', 'DSPy', 'framework', P, {
  summary: 'DSPy is a framework for programming — rather than hand-prompting — language-model pipelines: you declare modules and metrics, and optimisers tune prompts or weights automatically.',
  short: 'In DSPy you write **signatures and modules** and a **metric**, then an optimiser searches prompts/few-shot examples (or fine-tunes) to maximise it. It rewards having an evaluation set and reduces manual prompt fiddling.',
  plain: `Instead of endlessly rewording prompts by hand, DSPy lets you describe what each step should do and how to score success, then automatically finds better prompts or examples. It works best when you have test cases.`,
  technical: `Khattab et al. (2023) introduce DSPy: LM calls are expressed as declarative modules with typed signatures; teleprompters/optimisers (e.g., bootstrapping few-shot demonstrations, instruction proposal, search) compile programs against a metric and training/validation examples. Optimisation cost, reproducibility across model versions and the available optimisers change between releases.`,
  aliases: ['DSPy framework', 'declarative self-improving python', 'prompt optimization framework', 'dspy optimizer', 'dspy signatures', 'MIPRO', 'automatic prompt optimization'],
  intents: ['automate prompt optimisation', 'build modular LM pipelines with metrics'],
  questions: ['What is DSPy?', 'How does automatic prompt optimization work?', 'DSPy vs LangChain?', 'Do I need a dataset for DSPy?'],
  pre: ['prompt-engineering', 'ai-evaluation'], rel: ['agent-frameworks-compared', 'langchain', 'structured-outputs', 'framework-vs-direct-api'],
  vs: [['langchain', 'LangChain provides components and integrations; DSPy provides a program-and-optimise methodology.']],
  tech: ['DSPy (Python)', 'optimisers (teleprompters)', 'evaluation metrics'],
  patterns: ['Define a metric, collect 20–200 examples, compile, evaluate on held-out data.', 'Re-compile when changing models.', 'Keep optimised prompts under version control.'],
  fails: ['No reliable metric → optimiser overfits to a bad objective.', 'Overfitting to a tiny training set.', 'Optimisation cost surprises.', 'Prompts that do not transfer when the model changes.'],
  fix: [['Optimised program worse on new data', 'Use a held-out set; increase data diversity; simplify the program.']],
  guide: ['Write the task as a signature.', 'Build a small labelled set and metric.', 'Run baseline, then an optimiser.', 'Validate on held-out data.', 'Version the compiled program.'],
  when: 'Good when you have an evaluation set and want systematic prompt/pipeline improvement.',
  sources: [['Khattab et al., DSPy: Compiling Declarative Language Model Calls into Self-Improving Pipelines (2023)', 'arXiv:2310.03714'], ['DSPy documentation', 'dspy.ai (verify)']],
  fresh: 'volatile', tsc: ['Current API, optimisers and versions.'],
  keywords: ['optimizer', 'prompt compilation', 'metrics']
}),

E('autogen', 'AutoGen (Microsoft)', 'framework', P, {
  summary: 'AutoGen is an open-source Microsoft Research framework for multi-agent LLM applications where agents converse and collaborate. Its repository now states it is in maintenance mode, with Microsoft Agent Framework as the recommended successor for new projects.',
  short: 'AutoGen popularised **conversation-based multi-agent patterns** (assistant, user-proxy, group chat). Its repository states it is **in maintenance mode** (no new features, community managed) and recommends **Microsoft Agent Framework** for new projects, with a migration guide for existing users. Status as of 2026-10-09; re-check before adopting.',
  plain: `AutoGen lets several AI agents "talk" to each other and to humans to solve a task — one writes code, another reviews, a proxy runs it. It influenced many later frameworks. Because it has been redesigned and related Microsoft projects have changed, check what is current before starting.`,
  technical: `The AutoGen paper (Wu et al., 2023) describes conversable agents and conversation programming. Subsequent major versions introduced a layered, event-driven redesign and tooling such as a visual studio; Microsoft also maintains related agent SDKs (see [[semantic-kernel]]). As of 2026-10-09 the AutoGen repository states that AutoGen is in maintenance mode and that Microsoft Agent Framework (Python and .NET; repository github.com/microsoft/agent-framework) is its successor; the Semantic Kernel repository names the same successor. Existing AutoGen code keeps working but will not receive new features. Community forks with related names (for example AG2) are separate projects.`,
  aliases: ['AutoGen', 'autogen studio', 'microsoft autogen', 'autogen agents', 'AG2', 'conversable agent', 'group chat agents', 'Microsoft Agent Framework'],
  intents: ['evaluate AutoGen for multi-agent systems', 'work out which Microsoft agent framework is current'],
  questions: ['What is AutoGen?', 'AutoGen vs CrewAI vs LangGraph?', 'Is AutoGen still maintained?', 'What is the Microsoft Agent Framework?'],
  pre: ['multi-agent-systems', 'ai-agents'], rel: ['semantic-kernel', 'agent-frameworks-compared', 'crewai', 'langgraph', 'code-execution-sandboxing'],
  vs: [['langgraph', 'LangGraph is graph-state-machine oriented; AutoGen centres on agent conversations/events.'], ['crewai', 'CrewAI uses role/task crews; AutoGen uses conversational agent teams.']],
  tech: ['AutoGen (Python / .NET)', 'AutoGen Studio', 'Docker for code execution'],
  patterns: ['Assistant + code-executor agents with sandboxed execution.', 'Group chat with a manager selecting speakers.', 'Human proxy for approvals.'],
  fails: ['Free-form agent chatter consuming tokens.', 'Executing generated code without a sandbox.', 'Following outdated tutorials for a different major version.', 'Unclear project lineage causing dependency confusion (forks/renames).'],
  fix: [['Examples do not run', 'Match the library major version to the tutorial; check package names.'], ['Agents loop', 'Set max turns and termination conditions.']],
  guide: ['Check current repo status and docs.', 'Decide whether conversational orchestration suits you.', 'Sandbox code execution.', 'Cap turns and tokens.', 'Evaluate on tasks ([[ai-evaluation]]).'],
  when: 'For new projects, evaluate Microsoft Agent Framework (the stated successor) rather than starting on AutoGen; keep AutoGen for maintaining existing systems or reading earlier research code.',
  sources: [['Wu et al., AutoGen: Enabling Next-Gen LLM Applications via Multi-Agent Conversation (2023)', 'arXiv:2308.08155'], ['AutoGen repository README (maintenance-mode notice)', 'github.com/microsoft/autogen'], ['Microsoft Agent Framework repository', 'github.com/microsoft/agent-framework']],
  fresh: 'volatile', tsc: ['Project status, forks (e.g. AG2), Microsoft agent-framework lineage and versions.', 'Package names and APIs.'],
  keywords: ['multi-agent', 'conversation', 'microsoft']
}),

E('crewai', 'CrewAI', 'framework', P, {
  summary: 'CrewAI is a Python framework for orchestrating role-playing agent "crews" that carry out defined tasks, with a higher-level API than graph-style frameworks.',
  short: 'CrewAI organises work as **agents with roles, goals and tools, assigned tasks within a crew**, run sequentially or hierarchically. It is quick to start; control and debugging depth differ from lower-level frameworks, and APIs evolve.',
  plain: `CrewAI lets you describe a small team: a researcher, a writer, a reviewer — each with a role and tools — and a list of tasks. The framework handles running them in order and passing results along.`,
  technical: `Core abstractions as commonly documented: Agent (role, goal, backstory, tools), Task (description, expected output, assigned agent), Crew (agents + tasks + process such as sequential or hierarchical), and Flows for event-driven orchestration. It is an independent project (not tied to a model vendor). Features, enterprise offerings and APIs change across versions — verify against current documentation.`,
  aliases: ['CrewAI framework', 'crew ai', 'role based agents', 'crewai agents tasks', 'crewai vs autogen', 'crewai flows'],
  intents: ['prototype role-based multi-agent workflows', 'compare high-level agent frameworks'],
  questions: ['What is CrewAI?', 'CrewAI vs LangGraph?', 'How do I define agents and tasks in CrewAI?', 'Is CrewAI production ready?'],
  pre: ['multi-agent-systems', 'ai-agents'], rel: ['langgraph', 'autogen', 'agent-frameworks-compared', 'agentic-workflows', 'ai-evaluation'],
  vs: [['langgraph', 'LangGraph gives lower-level control of state and flow; CrewAI offers a higher-level role/task model.']],
  tech: ['CrewAI (Python)', 'tool integrations'],
  patterns: ['Sequential crew with clearly scoped tasks.', 'Hierarchical process with a manager agent.', 'Structured task outputs passed between agents.'],
  fails: ['Vague role descriptions causing overlap and wasted tokens.', 'Unbounded delegation.', 'Opaque runs hard to debug without tracing.', 'Assuming roles equal reliability.'],
  fix: [['Outputs inconsistent between tasks', 'Define expected output schemas and tighten task descriptions.'], ['High token usage', 'Reduce agents, cap iterations, use cheaper models for simple roles.']],
  guide: ['Decide if a fixed workflow would suffice.', 'Define tasks and expected outputs first.', 'Assign minimal tools per agent.', 'Trace and evaluate.'],
  when: 'Good for fast prototypes of role-structured pipelines.',
  sources: [['CrewAI documentation', 'docs.crewai.com (verify)'], ['CrewAI repository', 'github.com/crewAIInc/crewAI (verify)']],
  fresh: 'volatile', tsc: ['Current API, versions, commercial offerings and licence.'],
  keywords: ['roles', 'tasks', 'crew']
}),

E('semantic-kernel', 'Semantic Kernel', 'framework', P, {
  summary: 'Semantic Kernel is Microsoft\'s open-source SDK (C#, Python, Java) for integrating LLMs into applications with plugins, planning and agent abstractions.',
  short: 'Semantic Kernel is an **enterprise-oriented SDK** that wraps model calls, plugins (functions/tools), memory connectors and agents, with strong .NET support. Its repository now names **Microsoft Agent Framework** as its enterprise-ready successor and provides a migration guide (status as of 2026-10-09).',
  plain: `Semantic Kernel is Microsoft\'s toolkit for adding AI to apps, especially in .NET and enterprise settings. You register your code as plugins the model can call, and the kernel manages prompts, tools and agents.`,
  technical: `Concepts: kernel, plugins/functions exposed to models via function calling, prompt templates, connectors for models and vector stores, agent framework and process framework. Language support and feature parity vary across C#, Python and Java. As of 2026-10-09 the Semantic Kernel repository states that Microsoft Agent Framework (MAF) is the enterprise-ready successor to Semantic Kernel, available as a 1.0 production release, and links a migration guide; the AutoGen repository names the same successor. Treat Semantic Kernel as an established SDK for existing systems and evaluate MAF for new agent work.`,
  aliases: ['SK', 'Semantic Kernel SDK', 'semantic kernel plugins', 'microsoft semantic kernel', 'semantic kernel agents', 'semantic kernel C#'],
  intents: ['add LLM features to a .NET application', 'choose among Microsoft agent SDKs'],
  questions: ['What is Semantic Kernel?', 'Semantic Kernel vs LangChain?', 'How do plugins work in Semantic Kernel?', 'Is Semantic Kernel being replaced?'],
  pre: ['function-calling', 'agent-tools'], rel: ['autogen', 'langchain', 'agent-frameworks-compared', 'azure-fundamentals', 'framework-vs-direct-api'],
  vs: [['langchain', 'LangChain is Python/JS-first with broad community integrations; Semantic Kernel is Microsoft-stack oriented with first-class .NET.']],
  tech: ['Semantic Kernel (C#, Python, Java)', 'Azure OpenAI integrations', 'plugins'],
  patterns: ['Expose domain services as plugins with clear descriptions.', 'Use function-calling to let the model select plugins.', 'Keep permissions and auth in plugin code.'],
  fails: ['Feature mismatch between language SDKs.', 'Plugins with vague descriptions causing wrong tool choice.', 'Preview APIs changing.', 'Auth handled in prompts rather than code.'],
  fix: [['Tool not invoked', 'Improve plugin/function descriptions and parameter schemas; confirm function calling is enabled for the model.'], ['API removed after upgrade', 'Check release notes; avoid experimental features in production.']],
  guide: ['Check feature support for your language.', 'Define plugins for narrow capabilities.', 'Test tool selection with realistic prompts.', 'Pin versions.'],
  when: 'Existing .NET/Microsoft-stack systems built on it; for new Microsoft-stack agent projects, compare with Microsoft Agent Framework, which Microsoft positions as the successor.',
  sources: [['Semantic Kernel documentation', 'learn.microsoft.com/semantic-kernel (verify)'], ['Semantic Kernel repository', 'github.com/microsoft/semantic-kernel']],
  fresh: 'volatile', tsc: ['Roadmap and relationship to other Microsoft agent frameworks.', 'Per-language feature support and versions.'],
  keywords: ['.NET', 'plugins', 'Microsoft']
}),

E('openai-agents-sdk', 'OpenAI Agents SDK', 'framework', P, {
  summary: 'The OpenAI Agents SDK is an open-source library for building agentic applications with agents, tools, handoffs and guardrails; it is provider-vendor maintained and can be used with other model providers via adapters.',
  short: 'A lightweight SDK with **agents, tools, handoffs, guardrails and tracing primitives**. As vendor-maintained software it can change quickly; verify the current API, supported providers and licence in the repository.',
  plain: `A small toolkit from OpenAI for building agents: you define an agent with instructions and tools, let it hand work to other agents, add guardrails to check inputs and outputs, and trace what happened.`,
  technical: `Introduced in 2025 as a production-oriented evolution of an earlier experimental library (Swarm). Documented primitives include agents, tools (function tools, hosted tools), handoffs between agents, guardrails (input/output validation), sessions/memory and tracing. As of 2026-10-09 there are Python and JavaScript/TypeScript SDKs, and the Python README describes the SDK as provider-agnostic (OpenAI Responses and Chat Completions APIs plus other LLMs through adapters such as LiteLLM). Feature parity with hosted OpenAI tools still varies by provider and should be checked per feature.`,
  aliases: ['OpenAI Agents SDK', 'agents sdk', 'openai swarm', 'handoffs agents', 'openai agents python', 'agent guardrails sdk'],
  intents: ['build agents with vendor tooling', 'understand handoffs and guardrails'],
  questions: ['What is the OpenAI Agents SDK?', 'What is a handoff in an agent SDK?', 'Can the Agents SDK use other model providers?', 'OpenAI Agents SDK vs LangGraph?'],
  pre: ['ai-agents', 'function-calling'], rel: ['agent-frameworks-compared', 'langgraph', 'ai-guardrails', 'multi-agent-systems', 'ai-sdks'],
  vs: [['langgraph', 'LangGraph exposes explicit graph state; the Agents SDK emphasises small primitives (agents, handoffs, guardrails).']],
  tech: ['OpenAI Agents SDK (Python/JS)', 'tracing', 'hosted tools'],
  patterns: ['Triage agent with specialist handoffs.', 'Input/output guardrails running alongside the agent.', 'Function tools wrapping your services with validation.'],
  fails: ['Assuming guardrails are complete security.', 'Provider-specific features not portable.', 'Version drift.', 'Unbounded tool loops.'],
  fix: [['Handoffs not triggered', 'Clarify handoff descriptions and agent instructions.'], ['Behaviour differs with another provider', 'Check which features are provider-specific.']],
  guide: ['Read the current docs.', 'Define narrow agents and tools.', 'Add guardrails and limits.', 'Enable tracing and evaluate.'],
  when: 'Reasonable when you already build on the vendor\'s API and want first-party primitives.',
  sources: [['OpenAI Agents SDK documentation', 'openai.github.io/openai-agents-python (verify)'], ['Repository', 'github.com/openai/openai-agents-python (verify)']],
  fresh: 'volatile', tsc: ['Existence, API, licensing, language support and provider-agnostic claims — verify all.'],
  keywords: ['handoffs', 'guardrails', 'tracing']
}),

E('agent-frameworks-compared', 'AI Agent Frameworks Compared', 'concept', P, {
  page_kind: 'comparison',
  summary: 'Agent frameworks differ in abstraction level, control, language and ecosystem. Compare by what you need — state control, retrieval, multi-agent, enterprise language — not by popularity.',
  short: 'Choose by **needs**: low-level control and persistence (graph/state-machine style), data/retrieval depth (RAG-first), fast role-based prototypes, .NET/enterprise integration, or plain SDK calls. Always verify current versions; the field changes monthly.',
  plain: `There is no single best agent framework. Some give you fine control, some get you a prototype fast, some are strongest at working with your documents. Often the simplest answer is a few direct API calls.`,
  technical: `| Framework | Typical emphasis | Language(s) | Consider when |\n|---|---|---|---|\n| [[langchain]] | Broad integrations and components | Python, JS/TS | You need many connectors |\n| [[langgraph]] | Stateful graph orchestration, persistence, approvals | Python, JS/TS | You need control over loops |\n| [[llamaindex]] | Data ingestion, indexing, retrieval | Python, TS | RAG-centred work |\n| [[dspy]] | Programmatic pipelines with optimisation | Python | You have a metric and examples |\n| [[autogen]] | Conversational multi-agent (maintenance mode; successor: Microsoft Agent Framework) | Python, .NET | Maintaining existing AutoGen systems |\n| [[crewai]] | Role/task crews | Python | Fast role-based prototypes |\n| [[semantic-kernel]] | Enterprise SDK with plugins (successor named: Microsoft Agent Framework) | C#, Python, Java | Existing Microsoft-stack systems |\n| [[openai-agents-sdk]] | Lightweight primitives, handoffs, guardrails | Python, JavaScript/TypeScript | Building on that vendor's API (README describes it as provider-agnostic) |\n\nThis table is a neutral orientation, not a recommendation or ranking; feature claims need verification against current docs.`,
  aliases: ['which agent framework', 'best agent framework', 'LangGraph vs CrewAI vs AutoGen', 'agent framework comparison', 'what framework should I use for AI agents', 'LLM framework comparison', 'langchain alternatives'],
  intents: ['choose an agent framework', 'decide whether a framework is needed'],
  questions: ['Which AI agent framework should I use?', 'LangGraph vs CrewAI vs AutoGen?', 'Do I need an agent framework?', 'What are alternatives to LangChain?'],
  pre: ['ai-agents', 'agentic-workflows'], rel: ['choosing-an-agent-framework', 'what-is-an-ai-framework', 'framework-vs-direct-api', 'multi-agent-systems', 'mcp', 'a2a-protocol'],
  vs: [['framework-vs-direct-api', 'The baseline alternative to any framework.']],
  tech: ['LangChain', 'LangGraph', 'LlamaIndex', 'DSPy', 'AutoGen', 'CrewAI', 'Semantic Kernel', 'OpenAI Agents SDK'],
  patterns: ['Prototype with direct SDK calls; adopt a framework when specific needs appear.', 'Wrap framework code behind your own interfaces.', 'Evaluate on your tasks, not demos.'],
  fails: ['Choosing by GitHub stars.', 'Locking business logic into framework classes.', 'Using multi-agent frameworks for single-step tasks.'],
  fix: [['Framework fighting you', 'Drop to direct calls for that part; keep the framework where it helps.']],
  guide: ['Write down requirements: control, persistence, languages, retrieval, approvals.', 'Shortlist 2.', 'Build the same small task in each.', 'Compare debugging, tests and maintainability.', 'Decide and pin versions.'],
  when: 'Use when selecting tooling; revisit as the ecosystem changes.',
  sources: [['Each framework\'s current official documentation (see individual entries)', null], ['Anthropic, Building effective agents (guidance on simple composable patterns; verify URL and date)', null]],
  fresh: 'volatile', tsc: ['All feature, status, licence and versions claims for each framework.'],
  keywords: ['comparison', 'framework', 'orchestration']
}),

E('vllm', 'vLLM', 'runtime', P, {
  summary: 'vLLM is an open-source LLM inference and serving engine known for PagedAttention, continuous batching and high throughput on GPUs.',
  short: 'vLLM is a **high-throughput serving engine** for LLMs, using paged KV-cache memory and continuous batching, with an OpenAI-compatible API server and support for quantisation and many model families. Choose it for multi-user GPU serving rather than casual laptop use.',
  plain: `vLLM is software for running language models efficiently for many users at once. It manages GPU memory cleverly and batches requests continuously, so a single GPU server can answer far more requests than a naive setup.`,
  technical: `Introduced with PagedAttention (Kwon et al., 2023) and a PyTorch Foundation hosted project since 2025, vLLM stores KV cache in non-contiguous blocks to reduce fragmentation, and schedules requests with continuous batching. Common features: OpenAI-compatible HTTP server, tensor/pipeline parallelism, prefix caching, quantisation support, speculative decoding, guided decoding backends ([[constrained-decoding]]), LoRA adapter serving, and multi-modal model support. Hardware support (NVIDIA, AMD, others), supported models and flags change frequently.`,
  aliases: ['vLLM server', 'vllm serve', 'PagedAttention', 'continuous batching', 'LLM inference engine', 'high throughput LLM serving', 'OpenAI compatible server', 'self-hosted LLM serving'],
  intents: ['serve an open model to many users', 'choose an inference engine'],
  questions: ['What is vLLM?', 'How do I serve an LLM with vLLM?', 'vLLM vs Ollama vs llama.cpp?', 'What is continuous batching?', 'How does PagedAttention work?'],
  pre: ['kv-cache', 'model-serving-and-inference'], rel: ['local-runtimes-compared', 'llama-cpp', 'ollama', 'quantization', 'speculative-decoding', 'gpus-and-ai-accelerators', 'constrained-decoding'],
  vs: [['ollama', 'Ollama prioritises easy local use; vLLM prioritises multi-user throughput.'], ['llama-cpp', 'llama.cpp excels on CPUs/consumer hardware and GGUF; vLLM targets GPU servers.']],
  tech: ['vLLM', 'CUDA', 'Ray (for multi-node)', 'Hugging Face model hub'],
  patterns: ['Run behind a gateway with auth and rate limits.', 'Use tensor parallelism for models larger than one GPU.', 'Enable prefix caching for shared prompts.', 'Autoscale replicas with a load balancer.'],
  fails: ['OOM from too-large max context or batch settings.', 'Version/CUDA/driver mismatches.', 'Unsecured open endpoint.', 'Assuming every model architecture is supported.'],
  fix: [['CUDA out of memory', 'Reduce max model length / GPU memory utilisation, quantise, or add GPUs.'], ['Server fails to start', 'Match vLLM, PyTorch, CUDA and driver versions; check model support list.']],
  guide: ['Check model support and licence.', 'Size GPU memory (weights + KV cache).', 'Launch the OpenAI-compatible server.', 'Load-test with realistic traffic.', 'Add auth, monitoring ([[llm-observability]]).'],
  when: 'Use for production-style self-hosted serving on GPUs.',
  sources: [['Kwon et al., Efficient Memory Management for LLM Serving with PagedAttention (2023)', 'arXiv:2309.06180'], ['vLLM documentation', 'docs.vllm.ai (verify)']],
  fresh: 'volatile', tsc: ['Supported hardware, models, features and flags.', 'Project governance and hosting.'],
  keywords: ['serving', 'throughput', 'GPU']
}),

E('llama-cpp', 'llama.cpp', 'runtime', P, {
  summary: 'llama.cpp is a C/C++ inference engine for running LLMs efficiently on CPUs and consumer GPUs, using the GGUF format and aggressive quantisation.',
  short: 'llama.cpp runs **quantised GGUF models on almost any hardware** (CPU, Apple Silicon, consumer GPUs) via a CLI and a built-in server with an OpenAI-style API, and supports grammar-constrained output. It underlies several desktop tools.',
  plain: `llama.cpp is a lightweight program for running language models on ordinary computers — laptops, desktops, even phones — without needing a data-centre GPU. It uses compressed model files so big models fit in modest memory.`,
  technical: `Created by Georgi Gerganov and built on the GGML tensor library; model files use the GGUF container with multiple quantisation types. Features include CPU SIMD kernels, Metal/CUDA/Vulkan and other backends, partial GPU offload, a server, grammar-based sampling ([[gbnf-grammars]]) and multimodal model support in recent builds. Repository ownership and organisation have changed; verify the canonical location. Wrappers such as [[ollama]] and various GUIs build on it or similar engines.`,
  aliases: ['llama cpp', 'llamacpp', 'ggml', 'gguf', 'llama-server', 'run LLM on CPU', 'llama.cpp server', 'run llama on laptop', 'Apple Silicon LLM'],
  intents: ['run models locally on modest hardware', 'serve a small local API'],
  questions: ['What is llama.cpp?', 'How do I run a model with llama.cpp?', 'What is GGUF?', 'llama.cpp vs Ollama?', 'Can I run an LLM on CPU only?'],
  pre: ['quantization', 'local-ai'], rel: ['ollama', 'vllm', 'gbnf-grammars', 'local-runtimes-compared', 'small-language-models', 'onnx-runtime'],
  vs: [['ollama', 'Ollama adds model management and a friendlier CLI/API; llama.cpp is the lower-level engine with more knobs.'], ['vllm', 'vLLM targets GPU server throughput.']],
  tech: ['llama.cpp', 'GGUF', 'Metal / CUDA / Vulkan backends'],
  patterns: ['Choose quantisation by memory budget (test quality).', 'Offload as many layers to GPU as fits.', 'Bind the server to localhost unless secured.', 'Use grammars for structured output.'],
  fails: ['Model too large for RAM causing swapping.', 'Build flags missing GPU backend.', 'Exposing the server to the network without auth.', 'Outdated GGUF files for newer builds.'],
  fix: [['Very slow generation', 'Check that GPU offload is active; use a smaller quantisation or model.'], ['Model fails to load', 'Match GGUF version/format to the llama.cpp build.']],
  guide: ['Estimate memory needs.', 'Download a trusted GGUF.', 'Run with a small context first.', 'Tune GPU layers and threads.', 'Secure the server.'],
  when: 'Best for local, personal and edge use.',
  sources: [['llama.cpp repository and documentation', 'github.com/ggml-org/llama.cpp (verify current location)']],
  fresh: 'volatile', tsc: ['Repository location and governance.', 'Supported models, backends, formats and flags.'],
  keywords: ['GGUF', 'local', 'CPU']
}),

E('ollama', 'Ollama', 'runtime', P, {
  summary: 'Ollama is a tool that downloads, manages and runs open models locally with a simple command line and a local HTTP API.',
  short: 'Ollama makes local models **easy to pull and run** (`ollama run <model>`) and exposes a local API (default port 11434). It wraps inference engines and a model library; check current docs for supported models, formats and settings.',
  plain: `Ollama is the "app store plus launcher" for local AI. One command downloads a model and starts a chat; other programs can talk to it through a local web address on your own machine.`,
  technical: `Ollama packages models with configuration (Modelfile), manages downloads and storage, and serves a REST API on localhost (default 11434) with an optional OpenAI-compatible endpoint. Historically built on llama.cpp-family engines; engine details have evolved, so verify. Structured-output and tool-calling support depend on version and model.`,
  aliases: ['ollama run', 'ollama serve', 'ollama modelfile', 'run LLM locally easily', 'ollama API', 'ollama localhost 11434', 'ollama models'],
  intents: ['get a local model running quickly', 'call a local model from code'],
  questions: ['What is Ollama?', 'How do I run Llama with Ollama?', 'How do I call Ollama from Python?', 'Ollama vs llama.cpp vs vLLM?', 'Is Ollama private?'],
  pre: ['local-ai'], rel: ['llama-cpp', 'vllm', 'local-runtimes-compared', 'quantization', 'structured-outputs', 'local-ai-vs-cloud-ai'],
  vs: [['llama-cpp', 'llama.cpp is the lower-level engine; Ollama adds management and APIs.'], ['vllm', 'vLLM targets multi-user GPU serving; Ollama targets personal/local use.']],
  tech: ['Ollama CLI and API', 'Modelfile', 'GGUF models'],
  patterns: ['Local dev environment with an OpenAI-compatible client pointed at localhost.', 'Modelfile to set system prompt and parameters.', 'Keep the API bound to localhost.'],
  fails: ['Exposing the API publicly without authentication.', 'Models too large for available memory.', 'Assuming parity with hosted model features.', 'Trusting unvetted community models.'],
  fix: [['Connection refused', 'Check the service is running and the port/host settings.'], ['Slow responses', 'Pick a smaller or more quantised model; confirm GPU use.']],
  guide: ['Install from the official site.', 'Pull a small model first.', 'Test via CLI and API.', 'Set parameters via Modelfile.', 'Keep it local or secure it.'],
  when: 'Good default for local experimentation and development.',
  sources: [['Ollama documentation and repository', 'ollama.com and github.com/ollama/ollama (verify)']],
  fresh: 'volatile', tsc: ['Supported models, API fields, default ports/settings and engine internals.'],
  keywords: ['local models', 'CLI', 'API']
}),

E('onnx-runtime', 'ONNX Runtime', 'runtime', P, {
  summary: 'ONNX Runtime is a cross-platform engine for running machine-learning models exported to the ONNX format across CPUs, GPUs and edge devices.',
  short: 'Export a model to **ONNX**, then run it with ONNX Runtime and the right **execution provider** (CPU, CUDA, DirectML, CoreML…) for portable, optimised inference, including in browsers and mobile apps. LLM support exists via dedicated generation tooling; check compatibility.',
  plain: `ONNX is a common file format for AI models; ONNX Runtime is a fast, portable engine that runs those files on many kinds of hardware and platforms, including phones and web browsers. It is popular for shipping smaller models inside applications.`,
  technical: `ONNX defines a model graph and operator set; ONNX Runtime applies graph optimisations and dispatches to execution providers. Export from PyTorch/TensorFlow uses exporters that may need operator-set/version care. Browser deployment uses WebAssembly/WebGPU backends (ONNX Runtime Web) and libraries such as Transformers.js build on it. Generative-model support, quantisation tooling and provider coverage vary by version.`,
  aliases: ['ONNX', 'ORT', 'onnxruntime', 'ONNX export', 'ONNX runtime web', 'DirectML', 'execution provider', 'transformers.js', 'run model in browser'],
  intents: ['deploy a model across platforms', 'run models in the browser or on device'],
  questions: ['What is ONNX Runtime?', 'How do I export a PyTorch model to ONNX?', 'Can I run AI models in the browser?', 'ONNX Runtime vs PyTorch for inference?'],
  pre: ['neural-networks', 'model-serving-and-inference'], rel: ['pytorch', 'quantization', 'local-ai', 'llama-cpp', 'local-runtimes-compared', 'hugging-face'],
  vs: [['llama-cpp', 'llama.cpp is specialised for LLMs/GGUF; ONNX Runtime is a general model runtime.'], ['pytorch', 'PyTorch is a training/research framework; ONNX Runtime focuses on deployment.']],
  tech: ['ONNX Runtime (+Web, Mobile)', 'Optimum (Hugging Face)', 'Transformers.js', 'DirectML'],
  patterns: ['Export, validate numerical parity, quantise, deploy.', 'Pick execution providers per platform.', 'In-browser inference for privacy-preserving demos.'],
  fails: ['Unsupported operators during export.', 'Numerical drift after export or quantisation.', 'Large model downloads in browsers.', 'Provider-specific behaviour differences.'],
  fix: [['Export fails on an operator', 'Change opset version or rewrite the op.'], ['Output differs from PyTorch', 'Compare layer outputs; check dtype and preprocessing.']],
  guide: ['Export with a recent opset.', 'Validate outputs against the original.', 'Optimise/quantise.', 'Test per target platform.', 'Mind download size for web.'],
  when: 'Use for portable, on-device and browser deployment of small to mid-size models.',
  sources: [['ONNX Runtime documentation', 'onnxruntime.ai'], ['ONNX specification', 'onnx.ai']],
  fresh: 'volatile', tsc: ['Generative-AI support, execution-provider coverage and versions.'],
  keywords: ['deployment', 'portable', 'edge']
}),

E('hugging-face', 'Hugging Face Transformers and the Hub', 'library', P, {
  overlay: true,
  summary: 'The Hugging Face Transformers library provides a unified API for thousands of pre-trained models; the Hub hosts models, datasets and demos.',
  short: 'Transformers gives **one API (`AutoModel`, `pipeline`) across many pretrained models**; the Hub distributes weights, model cards and datasets. Check each model\'s licence and prefer safetensors from reputable publishers.',
  plain: `Hugging Face is the main public library and website for sharing AI models. With a few lines of Python you can download a pre-trained model and use or fine-tune it, and the Hub shows each model\'s documentation and licence.`,
  technical: `The transformers library (PyTorch-first, with other backends in varying states of support) offers tokenisers, model classes, \`pipeline\` helpers, the \`Trainer\` API and integration with accelerate/PEFT/TRL. The Hub provides git-based model and dataset repositories, model cards and gated access. Security considerations: avoid loading untrusted pickled checkpoints; prefer safetensors; review custom code flags such as trust_remote_code.`,
  aliases: ['transformers library', 'huggingface', 'hugging face hub', 'AutoModel', 'pipeline API', 'safetensors', 'model hub', 'trust_remote_code', 'datasets library'],
  intents: ['load and run a pre-trained model', 'download models safely'],
  questions: ['What is Hugging Face Transformers?', 'How do I load a model from the Hugging Face Hub?', 'What is safetensors?', 'Is trust_remote_code safe?', 'How do I fine-tune a model with Transformers?'],
  pre: ['python-for-ai', 'transformers'], rel: ['pytorch', 'lora-and-peft', 'open-weights-models', 'transfer-learning', 'ollama', 'ai-privacy-and-security'],
  vs: [['pytorch', 'PyTorch is the underlying tensor/training framework; Transformers is a model library on top.'], ['ollama', 'Ollama is a runner for local inference; Transformers is a general library for training and inference.']],
  tech: ['transformers', 'datasets', 'accelerate', 'PEFT', 'TRL', 'safetensors', 'Hugging Face Hub'],
  patterns: ['pipeline for quick experiments; Auto classes for control.', 'Pin model revision hashes.', 'Use safetensors and avoid trust_remote_code unless reviewed.', 'Cache models in a controlled directory.'],
  fails: ['Loading untrusted pickles.', 'Version mismatches between libraries.', 'Out-of-memory loading large models in full precision.', 'Ignoring gated-model licence terms.'],
  fix: [['OOM on load', 'Use lower precision, device_map/offload or quantised variants.'], ['Tokenizer/model mismatch', 'Load tokenizer and model from the same repository and revision.']],
  guide: ['Create a virtual environment.', 'Pin library and model revisions.', 'Read the model card and licence.', 'Run a small inference test.', 'Evaluate before fine-tuning.'],
  when: 'Default open-model toolbox for Python developers.',
  sources: [['Hugging Face Transformers documentation', 'huggingface.co/docs/transformers'], ['Wolf et al., Transformers: State-of-the-Art Natural Language Processing (EMNLP demos, 2020)', 'arXiv:1910.03771']],
  fresh: 'volatile', tsc: ['Supported backends (PyTorch vs others), APIs and versions.', 'Hub features and policies.'],
  keywords: ['pretrained', 'hub', 'pipeline']
}),

E('pytorch', 'PyTorch', 'framework', P, {
  summary: 'PyTorch is the leading open-source deep-learning framework for research and increasingly production, built on tensors, automatic differentiation and eager execution.',
  short: 'PyTorch provides **tensors, autograd, `nn` modules and GPU acceleration** with a Pythonic, eager style, plus `torch.compile` for graph optimisation. Most open models are released with PyTorch weights.',
  plain: `PyTorch is the toolkit most AI researchers and engineers use to build and train neural networks in Python. It handles the heavy maths on GPUs and computes the gradients needed for learning automatically.`,
  technical: `Key features: dynamic computation graphs, autograd, torch.nn, DataLoader, distributed training (DDP/FSDP, see [[distributed-training]]), mixed precision, \`torch.compile\`, and export paths (TorchScript legacy, ONNX, ExecuTorch). Governance: hosted by the PyTorch Foundation, part of the Linux Foundation, which since 2025 has also hosted projects such as vLLM, DeepSpeed and Ray (as of 2026-10-09). Competing frameworks include JAX and TensorFlow, which differ in programming model and ecosystem.`,
  aliases: ['torch', 'pytorch tutorial', 'torch.compile', 'autograd', 'DDP', 'FSDP', 'pytorch vs tensorflow', 'pytorch lightning', 'tensor library'],
  intents: ['pick a deep-learning framework', 'start training models in Python'],
  questions: ['What is PyTorch?', 'PyTorch vs TensorFlow: which should I learn?', 'What is torch.compile?', 'How does autograd work?'],
  pre: ['python-for-ai', 'neural-networks', 'backpropagation-and-gradient-descent'], rel: ['hugging-face', 'distributed-training', 'gpus-and-ai-accelerators', 'onnx-runtime', 'deep-learning'],
  vs: [['onnx-runtime', 'ONNX Runtime focuses on portable inference; PyTorch on research and training.']],
  tech: ['PyTorch', 'CUDA', 'PyTorch Lightning', 'torchvision / torchaudio', 'JAX and TensorFlow (alternatives)'],
  patterns: ['Overfit-a-batch sanity check.', 'Mixed precision with autocast.', 'DDP or FSDP for multi-GPU.', 'Export to ONNX/other runtimes for deployment.'],
  fails: ['Device mismatch errors (CPU vs GPU tensors).', 'Forgetting model.eval() or no_grad() at inference.', 'Memory leaks from retaining graphs.', 'Non-determinism between runs.'],
  fix: [['RuntimeError: expected same device', 'Move model and tensors to the same device.'], ['CUDA OOM', 'Reduce batch size, use mixed precision or gradient checkpointing.']],
  guide: ['Install the CUDA-matched build.', 'Write a minimal training loop.', 'Verify on one batch.', 'Add mixed precision and logging.', 'Scale with DDP/FSDP.'],
  when: 'Default choice for deep-learning work; evaluate alternatives for specific hardware or ecosystem needs.',
  sources: [['PyTorch documentation', 'pytorch.org/docs'], ['Paszke et al., PyTorch: An Imperative Style, High-Performance Deep Learning Library (2019)', 'arXiv:1912.01703']],
  fresh: 'volatile', tsc: ['Current version features and foundation governance.'],
  keywords: ['tensors', 'autograd', 'GPU']
}),

E('local-runtimes-compared', 'Local and Self-Hosted LLM Runtimes Compared', 'concept', P, {
  page_kind: 'comparison',
  summary: 'llama.cpp, Ollama, vLLM, ONNX Runtime and Hugging Face Transformers serve different needs: personal local use, multi-user GPU serving, portable deployment or general experimentation.',
  short: '**Personal laptop**: Ollama or llama.cpp. **Multi-user GPU server**: vLLM (or similar). **Portable/browser/edge**: ONNX Runtime or llama.cpp builds. **Research/fine-tuning**: Transformers + PyTorch. Verify model/hardware support before committing.',
  plain: `"What should I run my model with?" depends on who is using it and on what hardware. One person on a laptop wants something easy; a team serving hundreds of users wants throughput; an app that runs in the browser wants something portable.`,
  technical: `| Runtime | Sweet spot | Hardware | Format | Caveat |\n|---|---|---|---|---|\n| [[ollama]] | Easy local use, dev | CPU/GPU, Apple Silicon | GGUF models via its library | Not built for high concurrency |\n| [[llama-cpp]] | Efficient local inference, fine control | CPU/GPU/mobile | GGUF | More manual setup |\n| [[vllm]] | Multi-user GPU serving | GPU servers | HF-format weights, many quantisations | GPU-centric; setup complexity |\n| [[onnx-runtime]] | Portable deployment, browser/mobile | CPU/GPU/NPU | ONNX | Export/operator support limits |\n| [[hugging-face]] | Research, fine-tuning, broad model access | GPU/CPU | Safetensors/PyTorch | Not tuned for production throughput by default |\n\nCapabilities change quickly — treat as orientation and verify.`,
  aliases: ['ollama vs vllm', 'llama.cpp vs ollama vs vllm', 'what should I use to run LLMs locally', 'best way to host an open model', 'self host LLM options', 'which inference engine should I use', 'local LLM runtime comparison'],
  intents: ['choose a runtime for local or self-hosted models', 'plan hardware and concurrency for self-hosted models'],
  questions: ['Ollama vs vLLM vs llama.cpp: which should I use?', 'What is the best way to self-host an LLM?', 'Which runtime is best for multiple users?', 'What should I use to run a model on a Mac?'],
  pre: ['local-ai', 'model-serving-and-inference'], rel: ['quantization', 'gpus-and-ai-accelerators', 'local-ai-vs-cloud-ai', 'open-weights-models'],
  vs: [['local-ai-vs-cloud-ai', 'The earlier hosting decision.']],
  tech: ['Ollama', 'llama.cpp', 'vLLM', 'ONNX Runtime', 'Hugging Face Transformers'],
  patterns: ['Prototype with Ollama; move to vLLM for concurrency.', 'Use OpenAI-compatible endpoints so clients are portable across runtimes.'],
  fails: ['Using a single-user runtime for production traffic.', 'Ignoring memory needs.'],
  fix: [['Slow under multiple users', 'Move to a batching server like vLLM or add replicas.']],
  guide: ['Count concurrent users.', 'Check hardware.', 'Check model/format support.', 'Prototype two options.', 'Load-test.'],
  when: 'Use as a first-pass decision aid.',
  sources: [['Each runtime\'s documentation (see entries)', null]],
  fresh: 'volatile', tsc: ['Feature support, performance characteristics and format compatibility.'],
  keywords: ['comparison', 'self-hosting', 'inference engine']
}),

// ---------- Agent & RAG patterns ----------
E('react-agent-pattern', 'The ReAct Pattern (Reason + Act)', 'technique', R, {
  summary: 'ReAct interleaves reasoning steps with actions: the model decides what to do, calls a tool, reads the observation and reasons again, forming the basic agent loop.',
  short: 'ReAct = **think → act (tool call) → observe → repeat**. It underlies most tool-using agents; make loops safe with step limits, validated tools and clear stopping criteria. Reasoning shown in the loop is working text, not a guaranteed explanation.',
  plain: `ReAct is the basic recipe for an AI agent: decide on a next step, use a tool, look at what came back, and decide again. Most agent frameworks implement some version of it.`,
  technical: `Yao et al. (2022) propose prompting models to alternate "thought" and "action" steps with observations, improving performance on knowledge-intensive and interactive tasks versus reasoning-only or acting-only baselines. Modern implementations use native tool-calling APIs ([[function-calling]]) instead of text parsing, and may use hidden or summarised reasoning ([[reasoning-transparency]]). Reliability depends on tool design, error handling and termination logic.`,
  aliases: ['ReAct', 'reason and act', 'ReAct prompting', 'thought action observation', 'agent loop', 'tool use loop', 'ReAct agent'],
  intents: ['understand the basic agent loop', 'implement a tool-using agent'],
  questions: ['What is ReAct?', 'How does the agent loop work?', 'How do I stop an agent from looping forever?', 'ReAct vs plan-and-execute?'],
  pre: ['ai-agents', 'agent-tools', 'function-calling'], rel: ['agent-planning', 'chain-of-thought', 'agent-frameworks-compared', 'agentic-workflows', 'ai-agents'],
  vs: [['agent-planning', 'ReAct decides step by step; planning-first agents draft a multi-step plan upfront.'], ['chain-of-thought', 'CoT reasons without acting; ReAct interleaves actions with observations.']],
  tech: ['native tool-calling APIs', 'LangGraph', 'OpenAI Agents SDK', 'custom loops'],
  patterns: ['Loop: model → tool call → result → model, with a hard step cap.', 'Validate tool args; return concise, informative errors.', 'Add a "finish" tool or explicit stop condition.', 'Log each step for debugging.'],
  fails: ['Infinite or oscillating loops.', 'Context bloat from verbose tool outputs.', 'Wrong tool selection from vague descriptions.', 'Acting on injected instructions in tool output.'],
  fix: [['Agent repeats the same call', 'Detect repeats, add loop limits and hint in the error message.'], ['Context overflows', 'Truncate/summarise tool results; store large data outside the prompt.']],
  guide: ['Define tools with clear schemas.', 'Implement the loop with limits.', 'Add stop conditions.', 'Trace runs.', 'Evaluate on tasks ([[agent-evaluation]]).'],
  when: 'The default pattern for exploratory tasks needing tools.',
  sources: [['Yao et al., ReAct: Synergizing Reasoning and Acting in Language Models (2022)', 'arXiv:2210.03629'], ['Schick et al., Toolformer (2023)', 'arXiv:2302.04761']],
  fresh: 'evolving', keywords: ['agent loop', 'tools', 'observation']
}),

E('agent-planning', 'Agent Planning and Task Decomposition', 'technique', R, {
  summary: 'Planning agents break a goal into steps before or while acting, revising the plan as results arrive. Explicit plans help with long tasks and make oversight easier.',
  short: 'Planning patterns: **plan-then-execute**, **adaptive re-planning**, and **hierarchical decomposition** into sub-tasks. Plans make long tasks inspectable and approvable, but fixed plans fail when reality differs.',
  plain: `Rather than improvising every step, a planning agent first writes down what it intends to do, then carries it out and updates the plan when something unexpected happens. It is easier to review a plan than a stream of actions.`,
  technical: `Patterns: plan-and-solve prompting (Wang et al., 2023), plan-and-execute architectures with a planner and executor, hierarchical task decomposition, and re-planning on failure or new information. Plans can be represented as structured lists/graphs ([[structured-outputs]]) and checked by programs or humans. Reflection loops (Reflexion, Shinn et al., 2023) feed outcomes back into subsequent attempts. Reliability challenges include plan drift, over-long plans and brittle dependencies between steps.`,
  aliases: ['task decomposition', 'plan and execute', 'planning agents', 'plan-and-solve', 'hierarchical planning agents', 'reflexion', 'replanning', 'agent reflection'],
  intents: ['improve reliability on long tasks', 'add human review of plans'],
  questions: ['How do AI agents plan?', 'What is plan-and-execute?', 'How do I break a goal into sub-tasks for an agent?', 'What is Reflexion?'],
  pre: ['ai-agents', 'react-agent-pattern'], rel: ['agentic-workflows', 'multi-agent-systems', 'agent-memory', 'agent-evaluation', 'search-over-reasoning'],
  vs: [['react-agent-pattern', 'ReAct is incremental; planning commits to a structure first.']],
  tech: ['LangGraph', 'structured output plans', 'task queues'],
  patterns: ['Planner emits a JSON plan; executor runs each step with verification.', 'Re-plan when a step fails or new information changes assumptions.', 'Human approval of the plan before irreversible steps.', 'Cap plan length and depth.'],
  fails: ['Plan drift: execution deviates from the plan unnoticed.', 'Overly rigid plans.', 'Hallucinated steps or unavailable tools.', 'Plans that exceed context or budget.'],
  fix: [['Steps depend on missing info', 'Add information-gathering steps and allow re-planning.'], ['Plan too long', 'Plan at a coarser level; expand just-in-time.']],
  guide: ['Define available tools to the planner.', 'Emit structured plans.', 'Validate against allowed actions.', 'Execute with checks.', 'Re-plan on failure.'],
  when: 'Use for multi-step tasks where oversight or reliability justify the overhead.',
  sources: [['Wang et al., Plan-and-Solve Prompting (2023)', 'arXiv:2305.04091'], ['Shinn et al., Reflexion (2023)', 'arXiv:2303.11366']],
  fresh: 'evolving', keywords: ['decomposition', 'plan', 'reflection']
}),

E('computer-use-agents', 'Computer-Use and Browser Agents', 'concept', R, {
  summary: 'Computer-use agents operate software through its user interface — viewing screens, clicking and typing — rather than through APIs. They are powerful and risky, and still error-prone.',
  short: 'These agents **see screenshots/DOM and issue mouse and keyboard actions**. They can automate apps without APIs, but are slower, brittle and exposed to prompt injection from on-screen content; run them sandboxed with minimal permissions and human confirmation.',
  plain: `Instead of calling an app\'s programming interface, these agents use the app like a person would: they look at the screen, move the pointer, click and type. That lets them handle software that has no API, but they make mistakes and can be tricked by hostile web pages.`,
  technical: `Implementations pair a vision-language model ([[vision-language-models]]) or DOM-based observation with an action space (click, type, scroll, navigate) in a loop ([[react-agent-pattern]]). Benchmarks such as WebArena (Zhou et al., 2023) and OSWorld (Xie et al., 2024) evaluate such agents; reported success rates vary by model and date and should be verified. Major providers have released computer-use features since 2024; capabilities and availability change quickly. Security concerns include indirect prompt injection via web content, credential exposure and irreversible actions.`,
  aliases: ['computer use', 'browser agents', 'web agents', 'GUI agents', 'operator agents', 'screen control AI', 'AI that uses a computer', 'RPA with LLMs', 'WebArena', 'OSWorld'],
  intents: ['automate software without an API', 'assess computer-use risk'],
  questions: ['What are computer-use agents?', 'How do browser agents work?', 'Is it safe to let an AI control my computer?', 'Computer-use agent vs API integration?'],
  pre: ['ai-agents', 'vision-language-models', 'prompt-injection'], rel: ['code-execution-sandboxing', 'ai-privacy-and-security', 'agent-evaluation', 'agent-tools', 'mcp'],
  vs: [['agent-tools', 'API/tool integrations are faster and more reliable when available; computer use is the fallback for UI-only software.']],
  tech: ['headless browsers', 'Playwright', 'VLM providers\' computer-use features', 'containerised desktops'],
  patterns: ['Run in a disposable VM/container with no real credentials.', 'Allow-list domains and apps.', 'Human confirmation for purchases, sends and deletions.', 'Prefer APIs/MCP tools when available.'],
  fails: ['Clicking the wrong element.', 'Injected instructions from web pages.', 'CAPTCHAs and logins blocking progress.', 'Cost/latency from many screenshots.', 'Violating site terms of service.'],
  fix: [['Agent stuck on a page', 'Add step limits, retries with fresh screenshots, and escalation to a human.'], ['Suspicious behaviour after visiting a page', 'Treat page content as untrusted; restrict navigation and permissions.']],
  guide: ['Check for an API first.', 'Build a sandbox.', 'Limit domains and credentials.', 'Add approvals.', 'Evaluate on realistic tasks and monitor.'],
  when: 'Use when no API exists and risk can be contained.',
  sources: [['Zhou et al., WebArena: A Realistic Web Environment for Building Autonomous Agents (2023)', 'arXiv:2307.13854'], ['Xie et al., OSWorld (2024)', 'arXiv:2404.07972'], ['Provider documentation for computer-use features (identify current pages)', null]],
  fresh: 'volatile', tsc: ['Which providers offer computer-use features, their availability and safety guidance.', 'Benchmark success rates.'],
  keywords: ['GUI', 'browser', 'screenshots']
}),

E('code-execution-sandboxing', 'Code Execution and Sandboxing for AI Agents', 'technique', R, {
  summary: 'Agents that write and run code need isolation: sandboxes limit filesystem, network, resources and credentials so a mistake or injected instruction cannot harm the host.',
  short: 'Run model-generated code in a **disposable, restricted environment**: no secrets, limited network, CPU/memory/time caps, read-only mounts. Containers help but are not equal to microVM/gVisor-style stronger isolation. Never execute generated code on a machine holding credentials.',
  plain: `Letting an AI run code is powerful and risky — a bug or a trick could delete files or leak secrets. A sandbox is a locked room: the code runs there, with only what it needs, and the room is thrown away afterwards.`,
  technical: `Isolation options: containers (namespaces/cgroups; shared kernel), user-space kernels such as gVisor, microVMs such as Firecracker, WebAssembly runtimes, and hosted code-interpreter services. Controls: non-root users, seccomp/AppArmor profiles, resource limits, ephemeral filesystems, egress firewalls or allow-lists, no mounted credentials, timeouts, output size caps and auditing. Threats include escape, resource exhaustion, data exfiltration and malicious dependencies.`,
  aliases: ['code interpreter', 'sandbox for LLM code', 'run AI generated code safely', 'agent sandbox', 'gVisor', 'Firecracker microVM', 'code execution tool', 'secure code execution'],
  intents: ['run generated code safely', 'choose isolation technology'],
  questions: ['How do I safely run code generated by an LLM?', 'Is Docker enough to sandbox AI-generated code?', 'What is a code interpreter tool?', 'What is gVisor?'],
  pre: ['agent-tools', 'prompt-injection'], rel: ['computer-use-agents', 'ai-privacy-and-security', 'mcp-security', 'docker', 'ai-guardrails'],
  vs: [['computer-use-agents', 'Computer use controls UIs; code execution sandboxes contain programs the agent writes.']],
  tech: ['Docker', 'gVisor', 'Firecracker', 'WebAssembly runtimes', 'hosted code-interpreter services'],
  patterns: ['Ephemeral container per run with CPU/memory/time limits.', 'No network by default; allow-list when needed.', 'Pass inputs as files; return outputs through a narrow channel.', 'Static scan and package allow-lists.'],
  fails: ['Mounting host directories or credentials.', 'Unrestricted network egress.', 'Reusing state between users.', 'Resource exhaustion.', 'Assuming containers are a hard security boundary.'],
  fix: [['Code needs packages', 'Pre-build an image with approved libraries instead of allowing arbitrary installs.'], ['Concern about escape', 'Use stronger isolation (microVM/gVisor) and run on dedicated infrastructure.']],
  guide: ['Define what code may do.', 'Choose an isolation level matching the threat model.', 'Strip secrets; restrict network.', 'Set limits and timeouts.', 'Log and review executions.'],
  when: 'Required whenever agents execute code or shell commands.',
  sources: [['OWASP guidance on LLM application security', 'genai.owasp.org'], ['Documentation for the chosen sandbox technology (gVisor, Firecracker, container runtime)', null]],
  fresh: 'evolving', keywords: ['sandbox', 'isolation', 'containers']
}),

E('hybrid-search-and-reranking', 'Hybrid Search and Reranking', 'technique', R, {
  summary: 'Hybrid search combines keyword (lexical) and vector (semantic) retrieval; reranking then reorders the top candidates with a more precise model. Together they improve RAG retrieval quality.',
  short: 'Run **BM25 keyword search and vector search**, merge results (for example by reciprocal rank fusion), then **rerank the top-N with a cross-encoder or LLM**. This catches exact terms and meaning, and boosts precision before context goes to the model.',
  plain: `Keyword search is great at exact words like product codes; vector search is great at meaning. Using both and then having a stronger model re-sort the best candidates gives better results than either alone.`,
  technical: `Lexical retrieval (BM25; Robertson & Zaragoza, 2009) and dense retrieval ([[embeddings]], e.g. DPR, Karpukhin et al., 2020) have complementary strengths. Fusion options include reciprocal rank fusion (Cormack et al., 2009) and weighted score combination after normalisation. Rerankers: cross-encoders (e.g. monoBERT-style, Nogueira & Cho, 2019), late-interaction models (ColBERT, Khattab & Zaharia, 2020) or LLM-based rerankers; they add latency proportional to candidates scored. Evaluate with recall@k and nDCG on labelled queries ([[rag-evaluation]]).`,
  aliases: ['hybrid search', 'BM25 plus vectors', 'reranker', 'cross-encoder reranking', 'reciprocal rank fusion', 'RRF', 'ColBERT', 'rerank RAG results', 'improve RAG retrieval', 'keyword and semantic search'],
  intents: ['improve retrieval quality', 'handle exact-match terms in RAG'],
  questions: ['What is hybrid search?', 'What is a reranker in RAG?', 'How do I combine BM25 and vector search?', 'How do I improve RAG retrieval accuracy?', 'What is reciprocal rank fusion?'],
  pre: ['rag', 'embeddings', 'vector-databases'], rel: ['chunking', 'rag-evaluation', 'agentic-rag', 'graph-rag', 'vector-database-vs-traditional-database', 'pgvector'],
  vs: [['vector-database-vs-traditional-database', 'Hybrid search often needs both capabilities in one system or in two combined systems.']],
  tech: ['BM25 (Elasticsearch/OpenSearch/Lucene)', 'pgvector + full-text search', 'cross-encoder rerankers', 'ColBERT', 'rerank APIs'],
  patterns: ['Retrieve 50–100 candidates by both methods, fuse, rerank to top 5–10.', 'Metadata filters before scoring.', 'Query rewriting for ambiguous questions.', 'Cache embeddings and rerank results where sensible.'],
  fails: ['Unnormalised score mixing.', 'Reranker latency exceeding budget.', 'Retrieving too many candidates.', 'No evaluation to prove the gain.'],
  fix: [['Exact IDs/names not found', 'Add lexical search or boost exact matches.'], ['Latency too high', 'Reduce candidates reranked or use a smaller reranker.']],
  guide: ['Build a labelled retrieval set.', 'Measure vector-only baseline.', 'Add BM25 + fusion.', 'Add a reranker.', 'Track recall@k and latency.'],
  when: 'Use once simple vector retrieval misses exact terms or returns noisy top results.',
  sources: [['Karpukhin et al., Dense Passage Retrieval for Open-Domain QA (2020)', 'arXiv:2004.04906'], ['Khattab & Zaharia, ColBERT (2020)', 'arXiv:2004.12832'], ['Cormack, Clarke & Büttcher, Reciprocal rank fusion outperforms Condorcet and individual rank learning methods, SIGIR (2009)', null], ['Nogueira & Cho, Passage Re-ranking with BERT (2019)', 'arXiv:1901.04085']],
  fresh: 'evolving', keywords: ['BM25', 'rerank', 'retrieval']
}),

E('graph-rag', 'GraphRAG (Knowledge-Graph Retrieval)', 'technique', R, {
  summary: 'GraphRAG organises documents into a knowledge graph of entities and relationships, enabling retrieval and summarisation across connected information rather than isolated chunks.',
  short: 'GraphRAG **extracts entities and relationships into a graph**, often with community summaries, so questions needing multi-hop or corpus-wide synthesis can be answered. It costs more to build and maintain than chunk-based RAG.',
  plain: `Ordinary RAG fetches a few similar passages. Some questions need connections — "how are these people, projects and events related?" — or an overview of a whole collection. GraphRAG builds a map of entities and links first, then uses it to answer such questions.`,
  technical: `Microsoft Research\'s "From Local to Global" (Edge et al., 2024) describes building an entity graph from text with an LLM, detecting communities, pre-summarising them, and answering global questions via map-reduce over summaries; "GraphRAG" also denotes broader graph-based retrieval approaches (graph databases, multi-hop traversal). Costs include LLM extraction at index time, graph quality issues (entity resolution) and update complexity. Gains are task-specific and must be validated.`,
  aliases: ['GraphRAG', 'graph RAG', 'knowledge graph RAG', 'knowledge graphs for LLMs', 'multi-hop retrieval', 'community summaries', 'Neo4j RAG', 'entity relationship retrieval'],
  intents: ['answer multi-hop or corpus-wide questions', 'decide whether GraphRAG is worth the cost'],
  questions: ['What is GraphRAG?', 'GraphRAG vs vector RAG?', 'When do I need a knowledge graph for RAG?', 'How do I build a knowledge graph from documents?'],
  pre: ['rag', 'embeddings'], rel: ['graph-neural-networks', 'hybrid-search-and-reranking', 'agentic-rag', 'vector-databases', 'rag-evaluation'],
  vs: [['rag', 'Standard RAG retrieves similar chunks; GraphRAG retrieves connected structure and summaries.'], ['graph-neural-networks', 'GNNs are learned models over graphs; GraphRAG uses graph structure to organise LLM retrieval.']],
  tech: ['Microsoft GraphRAG', 'Neo4j', 'LlamaIndex property graphs', 'entity-resolution tooling'],
  patterns: ['Extract entities/relations with an LLM; resolve duplicates.', 'Community detection and summarisation for global questions.', 'Hybrid: vector retrieval for local questions, graph for global.', 'Cache or incrementally update the graph.'],
  fails: ['Extraction errors creating false relationships.', 'High indexing cost.', 'Stale graph after document updates.', 'Using it where plain RAG would do.'],
  fix: [['Wrong or duplicate entities', 'Improve entity resolution and prompts; audit samples.'], ['Cost too high', 'Limit to the document subsets that need graph answers.']],
  guide: ['Check if questions need synthesis or multi-hop reasoning.', 'Pilot on a subset.', 'Audit extracted graph quality.', 'Compare against hybrid RAG on your questions.'],
  when: 'Use for sensemaking over large corpora and relationship-heavy questions.',
  sources: [['Edge et al., From Local to Global: A Graph RAG Approach to Query-Focused Summarization (2024)', 'arXiv:2404.16130']],
  fresh: 'volatile', tsc: ['Tooling names, repository status and cost characteristics.'],
  keywords: ['knowledge graph', 'multi-hop', 'entities']
}),

E('agentic-rag', 'Agentic RAG (Adaptive and Self-Correcting Retrieval)', 'technique', R, {
  summary: 'Agentic RAG lets a model decide when and how to retrieve — rewriting queries, choosing sources, checking relevance and retrying — instead of a single fixed retrieve-then-generate pass.',
  short: 'The retrieval step becomes a **decision loop**: the model plans queries, calls search tools, grades what came back, and retries or stops. It handles complex questions better but costs more and adds failure modes; use it only where plain RAG falls short.',
  plain: `Basic RAG always searches once. Agentic RAG lets the AI act like a researcher: reword the question, try a different source, notice weak results and try again before answering.`,
  technical: `Patterns: query rewriting/decomposition, routing among indexes or tools, relevance grading with retry (Corrective RAG, Yan et al., 2024), self-reflective retrieval where the model decides when to retrieve (Self-RAG, Asai et al., 2023), and iterative multi-hop retrieval. It combines [[rag]] with [[react-agent-pattern]]. Extra LLM calls add latency and cost, and a mis-judging grader can discard good evidence.`,
  aliases: ['agentic RAG', 'self-RAG', 'corrective RAG', 'CRAG', 'adaptive RAG', 'iterative retrieval', 'multi-hop RAG', 'query decomposition', 'RAG agent', 'retrieval agent'],
  intents: ['handle complex multi-part questions', 'add self-checking to RAG'],
  questions: ['What is agentic RAG?', 'What is self-RAG?', 'When should RAG retrieve more than once?', 'How do I make RAG handle multi-hop questions?'],
  pre: ['rag', 'ai-agents', 'agent-tools'], rel: ['hybrid-search-and-reranking', 'graph-rag', 'rag-evaluation', 'react-agent-pattern', 'ai-hallucinations'],
  vs: [['rag', 'Standard RAG is one fixed retrieval pass; agentic RAG loops and adapts.'], ['react-agent-pattern', 'ReAct is the general loop; agentic RAG applies it to retrieval.']],
  tech: ['LangGraph', 'LlamaIndex agents', 'search tools', 'rerankers'],
  patterns: ['Rewrite → retrieve → grade → (retry | answer).', 'Router selects among vector, keyword and web search.', 'Decompose into sub-questions; answer; synthesise.', 'Hard cap on retrieval iterations.'],
  fails: ['Loops that never stop.', 'Grader errors discarding useful passages.', 'Latency and cost multiplication.', 'Injected instructions in retrieved text ([[prompt-injection]]).'],
  fix: [['Slow answers', 'Cap iterations, parallelise sub-queries, use a small grader model.'], ['Answers still ungrounded', 'Require citations and verify them against retrieved text.']],
  guide: ['Measure plain-RAG failures first.', 'Add the smallest loop that fixes them.', 'Limit iterations.', 'Evaluate end-to-end and retrieval separately.'],
  when: 'Use when single-pass retrieval fails on multi-hop or ambiguous questions.',
  sources: [['Asai et al., Self-RAG (2023)', 'arXiv:2310.11511'], ['Yan et al., Corrective Retrieval Augmented Generation (2024)', 'arXiv:2401.15884']],
  fresh: 'evolving', keywords: ['iterative', 'self-correction', 'query rewriting']
}),

E('context-engineering', 'Context Engineering', 'concept', R, {
  summary: 'Context engineering is deciding what goes into a model\'s context window — instructions, retrieved facts, tool results, memory, examples — and in what form, to make agents reliable.',
  short: 'Beyond writing a prompt, context engineering **curates everything the model sees each turn**: system instructions, relevant memory, retrieved documents, tool definitions and results, trimmed history. Less, better-organised context usually beats more.',
  plain: `A model only knows what's in front of it. Context engineering is the craft of putting the *right* information in front of it at the right time — and leaving the rest out — so it can do the job without being distracted or confused.`,
  technical: `The term gained currency in practitioner discussions in 2025 to describe the broader discipline around prompt engineering for agentic systems (verify provenance of the term if attributing it). Elements: instruction hierarchy ([[system-prompts]]), retrieval ([[rag]]), memory selection and summarisation ([[agent-memory]]), tool-set selection and result trimming ([[agent-tools]]), caching of stable prefixes ([[prompt-caching]]), and isolating sub-tasks into separate contexts ([[multi-agent-systems]]). Research on long-context use suggests models may use information unevenly across a long context, so organisation and pruning matter.`,
  aliases: ['context engineering', 'context management', 'context curation', 'context rot', 'managing context windows for agents', 'prompt vs context engineering', 'context pruning', 'context compaction'],
  intents: ['make long-running agents reliable', 'decide what to put in the prompt'],
  questions: ['What is context engineering?', 'How is context engineering different from prompt engineering?', 'How do I manage context for long-running agents?', 'What is context compaction?'],
  pre: ['prompt-engineering', 'context-windows'], rel: ['agent-memory', 'rag', 'prompt-caching', 'agent-tools', 'multi-agent-systems', 'chunking'],
  vs: [['prompt-engineering', 'Prompt engineering focuses on wording instructions; context engineering manages the whole information payload across turns.']],
  tech: ['retrieval pipelines', 'summarisation/compaction', 'prompt caching', 'tool-search/selection'],
  patterns: ['Keep stable instructions first; dynamic content later (cache-friendly).', 'Just-in-time retrieval instead of preloading.', 'Compact old turns into summaries; keep key decisions verbatim.', 'Offload large artefacts to files/stores and pass references.', 'Give each sub-agent a minimal context.'],
  fails: ['Dumping everything "to be safe".', 'Contradictory instructions across layers.', 'Stale summaries treated as fact.', 'Tool lists so long that selection degrades.', 'Sensitive data pulled into context unnecessarily.'],
  fix: [['Agent drifts on long tasks', 'Re-state the goal; compact history; keep a short task state.'], ['Quality drops as context grows', 'Prune irrelevant material; reorder; retrieve less but better.']],
  guide: ['Inventory what enters context each turn.', 'Remove what is not needed.', 'Order for clarity and caching.', 'Add compaction rules.', 'Test long-run behaviour ([[ai-evaluation]]).'],
  when: 'Central to building agents and RAG systems that stay reliable over many steps.',
  sources: [['Liu et al., Lost in the Middle: How Language Models Use Long Contexts (2023)', 'arXiv:2307.03172'], ['Practitioner and vendor guidance on context engineering (identify specific current articles; term provenance to verify)', null]],
  fresh: 'volatile', tsc: ['Provenance and exact definition of the term.', 'Provider-specific features such as context editing or memory tools.'],
  keywords: ['context window', 'compaction', 'curation'],
  tool: { id: 'ai-prompt-builder', note: `For the instruction part of your context, the **AI Prompt Builder** helps you organise role, request, context, process, tone and output into a clean prompt. It only structures prompt text — it does not manage retrieval, memory or tool results.` }
})
];
