import { E } from './entity-model.mjs';
const M = 'ML, Deep Learning & RL', A = 'Model Architectures';
const GBD = 'Goodfellow, Bengio & Courville, Deep Learning (MIT Press, 2016)';
export const entities = [
E('supervised-learning', 'Supervised Learning', 'concept', M, {
  summary: 'Supervised learning trains a model on labelled examples — inputs paired with the right answers — so it can predict answers for new inputs.',
  short: 'Supervised learning = **learn from labelled examples**. Classification predicts categories; regression predicts numbers. Quality depends on label quality, representative data and honest held-out evaluation.',
  plain: `You show a model many examples that already have the right answer — emails marked spam or not, houses with their sale prices — and it learns a rule that predicts the answer for new cases. "Supervised" refers to the answers acting as a teacher.`,
  technical: `Given a dataset of pairs (x, y) drawn from an unknown distribution, supervised learning fits a function f_θ by minimising an empirical loss (cross-entropy for classification, squared error for regression, etc.) plus optional regularisation, aiming to minimise expected loss on unseen data. Evaluation uses held-out validation and test splits; cross-validation helps with small datasets. Failure modes include label noise, distribution shift and leakage between train and test.`,
  aliases: ['supervised machine learning', 'classification and regression', 'labelled data learning', 'learning from labels', 'predictive modelling'],
  intents: ['understand the basic ML setup', 'choose between supervised and unsupervised learning', 'avoid train/test leakage'],
  questions: ['What is supervised learning?', 'What is the difference between classification and regression?', 'What is the difference between supervised and unsupervised learning?', 'How do I split data for training and testing?'],
  pre: ['what-is-ai'], rel: ['unsupervised-learning', 'self-supervised-learning', 'overfitting-and-regularization', 'neural-networks', 'transfer-learning', 'reinforcement-learning'],
  vs: [['unsupervised-learning', 'No labels; finds structure.'], ['reinforcement-learning', 'Learns from rewards after actions, not labelled answers.'], ['self-supervised-learning', 'Creates its own labels from the data.']],
  tech: ['scikit-learn', 'PyTorch', 'XGBoost / gradient boosting', 'pandas'],
  patterns: ['Split data into train / validation / test before any preprocessing that learns from data.', 'Start with a simple baseline (linear model, tree) before a neural network.', 'Track metrics suited to the problem (precision/recall for imbalance).', 'Use cross-validation for small datasets.'],
  fails: ['Data leakage: information from the test set influences training.', 'Label noise or inconsistent labelling.', 'Class imbalance hidden by accuracy.', 'Training data not representative of production inputs.'],
  fix: [['Great test score, poor production results', 'Check leakage and distribution shift between test and production data.'], ['Accuracy high but rare class missed', 'Use precision/recall/F1, resampling or class weights.'], ['Unstable results', 'Use cross-validation and fix random seeds for comparison.']],
  guide: ['Define the target and the metric.', 'Collect and clean labelled data; audit labels.', 'Split before preprocessing.', 'Train a baseline, then iterate.', 'Evaluate once on the held-out test set; monitor after launch ([[model-drift-and-monitoring]]).'],
  when: 'Use when you have (or can obtain) reliable labelled examples and a clear prediction target.',
  sources: [['Hastie, Tibshirani & Friedman, The Elements of Statistical Learning (2nd ed.)', 'hastie.su.domains/ElemStatLearn'], ['Bishop, Pattern Recognition and Machine Learning (2006)', null], ['scikit-learn user guide', 'scikit-learn.org']],
  fresh: 'stable', keywords: ['classification', 'regression', 'labels', 'train test split']
}),

E('unsupervised-learning', 'Unsupervised Learning', 'concept', M, {
  summary: 'Unsupervised learning finds structure in unlabelled data — clusters, patterns, compact representations — without being told the right answers.',
  short: 'Unsupervised learning looks for **structure without labels**: clustering, dimensionality reduction, density estimation, anomaly detection. Evaluation is harder because there is no single correct answer.',
  plain: `With no answer key, the model looks for patterns itself: groups of similar customers, unusual transactions, or a simpler way to represent complex data. Results need human interpretation — there's no label to score against.`,
  technical: `Tasks include clustering (k-means, hierarchical, DBSCAN, Gaussian mixtures), dimensionality reduction/visualisation (PCA, t-SNE, UMAP), density estimation and anomaly detection, and representation learning with autoencoders. Evaluation relies on internal criteria (silhouette, reconstruction error), downstream task performance, or expert review; different algorithms embed different assumptions about cluster shape and scale.`,
  aliases: ['clustering', 'k-means', 'dimensionality reduction', 'PCA', 'anomaly detection', 'unlabelled data learning', 'unsupervised machine learning'],
  intents: ['group similar items without labels', 'reduce data dimensions', 'detect unusual records'],
  questions: ['What is unsupervised learning?', 'How does k-means clustering work?', 'What is PCA used for?', 'How do I choose the number of clusters?'],
  pre: ['supervised-learning'], rel: ['self-supervised-learning', 'embeddings', 'variational-autoencoders', 'neural-networks'],
  vs: [['supervised-learning', 'Needs labels; has a defined target metric.'], ['self-supervised-learning', 'Uses data-derived labels to learn representations.']],
  tech: ['scikit-learn', 'UMAP', 'HDBSCAN', 'PyTorch autoencoders'],
  patterns: ['Scale features, then cluster.', 'Reduce with PCA before visualising with t-SNE/UMAP.', 'Cluster embeddings of text or images to explore a corpus.', 'Anomaly scoring with isolation forests or reconstruction error.'],
  fails: ['Unscaled features dominating distances.', 'Treating a visualisation as proof of real clusters.', 'Choosing k arbitrarily.', 'Clusters that are statistically fine but not useful.'],
  fix: [['Clusters look arbitrary', 'Scale features, try other algorithms, inspect samples per cluster.'], ['t-SNE plot changes each run', 'Fix seeds and treat distances in it as non-metric.']],
  guide: ['Clarify the question the structure should answer.', 'Clean and scale features.', 'Try more than one algorithm.', 'Inspect results by sampling.', 'Validate usefulness with a downstream task or expert.'],
  when: 'Use for exploration, segmentation, compression and anomaly detection when labels are unavailable.',
  sources: [['Hastie et al., The Elements of Statistical Learning, ch. 14', 'hastie.su.domains/ElemStatLearn'], ['scikit-learn clustering and decomposition guides', 'scikit-learn.org']],
  fresh: 'stable', keywords: ['clusters', 'structure', 'unlabelled']
}),

E('self-supervised-learning', 'Self-Supervised Learning', 'technique', M, {
  summary: 'Self-supervised learning creates its own training signal from raw data — predicting hidden words, masked patches or the next token — and is how most foundation models are pre-trained.',
  short: 'The model **learns by solving tasks made from the data itself** (predict the next token, fill in a masked word or patch). No human labels are needed, which makes training on huge corpora feasible.',
  plain: `Hide part of the data and ask the model to predict it: the next word in a sentence, a masked patch of an image. The data supplies its own answers, so you can learn from enormous unlabelled collections. This is how large language models are pre-trained.`,
  technical: `Pretext objectives include autoregressive next-token prediction (GPT-style), masked language modelling (BERT), masked autoencoding (MAE for images), and contrastive objectives ([[contrastive-learning-clip]]). The learned representations are then adapted by [[fine-tuning]] or used frozen. Quality depends on data scale, diversity and objective design.`,
  aliases: ['SSL', 'self supervised', 'pretext task', 'masked language modeling', 'masked language modelling', 'next token prediction pretraining', 'masked autoencoder'],
  intents: ['understand how foundation models are pre-trained', 'compare next-token and masked objectives'],
  questions: ['What is self-supervised learning?', 'How are LLMs trained without labels?', 'What is masked language modelling?', 'What is the difference between self-supervised and unsupervised learning?'],
  pre: ['supervised-learning', 'unsupervised-learning'], rel: ['large-language-models', 'transformers', 'contrastive-learning-clip', 'transfer-learning', 'scaling-laws', 'fine-tuning'],
  vs: [['unsupervised-learning', 'Unsupervised finds structure; self-supervised builds a prediction task from the data.'], ['supervised-learning', 'Supervised uses human labels.']],
  tech: ['BERT-style masking', 'GPT-style autoregression', 'MAE', 'SimCLR'],
  patterns: ['Pre-train on large unlabelled data, then fine-tune on small labelled data.', 'Use frozen self-supervised embeddings with a small classifier head.', 'Continue pre-training on domain text before task fine-tuning.'],
  fails: ['Pre-training data bias propagated downstream.', 'Pretext task mismatched to the downstream task.', 'Underestimating the compute and data needed.'],
  fix: [['Poor transfer to the target domain', 'Continue pre-training on domain data or fine-tune with more in-domain examples.'], ['Representations ignore needed features', 'Try a different objective or augmentations.']],
  guide: ['Choose a pre-trained model where possible instead of pre-training from scratch.', 'Match the pretext objective family to your modality.', 'Evaluate on your downstream task.', 'Check pre-training data licensing and bias.'],
  when: 'Relevant whenever you use or adapt foundation models; rarely something an application team trains from scratch.',
  sources: [['Devlin et al., BERT (2018)', 'arXiv:1810.04805'], ['He et al., Masked Autoencoders Are Scalable Vision Learners (2021)', 'arXiv:2111.06377'], ['Radford et al., Language Models are Unsupervised Multitask Learners (GPT-2, 2019)', null]],
  fresh: 'stable', keywords: ['pretraining', 'masked', 'next-token']
}),

E('neural-networks', 'Neural Networks', 'concept', M, {
  summary: 'A neural network is a model built from layers of simple numeric units whose connection strengths are learned from data. It is the foundation of deep learning.',
  short: 'A neural network stacks **layers of weighted sums plus non-linearities** and learns the weights by gradient descent. Depth and data let it learn complex patterns; it is a function approximator, not a brain.',
  plain: `Picture layers of simple calculators. Each takes numbers in, multiplies them by learned weights, adds them up and passes the result through a simple curve. Stack many layers and train the weights on examples, and the network can learn complex patterns like recognising faces or translating text.`,
  technical: `A feed-forward network computes h_{l+1} = σ(W_l h_l + b_l) for layers l, with non-linear activations σ (ReLU, GELU, etc.). Parameters are fitted by minimising a loss with gradients from [[backpropagation-and-gradient-descent]]. Universal-approximation results state that sufficiently wide networks can approximate broad function classes, but say nothing about learnability from finite data. Architectures specialise this template: [[convolutional-neural-networks]], [[recurrent-neural-networks]], [[transformers]], [[graph-neural-networks]].`,
  aliases: ['neural net', 'artificial neural network', 'ANN', 'multilayer perceptron', 'MLP', 'feedforward network', 'perceptron', 'activation function'],
  intents: ['learn the basics of neural networks', 'understand layers, weights and activations'],
  questions: ['What is a neural network?', 'How does a neural network learn?', 'What is an activation function?', 'What is a multilayer perceptron?'],
  pre: ['supervised-learning'], rel: ['deep-learning', 'backpropagation-and-gradient-descent', 'convolutional-neural-networks', 'transformers', 'overfitting-and-regularization'],
  vs: [['deep-learning', 'Deep learning means neural networks with many layers.'], ['supervised-learning', 'A learning setup, not a model type; neural nets are one model family used within it.']],
  tech: ['PyTorch', 'JAX', 'TensorFlow / Keras'],
  patterns: ['Start from a small MLP baseline for tabular data.', 'Normalise inputs; use standard initialisation and optimiser defaults.', 'Choose architecture by data type: images, sequences, graphs.', 'Use pre-trained networks when possible.'],
  fails: ['Overfitting small datasets.', 'Poor scaling or initialisation causing vanishing/exploding gradients.', 'Using a neural network where gradient-boosted trees would beat it on tabular data.', 'No baseline for comparison.'],
  fix: [['Loss is NaN', 'Lower learning rate; check input scaling and data for NaNs.'], ['Training loss does not decrease', 'Check labels, learning rate and that gradients flow; overfit a tiny batch first.']],
  guide: ['Overfit a tiny batch to verify the pipeline.', 'Scale inputs.', 'Pick a standard optimiser (Adam/AdamW) and learning rate sweep.', 'Monitor training vs validation loss.', 'Add regularisation as needed.'],
  when: 'Use for perception, language and other high-dimensional data; consider simpler models for small tabular datasets.',
  sources: [[GBD, 'deeplearningbook.org'], ['Zhang et al., Dive into Deep Learning', 'd2l.ai'], ['Cybenko, Approximation by superpositions of a sigmoidal function (1989)', null]],
  fresh: 'stable', keywords: ['layers', 'weights', 'activation']
}),

E('deep-learning', 'Deep Learning', 'concept', M, {
  summary: 'Deep learning is machine learning with neural networks that have many layers, learning useful features directly from raw data like pixels, audio and text.',
  short: 'Deep learning = **many-layer neural networks that learn their own features** from raw data. Its success rests on data, compute and architectures like CNNs and transformers; it needs more data and compute than classical ML.',
  plain: `Deep learning is the branch of machine learning that uses neural networks with many layers. Instead of an engineer hand-crafting features ("edges", "word counts"), the network learns them itself from raw pixels, sound or text. This is behind modern image recognition, speech and language models.`,
  technical: `Deep networks learn hierarchical representations; success on modern benchmarks has been enabled by large datasets, GPU/accelerator compute, better optimisation (Adam, normalisation layers, residual connections) and architectures suited to the data modality. LeCun, Bengio & Hinton (2015) give a canonical overview. Costs: data hunger, compute, limited interpretability and sensitivity to distribution shift.`,
  aliases: ['DL', 'deep neural networks', 'DNN', 'deep nets', 'deep learning explained', 'deep learning vs machine learning'],
  intents: ['understand how deep learning differs from classical ML', 'decide whether deep learning is needed'],
  questions: ['What is deep learning?', 'What is the difference between deep learning and machine learning?', 'When should I use deep learning instead of classical ML?', 'Why did deep learning take off?'],
  pre: ['neural-networks'], rel: ['backpropagation-and-gradient-descent', 'convolutional-neural-networks', 'transformers', 'transfer-learning', 'gpus-and-ai-accelerators', 'what-is-ai'],
  vs: [['what-is-ai', 'AI is the broad field; deep learning is one family of methods inside machine learning.'], ['supervised-learning', 'Learning paradigm; deep learning is a model family usable in several paradigms.']],
  tech: ['PyTorch', 'JAX', 'TensorFlow', 'CUDA'],
  patterns: ['Use pre-trained backbones and fine-tune.', 'Mixed-precision training on GPUs.', 'Residual connections and normalisation layers for depth.', 'Data augmentation for perception tasks.'],
  fails: ['Training from scratch on tiny data.', 'Ignoring simpler baselines.', 'Irreproducible results from uncontrolled randomness.', 'Silent failure under distribution shift.'],
  fix: [['Model overfits', 'More data/augmentation, regularisation, smaller model or pre-trained start.'], ['Training too slow', 'Use mixed precision, bigger batches, better data loading, or smaller models.']],
  guide: ['Establish a classical-ML baseline.', 'Choose a pre-trained model for your modality.', 'Fine-tune with a small learning rate.', 'Evaluate on held-out data with realistic shifts.', 'Plan serving cost ([[model-serving-and-inference]]).'],
  when: 'Use for images, audio, language and other unstructured data, or when pre-trained models can be adapted.',
  sources: [['LeCun, Bengio & Hinton, Deep learning, Nature 521 (2015)', 'doi:10.1038/nature14539'], [GBD, 'deeplearningbook.org']],
  fresh: 'stable', keywords: ['representation learning', 'layers']
}),

E('backpropagation-and-gradient-descent', 'Backpropagation and Gradient Descent', 'technique', M, {
  summary: 'Gradient descent adjusts a model\'s parameters in the direction that reduces loss; backpropagation is the efficient way to compute those gradients through a neural network.',
  short: 'Training = **repeat: compute loss, backpropagate gradients, nudge parameters downhill**. Learning rate, batch size and optimiser choice (SGD, Adam/AdamW) control speed and stability.',
  plain: `To learn, a network measures how wrong it is (the loss), works out how each weight contributed to that error (backpropagation) and nudges each weight slightly to reduce it (gradient descent). Repeat millions of times.`,
  technical: `Backpropagation applies the chain rule to compute ∂L/∂θ for all parameters in one backward pass. Optimisers: SGD with momentum, RMSProp, Adam (Kingma & Ba, 2014), AdamW (decoupled weight decay). Practical elements: learning-rate schedules and warm-up, gradient clipping, mini-batching, normalisation layers (batch/layer norm), mixed precision. Pathologies: vanishing/exploding gradients, saddle points, poor conditioning.`,
  aliases: ['backprop', 'gradient descent', 'SGD', 'stochastic gradient descent', 'Adam optimizer', 'AdamW', 'learning rate', 'loss function', 'training loop', 'optimizer'],
  intents: ['understand how neural networks are trained', 'tune learning rate and optimiser', 'debug training that will not converge'],
  questions: ['What is backpropagation?', 'What is gradient descent?', 'How do I choose a learning rate?', 'Why is my loss not decreasing?', 'What is the difference between SGD and Adam?'],
  pre: ['neural-networks'], rel: ['deep-learning', 'overfitting-and-regularization', 'distributed-training', 'proximal-policy-optimization', 'transfer-learning'],
  vs: [['reinforcement-learning', 'RL gets gradient estimates from reward feedback (e.g. policy gradients), not directly from labelled targets.']],
  tech: ['PyTorch autograd', 'JAX grad', 'optimizers: Adam, AdamW, SGD'],
  patterns: ['Learning-rate warm-up + cosine/linear decay.', 'Gradient clipping for stability.', 'Overfit one batch as a sanity test.', 'Log training and validation loss together.'],
  fails: ['Learning rate too high (diverges) or too low (stalls).', 'Forgetting to zero gradients or switch eval/train mode.', 'Exploding gradients in deep or recurrent nets.', 'Data/label bugs mistaken for optimisation problems.'],
  fix: [['Loss is NaN or spikes', 'Lower learning rate, clip gradients, check inputs for NaN/inf.'], ['Loss flat from the start', 'Check labels, learning rate, initialisation and that parameters are in the optimiser.']],
  guide: ['Run the one-batch overfit test.', 'Sweep learning rate on a log scale.', 'Add schedule and clipping.', 'Track gradient norms.', 'Scale up only after small runs behave.'],
  when: 'Needed knowledge for anyone training or fine-tuning neural networks.',
  sources: [['Rumelhart, Hinton & Williams, Learning representations by back-propagating errors, Nature (1986)', 'doi:10.1038/323533a0'], ['Kingma & Ba, Adam: A Method for Stochastic Optimization (2014)', 'arXiv:1412.6980'], ['Loshchilov & Hutter, Decoupled Weight Decay Regularization (2017)', 'arXiv:1711.05101']],
  fresh: 'stable', keywords: ['optimizer', 'gradient', 'loss', 'training']
}),

E('overfitting-and-regularization', 'Overfitting and Regularization', 'concept', M, {
  summary: 'Overfitting is when a model memorises training data and fails on new data. Regularisation, more data, early stopping and simpler models reduce it.',
  short: 'If **training performance is great but validation performance is poor**, the model is overfitting. Remedies: more or better data, augmentation, regularisation (weight decay, dropout), early stopping, simpler models.',
  plain: `A student who memorises past exam answers can ace those exams and fail new ones. A model that memorises its training data does the same. Regularisation is the set of tricks that discourage memorising and encourage learning general patterns.`,
  technical: `Overfitting reflects variance: low training error, high generalisation error. Diagnose with learning curves and validation metrics. Mitigations: more data, data augmentation, L2/weight decay, dropout (Srivastava et al., 2014), early stopping, model capacity reduction, ensembling, label smoothing, cross-validation for model selection. The opposite failure, underfitting, shows high error on both sets. Note that very large models can generalise well despite interpolating training data, so capacity alone does not determine overfitting.`,
  aliases: ['overfitting', 'underfitting', 'regularisation', 'regularization', 'dropout', 'weight decay', 'early stopping', 'bias variance tradeoff', 'generalization', 'generalisation', 'model memorizing training data'],
  intents: ['diagnose poor generalisation', 'choose regularisation techniques'],
  questions: ['What is overfitting?', 'How do I prevent overfitting?', 'What is dropout?', 'What is the bias-variance tradeoff?', 'Why does my model perform well on training but not test data?'],
  pre: ['supervised-learning', 'neural-networks'], rel: ['backpropagation-and-gradient-descent', 'transfer-learning', 'ai-evaluation', 'deep-learning'],
  vs: [['transfer-learning', 'Starting from pre-trained weights is itself a strong regulariser for small datasets.']],
  tech: ['scikit-learn', 'PyTorch dropout', 'weight decay in AdamW', 'Albumentations (augmentation)'],
  patterns: ['Learning curves: plot train vs validation metric over data size and epochs.', 'Early stopping on validation loss.', 'Augmentation for images/audio.', 'Cross-validation for model selection on small data.'],
  fails: ['Tuning on the test set, overfitting to it indirectly.', 'Leakage that makes validation look good.', 'Too much regularisation causing underfitting.', 'Ignoring distribution shift between validation and real use.'],
  fix: [['Validation loss rising while training loss falls', 'Stop earlier, add regularisation or data.'], ['Both losses high', 'Underfitting: increase capacity, train longer, improve features.']],
  guide: ['Hold out validation and test sets properly.', 'Plot learning curves.', 'Add one regularisation measure at a time.', 'Use the test set once at the end.', 'Re-check after deployment ([[model-drift-and-monitoring]]).'],
  when: 'Always relevant when training; central to small-data work.',
  sources: [['Srivastava et al., Dropout: A Simple Way to Prevent Neural Networks from Overfitting, JMLR (2014)', null], ['Hastie et al., The Elements of Statistical Learning, ch. 7', 'hastie.su.domains/ElemStatLearn']],
  fresh: 'stable', keywords: ['generalization', 'variance', 'validation']
}),

E('transfer-learning', 'Transfer Learning', 'technique', M, {
  summary: 'Transfer learning reuses a model pre-trained on a large task as the starting point for a new, smaller one, saving data and compute.',
  short: 'Start from a **pre-trained model** and adapt it to your task (feature extraction or fine-tuning). It usually beats training from scratch when your data is limited and the domains are related.',
  plain: `Instead of teaching a model from zero, borrow one that already learned general skills — recognising shapes, understanding language — and teach it your specific task. It needs far less data and time.`,
  technical: `Approaches: use the pre-trained model as a frozen feature extractor with a new head; fine-tune all or some layers; parameter-efficient methods ([[lora-and-peft]]); continued pre-training on domain data. Yosinski et al. (2014) studied transferability of features by layer. Negative transfer can occur when source and target are very different; catastrophic forgetting can erase general abilities if fine-tuning is aggressive.`,
  aliases: ['pretrained models', 'pre-trained model fine-tuning', 'feature extraction', 'domain adaptation', 'ImageNet pretrained', 'catastrophic forgetting', 'warm start'],
  intents: ['adapt a pre-trained model to my data', 'decide between freezing and fine-tuning'],
  questions: ['What is transfer learning?', 'Should I freeze layers when fine-tuning?', 'What is catastrophic forgetting?', 'How much data do I need to fine-tune a pre-trained model?'],
  pre: ['neural-networks', 'self-supervised-learning'], rel: ['fine-tuning', 'lora-and-peft', 'overfitting-and-regularization', 'deep-learning', 'hugging-face'],
  vs: [['fine-tuning', 'Fine-tuning is the most common form of transfer learning for language models.']],
  tech: ['Hugging Face Hub', 'PyTorch / torchvision', 'timm'],
  patterns: ['Freeze backbone, train head first; then unfreeze with a small learning rate.', 'Use domain-specific pre-trained models when available.', 'LoRA for large models.', 'Evaluate for forgetting on a general benchmark.'],
  fails: ['Source domain too different from target.', 'Fine-tuning learning rate too high.', 'Preprocessing mismatch with the pre-trained model.', 'Ignoring licence terms of the pre-trained model.'],
  fix: [['Accuracy collapses after fine-tuning', 'Lower learning rate, freeze early layers, mix in general data.'], ['Poor results immediately', 'Match tokenizer/normalisation/preprocessing to the pre-trained model.']],
  guide: ['Pick a pre-trained model close to your domain.', 'Check licence.', 'Replicate its preprocessing.', 'Train the head, then unfreeze gradually.', 'Compare with a from-scratch baseline.'],
  when: 'Default approach for images, text and audio when data is limited.',
  sources: [['Yosinski et al., How transferable are features in deep neural networks? (2014)', 'arXiv:1411.1792'], ['Pan & Yang, A Survey on Transfer Learning, IEEE TKDE (2010)', null]],
  fresh: 'stable', keywords: ['pretrained', 'adaptation']
}),

E('reinforcement-learning', 'Reinforcement Learning', 'concept', M, {
  summary: 'Reinforcement learning trains an agent to choose actions in an environment to maximise cumulative reward through trial and feedback.',
  short: 'RL = **an agent acts, gets rewards, and learns a policy that maximises long-term reward**. It handles sequential decisions (games, robotics, control) but is data-hungry and sensitive to reward design. Preference methods like DPO are not standard RL.',
  plain: `Learn by doing: an agent tries actions, receives rewards or penalties, and gradually learns which actions lead to the best long-term outcome — like training a dog with treats, or a program learning chess by playing itself.`,
  technical: `Formalised as a Markov decision process ([[markov-decision-processes]]): states, actions, transition dynamics, rewards and discount factor. Goals: learn a policy π(a|s) maximising expected return. Families: value-based (Q-learning, [[deep-q-networks]]), policy-gradient and actor-critic ([[proximal-policy-optimization]]), model-based RL ([[world-models]]), offline RL, imitation/inverse RL. Key difficulties: exploration versus exploitation, credit assignment over long horizons, sample efficiency, reward specification ([[reward-hacking]]) and stability. Methods that optimise directly on preference pairs without a sampled-reward RL loop, such as [[dpo]], belong to [[preference-optimization]] rather than ordinary RL.`,
  aliases: ['RL', 'reinforcement learning basics', 'policy', 'reward function', 'agent environment reward', 'exploration vs exploitation', 'deep reinforcement learning', 'deep RL'],
  intents: ['understand RL basics', 'distinguish RL from supervised learning and from preference optimisation'],
  questions: ['What is reinforcement learning?', 'How is RL different from supervised learning?', 'What is exploration vs exploitation?', 'How does reinforcement learning differ from preference optimization?'],
  pre: ['supervised-learning'], rel: ['markov-decision-processes', 'deep-q-networks', 'proximal-policy-optimization', 'reinforcement-learning-for-reasoning', 'rlhf', 'preference-optimization', 'world-models', 'imitation-learning'],
  vs: [['supervised-learning', 'Supervised learns from labelled answers; RL learns from delayed reward after actions.'], ['dpo', 'DPO optimises a policy on preference pairs with a supervised-style loss; it is preference optimisation, not an RL sampling loop.'], ['imitation-learning', 'Imitation learns from demonstrations rather than rewards.']],
  tech: ['Gymnasium', 'Stable-Baselines3', 'RLlib (Ray)', 'TRL'],
  patterns: ['Simulate first: train in simulation before real systems.', 'Reward shaping with care and audits.', 'Use proven algorithms (PPO, SAC, DQN) before inventing new ones.', 'Evaluate across many seeds.'],
  fails: ['Reward hacking and unintended behaviour.', 'High variance across random seeds.', 'Poor sample efficiency making real-world training impractical.', 'Training/evaluation environment mismatch.'],
  fix: [['Agent finds a loophole', 'Audit the reward; add constraints and held-out evaluation.'], ['Learning unstable', 'Use established implementations, tune learning rate/advantage normalisation, check seeds.']],
  guide: ['Define states, actions and reward precisely.', 'Build or pick a simulator.', 'Start with a standard algorithm.', 'Log returns over many seeds.', 'Test on perturbed environments before deployment.'],
  when: 'Use when decisions are sequential and feedback is delayed and a simulator or safe trial-and-error exists.',
  sources: [['Sutton & Barto, Reinforcement Learning: An Introduction (2nd ed., 2018)', 'incompleteideas.net/book'], ['Mnih et al., Human-level control through deep reinforcement learning, Nature (2015)', 'doi:10.1038/nature14236']],
  fresh: 'stable', keywords: ['policy', 'reward', 'agent', 'environment']
}),

E('markov-decision-processes', 'Markov Decision Processes', 'concept', M, {
  summary: 'A Markov decision process is the mathematical framework for sequential decision-making under uncertainty that underlies reinforcement learning.',
  short: 'An MDP = **states, actions, transition probabilities, rewards and a discount factor**, with the Markov property: the next state depends only on the current state and action. Solving it means finding a policy with maximum expected return.',
  plain: `An MDP is the rulebook for a decision game: where you can be (states), what you can do (actions), what happens as a result (probabilistic transitions), and what you earn (rewards). The goal is a plan that earns the most over time.`,
  technical: `Tuple (S, A, P, R, γ). Value functions V^π(s) and Q^π(s,a) satisfy Bellman equations; optimal policies satisfy Bellman optimality. Exact methods (value/policy iteration) need a known model and small state spaces; RL estimates from samples. Partial observability generalises to POMDPs. Real systems often violate the Markov assumption unless the state includes sufficient history.`,
  aliases: ['MDP', 'Bellman equation', 'POMDP', 'value function', 'Q function', 'markov property', 'discount factor', 'policy and value'],
  intents: ['learn the formal basis of RL', 'model a sequential decision problem'],
  questions: ['What is a Markov decision process?', 'What is the Bellman equation?', 'What is the difference between an MDP and a POMDP?', 'What is a value function?'],
  pre: ['reinforcement-learning'], rel: ['deep-q-networks', 'proximal-policy-optimization', 'world-models', 'agentic-workflows'],
  vs: [['reinforcement-learning', 'RL is the learning problem; an MDP is the mathematical model it is usually posed in.']],
  tech: ['Gymnasium environments', 'dynamic programming', 'POMDP solvers'],
  patterns: ['Encode history in the state when the environment is partially observable.', 'Model the reward carefully.', 'Use value iteration on small known models.'],
  fails: ['State omits information needed to be Markov.', 'Discount factor poorly chosen.', 'Reward misses the true objective.'],
  fix: [['Policy behaves inconsistently', 'Add history or memory to the state.'], ['Agent myopic or reckless', 'Revisit discount factor and reward design.']],
  guide: ['List states, actions, rewards.', 'Check whether the state is sufficient.', 'Choose exact or sample-based solving.', 'Verify with a simple case you can compute by hand.'],
  when: 'Foundational for designing or analysing RL problems.',
  sources: [['Sutton & Barto, Reinforcement Learning: An Introduction (2nd ed., 2018)', 'incompleteideas.net/book'], ['Puterman, Markov Decision Processes (1994)', null]],
  fresh: 'stable', keywords: ['bellman', 'state', 'action', 'transition']
}),

E('proximal-policy-optimization', 'Proximal Policy Optimization (PPO)', 'technique', M, {
  summary: 'PPO is a widely used policy-gradient reinforcement-learning algorithm that limits how far each update can move the policy, for stable training.',
  short: 'PPO is an **actor-critic policy-gradient method** that uses a clipped objective (or KL control) to keep updates small and training stable. It has been used for games, robotics and in RLHF pipelines.',
  plain: `PPO teaches an agent by repeatedly trying behaviours and nudging its policy toward those that earned more reward — but it refuses to change too much at once, which keeps learning from going off the rails. It is a workhorse algorithm in RL.`,
  technical: `PPO (Schulman et al., 2017) optimises a clipped surrogate objective on the probability ratio between new and old policies, using advantage estimates (typically GAE) from a learned value function, and multiple epochs of minibatch updates per batch of on-policy data. In RLHF it optimises a policy against a learned reward model with a KL penalty to a reference model. Practical stability depends on many implementation details (advantage normalisation, value clipping, learning-rate schedules).`,
  aliases: ['PPO', 'proximal policy optimisation', 'clipped surrogate objective', 'actor critic', 'policy gradient', 'TRPO', 'GAE'],
  intents: ['understand the algorithm used in RLHF', 'choose an RL algorithm', 'compare PPO and GRPO'],
  questions: ['What is PPO?', 'How does PPO work in RLHF?', 'What is a policy gradient?', 'What is the difference between PPO and DPO?', 'What is an actor-critic?'],
  pre: ['reinforcement-learning', 'backpropagation-and-gradient-descent'], rel: ['rlhf', 'reinforcement-learning-for-reasoning', 'deep-q-networks', 'reward-hacking', 'dpo'],
  vs: [['dpo', 'PPO is online RL with a reward model and sampling; DPO trains directly on preference pairs without sampling or a separate reward model.'], ['deep-q-networks', 'DQN is value-based for discrete actions; PPO is policy-based and handles continuous actions.']],
  tech: ['Stable-Baselines3', 'TRL', 'OpenRLHF', 'RLlib'],
  patterns: ['Collect on-policy rollouts, compute advantages, update with clipped objective for a few epochs.', 'KL penalty against a reference model in RLHF.', 'Normalise advantages and observations.', 'Evaluate on held-out environments or prompts.'],
  fails: ['Sensitive to implementation details and hyperparameters.', 'Reward hacking against the reward model.', 'Memory and compute heavy in LLM RLHF (policy, reference, reward and value models).', 'Instability from poor KL control.'],
  fix: [['Reward rises, human quality falls', 'Increase KL penalty, refresh the reward model, audit samples.'], ['Training diverges', 'Lower learning rate, check advantage normalisation, use known-good implementation settings.']],
  guide: ['Use a vetted implementation.', 'Reproduce a known baseline first.', 'Log KL, reward, entropy and value loss.', 'Inspect generations regularly in RLHF.'],
  when: 'Consider for continuous-control RL or when online RL against a reward signal is required; for preference alignment consider [[preference-optimization]] methods first.',
  sources: [['Schulman et al., Proximal Policy Optimization Algorithms (2017)', 'arXiv:1707.06347'], ['Ouyang et al., Training language models to follow instructions with human feedback (2022)', 'arXiv:2203.02155']],
  fresh: 'evolving', keywords: ['clipping', 'advantage', 'policy']
}),

E('deep-q-networks', 'Deep Q-Networks (DQN) and Q-Learning', 'technique', M, {
  summary: 'Q-learning learns the value of taking each action in each state; DQN uses a neural network to do this from raw inputs such as game pixels.',
  short: 'Q-learning estimates **expected return for each (state, action)** and acts greedily on it. DQN adds a neural network, experience replay and a target network to make this work on high-dimensional inputs with discrete actions.',
  plain: `Q-learning keeps a score for every action in every situation: "if I'm here and do this, how good will things turn out?" DQN replaces the giant lookup table with a neural network, which let a single system learn to play many Atari games from the screen pixels.`,
  technical: `Q-learning (Watkins & Dayan, 1992) updates Q(s,a) toward r + γ max_a' Q(s',a'). DQN (Mnih et al., 2015) stabilises deep Q-learning with experience replay and a periodically updated target network; extensions include Double DQN, dueling networks, prioritised replay and Rainbow. It suits discrete action spaces; continuous control typically uses actor-critic methods.`,
  aliases: ['DQN', 'Q-learning', 'Q learning', 'deep Q network', 'experience replay', 'target network', 'value-based RL'],
  intents: ['understand value-based RL', 'choose between DQN and policy methods'],
  questions: ['What is Q-learning?', 'What is a Deep Q-Network?', 'What is experience replay?', 'When should I use DQN vs PPO?'],
  pre: ['markov-decision-processes', 'reinforcement-learning'], rel: ['proximal-policy-optimization', 'world-models', 'deep-learning'],
  vs: [['proximal-policy-optimization', 'PPO learns a policy directly and handles continuous actions; DQN learns action values for discrete actions.']],
  tech: ['Stable-Baselines3', 'Gymnasium / Atari', 'RLlib'],
  patterns: ['Replay buffer with random minibatches.', 'Target network updated slowly.', 'ε-greedy exploration with decay.', 'Double DQN to reduce overestimation.'],
  fails: ['Overestimation bias.', 'Instability without replay/target networks.', 'Poor exploration in sparse-reward tasks.', 'Applying it to continuous actions without adaptation.'],
  fix: [['Q-values explode', 'Use Double DQN, gradient clipping, reward clipping/normalisation.'], ['No learning in sparse rewards', 'Better exploration, reward shaping or curriculum.']],
  guide: ['Check actions are discrete.', 'Use a vetted implementation.', 'Tune replay size, target update rate, ε schedule.', 'Evaluate across seeds.'],
  when: 'Use for discrete-action problems such as games and some operations tasks.',
  sources: [['Mnih et al., Human-level control through deep reinforcement learning, Nature (2015)', 'doi:10.1038/nature14236'], ['Watkins & Dayan, Q-learning, Machine Learning (1992)', null]],
  fresh: 'stable', keywords: ['value function', 'atari', 'replay']
}),

// -------- Architectures --------
E('convolutional-neural-networks', 'Convolutional Neural Networks (CNNs)', 'concept', A, {
  summary: 'CNNs process grid-like data such as images by sliding small learned filters across it, capturing local patterns with far fewer parameters than fully connected nets.',
  short: 'A CNN uses **convolutions with shared filters, pooling and depth** to build up from edges to objects. It exploits locality and translation structure in images; vision transformers now compete with and sometimes replace it.',
  plain: `A CNN looks at an image through small windows, learning filters that detect edges, textures and then shapes. Because the same filter slides across the whole image, it needs far fewer weights and recognises a pattern wherever it appears.`,
  technical: `Convolutional layers compute local, weight-shared linear filters followed by non-linearities, often with pooling or strided convolutions and normalisation; residual connections (ResNet, He et al., 2015) enable very deep networks. Inductive biases (locality, translation equivariance) make CNNs data-efficient on images. They are also used for audio spectrograms and 1-D signals. Competing/complementary designs include [[vision-transformers]] and hybrids.`,
  aliases: ['CNN', 'ConvNet', 'convolution', 'ResNet', 'AlexNet', 'image classification network', 'convolutional network', 'pooling layer', 'filters kernels'],
  intents: ['understand image-model basics', 'choose between CNN and ViT'],
  questions: ['What is a convolutional neural network?', 'How do CNNs work?', 'What is a convolution in deep learning?', 'Are CNNs obsolete because of transformers?'],
  pre: ['neural-networks'], rel: ['vision-transformers', 'cnn-vs-vision-transformer', 'deep-learning', 'transfer-learning', 'multimodal-ai'],
  vs: [['vision-transformers', 'ViT splits images into patches and uses attention; CNNs use local filters with built-in spatial bias.'], ['recurrent-neural-networks', 'RNNs process sequences step by step; CNNs process grids/windows in parallel.']],
  tech: ['PyTorch / torchvision', 'ResNet', 'EfficientNet', 'ConvNeXt'],
  patterns: ['Pre-trained backbone + task head.', 'Data augmentation (crop, flip, colour jitter).', 'Residual connections.', 'Mixed precision on GPUs.'],
  fails: ['Overfitting small image sets.', 'Sensitivity to distribution shift (lighting, camera).', 'Shortcut learning on background cues.', 'Inappropriate input resizing.'],
  fix: [['Great on validation, poor in the field', 'Collect field-like data; augment; test on shifted sets.'], ['Model focuses on background', 'Rebalance data; use saliency checks.']],
  guide: ['Start from a pre-trained backbone.', 'Match preprocessing to it.', 'Fine-tune with a small learning rate.', 'Test on realistic shifted data.'],
  when: 'Strong default for image tasks, especially with limited data or compute.',
  sources: [['LeCun et al., Gradient-based learning applied to document recognition, Proc. IEEE (1998)', null], ['He et al., Deep Residual Learning for Image Recognition (2015)', 'arXiv:1512.03385'], ['Krizhevsky, Sutskever & Hinton, ImageNet Classification with Deep CNNs (NeurIPS 2012)', null]],
  fresh: 'stable', keywords: ['image', 'filters', 'vision']
}),

E('recurrent-neural-networks', 'Recurrent Neural Networks and LSTMs', 'concept', A, {
  summary: 'RNNs process sequences one step at a time while carrying a hidden state; LSTMs and GRUs add gates to remember longer. Transformers have largely replaced them for language.',
  short: 'RNNs keep a **hidden state that is updated step by step**. LSTM/GRU gates ease the vanishing-gradient problem. They are sequential (hard to parallelise) and have been largely superseded by transformers and, for some uses, state-space models.',
  plain: `A recurrent network reads a sequence one item at a time, carrying a "memory" forward. LSTMs add control gates that decide what to keep or forget, so they remember longer. Today most language models use transformers instead, because they train much faster in parallel.`,
  technical: `Vanilla RNN: h_t = f(W h_{t-1} + U x_t). Backpropagation through time suffers vanishing/exploding gradients. LSTM (Hochreiter & Schmidhuber, 1997) uses input/forget/output gates and a cell state; GRU (Cho et al., 2014) simplifies the gating. Sequential dependence limits training parallelism; attention (Bahdanau et al., 2014) and then transformers addressed both long-range dependence and parallelism. Recent [[state-space-models]] and linear-recurrent designs revisit recurrence with parallel training.`,
  aliases: ['RNN', 'LSTM', 'GRU', 'long short-term memory', 'gated recurrent unit', 'sequence model', 'vanishing gradient', 'seq2seq', 'backpropagation through time'],
  intents: ['understand pre-transformer sequence models', 'decide if an RNN is still appropriate'],
  questions: ['What is an RNN?', 'What is an LSTM?', 'Why did transformers replace RNNs?', 'What is the vanishing gradient problem?'],
  pre: ['neural-networks', 'backpropagation-and-gradient-descent'], rel: ['transformers', 'state-space-models', 'transformers-vs-state-space-models', 'encoder-decoder-vs-decoder-only'],
  vs: [['transformers', 'Transformers use attention over all positions and parallel training; RNNs are sequential.'], ['state-space-models', 'SSMs revive recurrence with structures that train in parallel.']],
  tech: ['PyTorch nn.LSTM / nn.GRU', 'TensorFlow / Keras'],
  patterns: ['Gradient clipping.', 'Bidirectional encoders for classification.', 'Small LSTMs for on-device time-series with tight memory.', 'Encoder–decoder with attention for legacy seq2seq.'],
  fails: ['Vanishing/exploding gradients on long sequences.', 'Slow training due to sequential computation.', 'Limited long-range memory despite gating.', 'Padding/masking bugs.'],
  fix: [['Cannot learn long dependencies', 'Use LSTM/GRU with clipping, or move to attention-based models.'], ['Training slow', 'Use larger batches and cuDNN kernels, or switch architecture.']],
  guide: ['Ask whether a pre-trained transformer is available.', 'If recurrent, use LSTM/GRU, clip gradients.', 'Mask padding.', 'Benchmark against a simple baseline.'],
  when: 'Still reasonable for small streaming/time-series tasks; for language prefer transformers.',
  sources: [['Hochreiter & Schmidhuber, Long Short-Term Memory, Neural Computation (1997)', null], ['Cho et al., Learning Phrase Representations using RNN Encoder–Decoder (2014)', 'arXiv:1406.1078'], ['Bahdanau et al., Neural Machine Translation by Jointly Learning to Align and Translate (2014)', 'arXiv:1409.0473']],
  fresh: 'stable', keywords: ['sequence', 'hidden state', 'gates']
}),

E('vision-transformers', 'Vision Transformers (ViT)', 'model', A, {
  summary: 'Vision Transformers split an image into patches and process them with transformer attention, matching or beating CNNs at scale.',
  short: 'ViT cuts an image into **patches treated like tokens** and runs a standard transformer. It needs large-scale pre-training to shine and underlies many multimodal models.',
  plain: `Instead of sliding filters over an image, a Vision Transformer chops it into small squares ("patches"), treats each like a word, and lets attention work out how the patches relate. Given enough training data it performs very well and forms the visual half of many multimodal AI systems.`,
  technical: `ViT (Dosovitskiy et al., 2020) linearly embeds fixed-size patches, adds position embeddings and a class token, and applies transformer encoder layers. Lacking CNN inductive biases, it generally needs large datasets or strong augmentation/distillation to match CNNs on smaller data. Variants: Swin (shifted windows), DeiT (data-efficient training), and use as image encoders in [[contrastive-learning-clip]] and [[vision-language-models]]. Cost grows quadratically with patch count.`,
  aliases: ['ViT', 'vision transformer', 'image transformer', 'patch embedding', 'Swin transformer', 'DeiT', 'transformers for images'],
  intents: ['understand how transformers handle images', 'choose an image backbone'],
  questions: ['What is a Vision Transformer?', 'How does ViT work?', 'ViT vs CNN: which is better?', 'Why do vision transformers need so much data?'],
  pre: ['transformers', 'convolutional-neural-networks'], rel: ['cnn-vs-vision-transformer', 'vision-language-models', 'contrastive-learning-clip', 'multimodal-ai', 'transfer-learning'],
  vs: [['convolutional-neural-networks', 'CNNs build in locality; ViT learns spatial relations from data.']],
  tech: ['Hugging Face Transformers', 'timm', 'PyTorch'],
  patterns: ['Use a pre-trained ViT backbone with a task head.', 'Larger patch size to cut compute.', 'Hierarchical/windowed variants for dense tasks.', 'ViT as the image encoder in a VLM.'],
  fails: ['Overfitting when trained from scratch on small data.', 'High memory at high resolution.', 'Resolution mismatch with pre-training position embeddings.', 'Ignoring licence of pre-trained weights.'],
  fix: [['Poor accuracy on small dataset', 'Fine-tune a pre-trained ViT or use a CNN.'], ['Out of memory', 'Lower resolution, larger patches, gradient checkpointing, or windowed variants.']],
  guide: ['Pick a pre-trained checkpoint.', 'Match input resolution/normalisation.', 'Fine-tune with small LR and layer-wise decay.', 'Compare against a CNN baseline.'],
  when: 'Use with pre-trained weights for classification, detection and as visual encoders in multimodal systems.',
  sources: [['Dosovitskiy et al., An Image is Worth 16x16 Words (2020)', 'arXiv:2010.11929'], ['Liu et al., Swin Transformer (2021)', 'arXiv:2103.14030']],
  fresh: 'evolving', keywords: ['patches', 'image encoder']
}),

E('cnn-vs-vision-transformer', 'CNN vs Vision Transformer', 'concept', A, {
  page_kind: 'comparison',
  summary: 'CNNs bake in image structure and are data- and compute-efficient; Vision Transformers learn it and scale well with data. Pre-trained availability often decides.',
  short: '**CNN**: strong inductive bias, efficient on small/medium data and edge devices. **ViT**: scales with data and unifies with language/multimodal models. In practice choose the best pre-trained backbone for your task and constraints, and measure.',
  plain: `Both recognise images. CNNs have image structure built in, so they learn well from less data and run efficiently on small devices. ViTs are more general and improve strongly with huge data and model size.`,
  technical: `| | CNN | Vision Transformer |\n|---|---|---|\n| Inductive bias | Locality, translation equivariance | Minimal; learned via attention |\n| Data need | Lower | Higher unless pre-trained |\n| Compute scaling | Linear in pixels | Quadratic in patches (mitigated by variants) |\n| Dense prediction | Natural | Needs hierarchical/windowed variants |\n| Multimodal fit | Needs adapters | Natural token interface |\n| Edge deployment | Often easier | Improving with efficient variants |\n\nHybrids and modern CNNs (e.g. ConvNeXt) narrow the gap; outcomes depend on training recipe as much as architecture.`,
  aliases: ['CNN vs ViT', 'convnet vs transformer', 'ViT vs ResNet', 'which image model should I use', 'vision transformer vs convolutional'],
  intents: ['pick an image model family', 'weigh latency and data constraints for image models'],
  questions: ['Should I use a CNN or a Vision Transformer?', 'Is ViT better than ResNet?', 'Which image model is best for small datasets?', 'Which vision backbone is best for edge devices?'],
  pre: ['convolutional-neural-networks', 'vision-transformers'], rel: ['transfer-learning', 'multimodal-ai'],
  vs: [['convolutional-neural-networks', 'Efficient local-pattern model.'], ['vision-transformers', 'Attention-based patch model.']],
  tech: ['timm', 'torchvision', 'Hugging Face'],
  patterns: ['Benchmark 2–3 pre-trained backbones on your validation set.', 'Prefer CNNs for tight latency/memory budgets; ViT for scale and multimodal reuse.'],
  fails: ['Choosing by hype instead of measurement.', 'Comparing models trained with different recipes.'],
  fix: [['Unclear winner', 'Fine-tune both with the same recipe and compare on your data.']],
  guide: ['List constraints (latency, memory, data size).', 'Shortlist backbones.', 'Fine-tune with matched recipes.', 'Choose on accuracy, cost and maintainability.'],
  when: 'Default: best pre-trained backbone that fits your constraints.',
  sources: [['Dosovitskiy et al., An Image is Worth 16x16 Words (2020)', 'arXiv:2010.11929'], ['Liu et al., A ConvNet for the 2020s (2022)', 'arXiv:2201.03545']],
  fresh: 'evolving', keywords: ['comparison', 'backbone']
}),

E('mixture-of-experts', 'Mixture of Experts (MoE)', 'technique', A, {
  summary: 'Mixture-of-experts models contain many specialist sub-networks and route each token to only a few, giving large capacity at lower per-token compute.',
  short: 'A router sends each token to a **small subset of expert sub-networks**, so total parameters are large but active parameters per token are fewer. Memory still holds all experts; routing and load balancing add complexity.',
  plain: `Instead of every part of the model working on every word, an MoE model has many "expert" blocks and a router that picks a few for each word. The model can be very big in total yet use only part of it each time.`,
  technical: `In sparse MoE transformer layers, the feed-forward block is replaced by N experts and a gating network selecting top-k experts per token (Shazeer et al., 2017; Switch Transformer, Fedus et al., 2021; Mixtral, Jiang et al., 2024). Auxiliary losses encourage load balance. Compute per token scales with active experts, but memory scales with total parameters and expert-parallel serving needs all-to-all communication. Total and active parameter counts differ and should not be conflated.`,
  aliases: ['MoE', 'sparse mixture of experts', 'expert routing', 'sparse models', 'Switch Transformer', 'Mixtral', 'top-k routing', 'active parameters'],
  intents: ['understand why some models quote total and active parameters', 'estimate serving cost of MoE models'],
  questions: ['What is a mixture of experts model?', 'What are active parameters in an MoE?', 'Why are MoE models cheaper to run per token?', 'Do MoE models need less memory?'],
  pre: ['transformers'], rel: ['scaling-laws', 'model-serving-and-inference', 'distributed-training', 'open-weights-models', 'vllm'],
  vs: [['transformers', 'Dense transformers use all parameters for every token; MoE activates a subset.']],
  tech: ['Switch Transformer', 'Mixtral', 'DeepSpeed-MoE', 'Megatron-LM', 'vLLM'],
  patterns: ['Top-1 or top-2 routing with load-balancing loss.', 'Expert parallelism across GPUs.', 'Shared experts alongside routed ones.', 'Quantise experts to cut memory.'],
  fails: ['Load imbalance, with some experts overused.', 'High memory despite low active compute.', 'Communication bottlenecks at scale.', 'Fine-tuning instability.'],
  fix: [['Cannot fit the model in memory', 'Quantise, offload, or use fewer experts/smaller variant.'], ['Throughput lower than expected', 'Check batching, expert parallelism and communication overhead.']],
  guide: ['Compare both total and active parameters.', 'Estimate memory from total, compute from active.', 'Choose a serving engine with MoE support.', 'Benchmark latency and throughput on your hardware.'],
  when: 'Relevant when choosing or serving large open models; rarely something application teams build.',
  sources: [['Shazeer et al., Outrageously Large Neural Networks: The Sparsely-Gated Mixture-of-Experts Layer (2017)', 'arXiv:1701.06538'], ['Fedus et al., Switch Transformers (2021)', 'arXiv:2101.03961'], ['Jiang et al., Mixtral of Experts (2024)', 'arXiv:2401.04088']],
  fresh: 'evolving', keywords: ['sparse', 'router', 'experts']
}),

E('state-space-models', 'State Space Models (Mamba and S4)', 'concept', A, {
  summary: 'State space models process sequences with a compact recurrent state and linear-time computation, offering an alternative to attention for long inputs.',
  short: 'SSMs like **S4 and Mamba** compress history into a fixed-size state, giving **linear-time** sequence processing and cheap inference on long inputs, with trade-offs in recall of exact details versus attention. Hybrids are common.',
  plain: `Attention compares every word with every other word, which gets expensive for very long inputs. State space models instead keep a running summary of what they've seen, so cost grows linearly with length. They can be much cheaper on long sequences but may be weaker at looking up exact earlier details.`,
  technical: `Structured SSMs (S4; Gu et al., 2021) model sequences with linear dynamical systems that can be computed as convolutions for training and recurrences for inference. Mamba (Gu & Dao, 2023) adds input-dependent (selective) parameters with a hardware-aware scan. Relative to attention, SSMs have constant-size state at inference (no growing [[kv-cache]]) but a bounded memory; hybrid models interleave attention and SSM layers. Empirical comparisons are model-, scale- and task-dependent.`,
  aliases: ['SSM', 'Mamba', 'S4', 'Mamba-2', 'selective state space', 'linear attention alternative', 'linear time sequence models', 'structured state space'],
  intents: ['understand transformer alternatives', 'evaluate SSMs for long context'],
  questions: ['What is Mamba?', 'What is a state space model?', 'Are state space models better than transformers?', 'Why do SSMs scale linearly with sequence length?'],
  pre: ['transformers', 'recurrent-neural-networks'], rel: ['transformers-vs-state-space-models', 'kv-cache', 'context-windows', 'mixture-of-experts', 'flash-attention'],
  vs: [['transformers', 'Attention keeps all tokens accessible at quadratic cost; SSMs compress history into a state at linear cost.'], ['recurrent-neural-networks', 'Modern SSMs can be trained in parallel unlike classic RNNs.']],
  tech: ['Mamba reference implementation', 'Hugging Face Transformers', 'hybrid attention–SSM models'],
  patterns: ['Hybrid stacks mixing attention and SSM layers.', 'Use for long-sequence modalities (audio, genomics, long text).', 'Evaluate on retrieval-heavy tasks specifically.'],
  fails: ['Weaker exact recall of distant details.', 'Immature tooling relative to transformers.', 'Reported gains not replicating at your scale.'],
  fix: [['Poor in-context retrieval', 'Consider hybrid architectures or add retrieval ([[rag]]).'], ['Tooling gaps', 'Check serving-engine support before committing.']],
  guide: ['Define your sequence length and latency needs.', 'Check available pre-trained models and serving support.', 'Benchmark on your tasks, especially recall-heavy ones.', 'Compare cost per token against a transformer.'],
  when: 'Consider for very long sequences or constrained inference memory; default to transformers where ecosystem support matters.',
  sources: [['Gu et al., Efficiently Modeling Long Sequences with Structured State Spaces (S4) (2021)', 'arXiv:2111.00396'], ['Gu & Dao, Mamba: Linear-Time Sequence Modeling with Selective State Spaces (2023)', 'arXiv:2312.00752'], ['Dao & Gu, Transformers are SSMs (Mamba-2) (2024)', 'arXiv:2405.21060']],
  fresh: 'volatile', tsc: ['Which production models use SSM/hybrid designs.', 'Comparative benchmark claims against transformers.', 'Tooling and serving support status.'],
  keywords: ['long context', 'linear time']
}),

E('transformers-vs-state-space-models', 'Transformers vs State Space Models', 'concept', A, {
  page_kind: 'comparison',
  summary: 'Transformers keep full access to the token history through attention; state space models keep a compressed state. The trade-off is exact recall versus linear-time efficiency.',
  short: '**Transformers**: strongest ecosystem, precise in-context recall, quadratic attention cost and growing KV cache. **SSMs**: linear time, constant-size state, efficient long sequences, weaker exact recall. **Hybrids** try to get both. Verify with benchmarks on your task.',
  plain: `Transformers can look back at any earlier word directly, which makes them precise but costly for very long inputs. State-space models carry a compact summary forward, which is cheaper but can lose details. Mixed designs combine them.`,
  technical: `| | Transformer | State space model |\n|---|---|---|\n| History access | Direct (attention over all tokens) | Compressed state |\n| Training cost vs length | Quadratic (mitigated by kernels) | Near-linear |\n| Inference memory | Grows with context ([[kv-cache]]) | Constant per layer |\n| Exact recall / copying | Strong | Weaker (task-dependent) |\n| Ecosystem and tooling | Mature | Younger |\n| Typical use | General LLMs | Long sequences, efficiency-focused or hybrid models |\n\nClaims of superiority are scale- and benchmark-dependent.`,
  aliases: ['transformer vs mamba', 'attention vs SSM', 'mamba vs transformer', 'transformer alternatives', 'are transformers going away'],
  intents: ['compare architectures for long context', 'decide whether to adopt SSM models'],
  questions: ['Mamba vs transformer: which is better?', 'Will state space models replace transformers?', 'Which architecture is better for long documents?', 'What are hybrid attention-SSM models?'],
  pre: ['transformers', 'state-space-models'], rel: ['kv-cache', 'flash-attention', 'context-windows'],
  vs: [['transformers', 'The dominant architecture.'], ['state-space-models', 'The linear-time alternative.']],
  tech: ['Mamba', 'FlashAttention', 'hybrid models'],
  patterns: ['Default to transformers for ecosystem; test SSM/hybrids when sequence length or memory dominate.', 'Evaluate retrieval/copy tasks explicitly.'],
  fails: ['Choosing on headline throughput without checking quality on your tasks.', 'Ignoring tooling support.'],
  fix: [['Unsure', 'Run both on your longest realistic inputs and compare quality, latency, memory.']],
  guide: ['Define sequence lengths.', 'List candidate models.', 'Benchmark quality + cost.', 'Verify serving support.'],
  when: 'Use transformers by default; evaluate SSMs for long-sequence efficiency.',
  sources: [['Gu & Dao, Mamba (2023)', 'arXiv:2312.00752'], ['Vaswani et al., Attention Is All You Need (2017)', 'arXiv:1706.03762']],
  fresh: 'volatile', tsc: ['Current state of model availability and benchmark comparisons.'],
  keywords: ['comparison', 'long context']
}),

E('diffusion-models', 'Diffusion Models', 'concept', A, {
  summary: 'Diffusion models generate images, audio and video by learning to reverse a gradual noising process, turning random noise into structured content step by step.',
  short: 'A diffusion model **learns to denoise**: starting from pure noise it iteratively refines a sample toward the data distribution, often guided by a text prompt. Many steps make it slower than one-shot generators; distillation and fewer-step samplers speed it up.',
  plain: `Imagine a picture slowly dissolving into static. A diffusion model learns to run that film backwards: starting from random static and step by step cleaning it up into an image that matches your description. Most modern image generators work this way.`,
  technical: `Forward process adds Gaussian noise over T steps; a network (U-Net or transformer) is trained to predict the noise (or score/velocity) so that sampling can iteratively denoise from noise (DDPM, Ho et al., 2020; score-based SDE view, Song et al., 2020). Latent diffusion (Rombach et al., 2021) runs diffusion in a compressed latent space; classifier-free guidance (Ho & Salimans, 2022) trades diversity for prompt adherence; DDIM and distillation reduce sampling steps. Text conditioning typically comes from a text encoder such as CLIP or T5.`,
  aliases: ['stable diffusion', 'latent diffusion', 'DDPM', 'denoising diffusion', 'text to image model', 'image generation model', 'classifier-free guidance', 'score-based models', 'diffusion transformer', 'DiT'],
  intents: ['understand how image generators work', 'tune guidance and steps'],
  questions: ['What is a diffusion model?', 'How does Stable Diffusion work?', 'What is classifier-free guidance?', 'Why do diffusion models take many steps?', 'What is latent diffusion?'],
  pre: ['neural-networks', 'generative-ai'], rel: ['generative-adversarial-networks', 'variational-autoencoders', 'contrastive-learning-clip', 'multimodal-ai', 'vision-transformers'],
  vs: [['generative-adversarial-networks', 'GANs generate in one pass via adversarial training; diffusion iterates denoising and is generally more stable to train.'], ['variational-autoencoders', 'VAEs encode to a latent and decode; diffusion refines noise iteratively. Latent diffusion uses a VAE for compression.']],
  tech: ['Stable Diffusion family', 'Diffusers (Hugging Face)', 'U-Net / DiT backbones', 'CLIP / T5 text encoders'],
  patterns: ['Text-conditioned latent diffusion with classifier-free guidance.', 'Img2img and inpainting by starting from partly noised inputs.', 'Distillation for few-step sampling.', 'LoRA adapters for style/subject customisation.'],
  fails: ['Prompts ignored at low guidance; oversaturated artefacts at high guidance.', 'Anatomy/text rendering errors.', 'Training-data bias and copyright concerns.', 'Slow sampling on limited hardware.'],
  fix: [['Image ignores prompt', 'Raise guidance moderately; rewrite prompt; check text encoder.'], ['Artefacts or burnt colours', 'Lower guidance; change sampler/steps.']],
  guide: ['Choose a pre-trained checkpoint and check its licence.', 'Tune steps and guidance on a fixed seed set.', 'Add LoRA for custom styles.', 'Add provenance/watermarking where required ([[c2pa-content-provenance]]).'],
  when: 'Use for image, audio and video generation and editing.',
  sources: [['Ho et al., Denoising Diffusion Probabilistic Models (2020)', 'arXiv:2006.11239'], ['Rombach et al., High-Resolution Image Synthesis with Latent Diffusion Models (2021)', 'arXiv:2112.10752'], ['Ho & Salimans, Classifier-Free Diffusion Guidance (2022)', 'arXiv:2207.12598']],
  fresh: 'evolving', keywords: ['denoising', 'text to image', 'noise']
}),

E('generative-adversarial-networks', 'Generative Adversarial Networks (GANs)', 'concept', A, {
  summary: 'GANs train a generator and a discriminator against each other so the generator learns to produce realistic samples.',
  short: 'A GAN pits a **generator** (makes fakes) against a **discriminator** (spots fakes). It yields sharp samples in one pass but training can be unstable and prone to mode collapse; diffusion has taken over many tasks.',
  plain: `Two networks play a game: a forger tries to produce convincing fakes while a detective tries to tell fakes from real examples. Each gets better because of the other, until the forger's output is realistic.`,
  technical: `Goodfellow et al. (2014) formulate a minimax game between G and D. Practical issues: non-convergence, mode collapse, vanishing gradients; mitigations include Wasserstein losses, spectral normalisation and progressive growing (StyleGAN family). GANs generate in a single forward pass (fast sampling), whereas [[diffusion-models]] now dominate many text-conditioned generation tasks.`,
  aliases: ['GAN', 'GANs', 'generator discriminator', 'StyleGAN', 'mode collapse', 'adversarial training', 'deepfake generator'],
  intents: ['understand GANs and their limits', 'compare GANs with diffusion models'],
  questions: ['What is a GAN?', 'What is mode collapse?', 'GAN vs diffusion model: what is the difference?', 'How are deepfakes made?'],
  pre: ['neural-networks'], rel: ['diffusion-models', 'variational-autoencoders', 'c2pa-content-provenance', 'generative-ai'],
  vs: [['diffusion-models', 'Diffusion is iterative and more stable to train; GANs are single-pass and faster at sampling.'], ['variational-autoencoders', 'VAEs optimise a likelihood bound and tend to give blurrier but more diverse samples.']],
  tech: ['StyleGAN', 'PyTorch', 'Wasserstein GAN'],
  patterns: ['Conditional GANs for class- or image-conditioned generation.', 'Spectral normalisation and two-timescale updates for stability.', 'Use for fast real-time generation or super-resolution.'],
  fails: ['Mode collapse.', 'Training oscillation or divergence.', 'Hard-to-evaluate quality (FID has caveats).', 'Misuse for synthetic media and fraud.'],
  fix: [['Generator outputs lack variety', 'Use stabilised losses, minibatch discrimination, or move to a diffusion model.'], ['Training diverges', 'Lower learning rates, balance G/D updates, use proven architectures.']],
  guide: ['Check whether diffusion fits better.', 'Start from a published architecture.', 'Track FID and visual samples.', 'Plan misuse mitigations and provenance.'],
  when: 'Consider for real-time or low-latency generation, super-resolution and legacy pipelines.',
  sources: [['Goodfellow et al., Generative Adversarial Nets (2014)', 'arXiv:1406.2661'], ['Karras et al., A Style-Based Generator Architecture for GANs (2018)', 'arXiv:1812.04948']],
  fresh: 'stable', keywords: ['adversarial', 'generator', 'discriminator']
}),

E('variational-autoencoders', 'Variational Autoencoders (VAEs)', 'concept', A, {
  summary: 'A VAE learns to compress data into a smooth probabilistic latent space and decode samples from it, enabling generation and representation learning.',
  short: 'A VAE has an **encoder to a latent distribution and a decoder back**, trained with a reconstruction loss plus a KL regulariser. It gives structured latent spaces; latent diffusion uses VAE-style autoencoders for compression.',
  plain: `A VAE squeezes data (like an image) into a short code, then learns to rebuild it. Because the codes are encouraged to form a smooth, well-behaved space, you can pick new codes and decode them into new, plausible samples.`,
  technical: `Kingma & Welling (2013) maximise the evidence lower bound: expected reconstruction log-likelihood minus KL(q(z|x) || p(z)), using the reparameterisation trick for gradients. Outputs can be blurrier than GANs/diffusion; extensions include β-VAE (disentanglement) and VQ-VAE (discrete codes), the latter widely used as image/audio tokenisers.`,
  aliases: ['VAE', 'variational autoencoder', 'autoencoder', 'latent space', 'VQ-VAE', 'reparameterization trick', 'ELBO', 'beta-VAE'],
  intents: ['understand latent-variable generative models', 'understand latent spaces used by image generators'],
  questions: ['What is a variational autoencoder?', 'What is a latent space?', 'What is the difference between an autoencoder and a VAE?', 'What is VQ-VAE used for?'],
  pre: ['neural-networks', 'unsupervised-learning'], rel: ['diffusion-models', 'generative-adversarial-networks', 'embeddings', 'multimodal-ai'],
  vs: [['generative-adversarial-networks', 'GANs use a discriminator; VAEs optimise a likelihood bound.'], ['diffusion-models', 'Diffusion refines noise iteratively; VAEs sample a latent and decode once.']],
  tech: ['PyTorch', 'VQ-VAE tokenisers', 'Stable Diffusion\'s autoencoder'],
  patterns: ['Latent compression before diffusion.', 'VQ-VAE tokenisation for images/audio.', 'Anomaly detection by reconstruction error.'],
  fails: ['Posterior collapse, where the decoder ignores the latent code.', 'Blurry reconstructions from the pixel-wise likelihood objective.', 'KL weight poorly tuned, trading reconstruction quality against latent regularity.'],
  fix: [['Decoder ignores latent', 'Anneal KL weight (KL warm-up) or adjust architecture.'], ['Blurry outputs', 'Add perceptual/adversarial losses or use diffusion.']],
  guide: ['Choose continuous vs discrete latent.', 'Tune KL weight.', 'Visualise reconstructions and samples.', 'Use as a component, e.g. for latent diffusion.'],
  when: 'Useful for compression, representation learning, anomaly detection and as the autoencoder inside latent diffusion.',
  sources: [['Kingma & Welling, Auto-Encoding Variational Bayes (2013)', 'arXiv:1312.6114'], ['van den Oord et al., Neural Discrete Representation Learning (VQ-VAE) (2017)', 'arXiv:1711.00937']],
  fresh: 'stable', keywords: ['latent', 'encoder', 'decoder']
}),

E('graph-neural-networks', 'Graph Neural Networks (GNNs)', 'concept', A, {
  summary: 'GNNs learn from data shaped like graphs — molecules, social networks, road maps — by passing messages between connected nodes.',
  short: 'A GNN updates each node\'s representation by **aggregating messages from its neighbours** over several rounds. It suits relational data (molecules, networks, recommendation); over-smoothing and scalability are known challenges.',
  plain: `Some data is naturally a network: atoms joined by bonds, people connected by friendships. A graph neural network lets each node repeatedly "ask its neighbours" and update what it knows, so after a few rounds each node's summary reflects its surroundings.`,
  technical: `Message-passing framework (Gilmer et al., 2017): h_v^{k+1} = U(h_v^k, AGG({M(h_u^k, h_v^k, e_uv)})). Variants: GCN (Kipf & Welling, 2016), GraphSAGE, GAT (attention), and graph transformers. Tasks: node, edge and graph-level prediction. Challenges: over-smoothing with depth, over-squashing, scaling to large graphs (sampling), and expressiveness limits (Weisfeiler–Lehman). Applications include molecules and materials ([[ai-drug-discovery]], [[ai-materials-discovery]]) and weather models such as GraphCast ([[ai-weather-forecasting]]).`,
  aliases: ['GNN', 'GCN', 'graph convolutional network', 'message passing', 'GraphSAGE', 'GAT', 'graph attention network', 'graph deep learning', 'graph transformer'],
  intents: ['model relational or graph data', 'understand GNN use in science'],
  questions: ['What is a graph neural network?', 'How does message passing work in GNNs?', 'What are GNNs used for?', 'What is over-smoothing?'],
  pre: ['neural-networks'], rel: ['ai-for-science', 'ai-drug-discovery', 'ai-materials-discovery', 'ai-weather-forecasting', 'graph-rag'],
  vs: [['graph-rag', 'GraphRAG uses knowledge graphs to organise retrieval for LLMs; GNNs are learned models over graph-structured data.'], ['convolutional-neural-networks', 'CNNs assume a regular grid; GNNs handle irregular connectivity.']],
  tech: ['PyTorch Geometric', 'DGL', 'Jraph', 'NetworkX'],
  patterns: ['Node classification with neighbourhood sampling.', 'Graph-level prediction with readout pooling (molecular property prediction).', 'Edge prediction for recommendations/link prediction.', 'Equivariant GNNs for 3-D physical systems.'],
  fails: ['Over-smoothing with many layers.', 'Memory blow-up on large graphs.', 'Leakage between train and test nodes in transductive setups.', 'Poorly defined graph construction.'],
  fix: [['Performance drops with depth', 'Use fewer layers, residual connections, or different aggregators.'], ['Out of memory', 'Neighbourhood sampling or cluster-based mini-batching.']],
  guide: ['Define nodes, edges and features.', 'Split train/test carefully for graphs.', 'Start with GCN/GraphSAGE baselines.', 'Add domain symmetries where relevant.'],
  when: 'Use when relationships between entities carry the signal.',
  sources: [['Kipf & Welling, Semi-Supervised Classification with Graph Convolutional Networks (2016)', 'arXiv:1609.02907'], ['Gilmer et al., Neural Message Passing for Quantum Chemistry (2017)', 'arXiv:1704.01212'], ['Veličković et al., Graph Attention Networks (2017)', 'arXiv:1710.10903']],
  fresh: 'stable', keywords: ['graph', 'nodes', 'edges', 'message passing']
}),

E('encoder-decoder-vs-decoder-only', 'Encoder-Only, Decoder-Only and Encoder-Decoder Models', 'concept', A, {
  page_kind: 'comparison',
  summary: 'Transformer models come in three layouts: encoders for understanding, decoders for generating, and encoder-decoders for transforming one sequence into another.',
  short: '**Encoder-only** (BERT-style): understanding, classification, embeddings. **Decoder-only** (GPT-style): generation and the dominant chat LLM layout. **Encoder-decoder** (T5-style): sequence-to-sequence tasks like translation.',
  plain: `Transformers are built in three layouts. Encoders read a whole text and produce a rich understanding of it (great for search and classification). Decoders write text one token at a time (the chat models). Encoder-decoders read one text and write another (translation, summarisation).`,
  technical: `| | Encoder-only | Decoder-only | Encoder-decoder |\n|---|---|---|---|\n| Attention | Bidirectional | Causal (left-to-right) | Bidirectional encoder + causal decoder with cross-attention |\n| Pre-training | Masked LM | Next-token prediction | Span corruption / denoising |\n| Typical use | Embeddings, classification, retrieval | Chat, code, general generation | Translation, summarisation, structured transforms |\n| Examples | BERT family | GPT-style LLMs | T5, original Transformer |\n\nDecoder-only models dominate current general-purpose LLMs partly for scaling simplicity and in-context learning; the other layouts remain strong for specific tasks.`,
  aliases: ['encoder vs decoder', 'BERT vs GPT', 'decoder-only', 'encoder-only', 'seq2seq transformer', 'T5', 'causal language model', 'bidirectional model'],
  intents: ['pick a transformer type for a task', 'understand why embedding models differ from chat models'],
  questions: ['What is the difference between BERT and GPT?', 'What is a decoder-only model?', 'Which transformer type is best for classification?', 'What is an encoder-decoder model?'],
  pre: ['transformers'], rel: ['embeddings', 'large-language-models', 'fine-tuning', 'positional-encoding'],
  vs: [['embeddings', 'Embedding models are usually encoder-style.']],
  tech: ['BERT', 'T5', 'GPT-style decoders', 'Hugging Face Transformers'],
  patterns: ['Encoder for classification/embedding; decoder for generation.', 'Encoder-decoder for translation/summarisation where input and output are distinct sequences.'],
  fails: ['Using a generative LLM where a small encoder would be cheaper and sufficient.', 'Expecting BERT-style encoders to generate fluent text.'],
  fix: [['Classification is slow/expensive', 'Try a fine-tuned small encoder.']],
  guide: ['Classify task: understand, generate or transform.', 'Pick the layout.', 'Choose a pre-trained model of that type.', 'Compare cost and quality.'],
  when: 'Pick the layout matching the task; default to decoder-only for open-ended generation.',
  sources: [['Vaswani et al., Attention Is All You Need (2017)', 'arXiv:1706.03762'], ['Devlin et al., BERT (2018)', 'arXiv:1810.04805'], ['Raffel et al., Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer (T5) (2019)', 'arXiv:1910.10683']],
  fresh: 'stable', keywords: ['BERT', 'GPT', 'T5', 'comparison']
}),

E('kv-cache', 'KV Cache', 'technique', A, {
  summary: 'The KV cache stores attention keys and values for past tokens so a model need not recompute them while generating, trading memory for speed.',
  short: 'During generation, the model **caches keys and values of earlier tokens**, so each new token only computes its own attention. The cache grows with context length and batch size, making memory the main serving limit.',
  plain: `When a model writes a long answer, it would be wasteful to re-read the whole conversation for every new word. It stores intermediate results (the "KV cache") from earlier words and reuses them. That makes generation faster but uses a lot of memory as the conversation grows.`,
  technical: `For each layer, keys and values of previous tokens are retained, giving per-token decode cost linear in context but memory O(layers × heads × head_dim × tokens × batch). Techniques to reduce or manage it: multi-query and grouped-query attention (Shazeer, 2019; Ainslie et al., 2023), PagedAttention (Kwon et al., 2023, vLLM), cache quantisation, prefix caching and eviction/compression policies. Prompt-caching features offered by providers reuse computed prefixes ([[prompt-caching]]).`,
  aliases: ['key value cache', 'KV caching', 'attention cache', 'grouped query attention', 'GQA', 'multi-query attention', 'PagedAttention', 'prefix cache', 'why LLM memory grows with context'],
  intents: ['understand memory use during inference', 'optimise long-context serving'],
  questions: ['What is a KV cache?', 'Why does GPU memory grow with context length?', 'What is grouped-query attention?', 'What is PagedAttention?'],
  pre: ['transformers', 'context-windows'], rel: ['vllm', 'prompt-caching', 'flash-attention', 'model-serving-and-inference', 'state-space-models', 'quantization'],
  vs: [['prompt-caching', 'Prompt caching is a provider billing/latency feature built on reusing cached prefixes; the KV cache is the underlying data structure.']],
  tech: ['vLLM PagedAttention', 'llama.cpp', 'TensorRT-LLM'],
  patterns: ['Paged KV memory management.', 'GQA/MQA models to shrink cache size.', 'Prefix/prompt caching for shared system prompts.', 'KV quantisation for long contexts.'],
  fails: ['Out-of-memory at long context or high concurrency.', 'Fragmentation wasting memory.', 'Cache invalidated by tiny prompt changes.'],
  fix: [['OOM with many concurrent users', 'Reduce max context/batch, use paged KV engines, quantise cache, or use a GQA model.'], ['Latency high on repeated prompts', 'Use prefix caching and keep shared prefixes stable.']],
  guide: ['Estimate cache size per token for your model.', 'Multiply by context and concurrency.', 'Choose a serving engine with paged KV.', 'Stabilise shared prefixes.'],
  when: 'Matters when serving LLMs or when you hit memory limits at long context.',
  sources: [['Kwon et al., Efficient Memory Management for LLM Serving with PagedAttention (2023)', 'arXiv:2309.06180'], ['Ainslie et al., GQA: Training Generalized Multi-Query Transformer Models (2023)', 'arXiv:2305.13245'], ['Shazeer, Fast Transformer Decoding: One Write-Head is All You Need (2019)', 'arXiv:1911.02150']],
  fresh: 'evolving', keywords: ['memory', 'inference', 'attention']
}),

E('flash-attention', 'FlashAttention', 'technique', A, {
  summary: 'FlashAttention is an exact attention algorithm that reorganises computation to cut memory traffic, speeding up transformers and enabling longer sequences.',
  short: 'FlashAttention computes **exact attention in tiles that stay in fast on-chip memory**, avoiding the huge intermediate attention matrix. It speeds training and inference and reduces memory without changing results (up to numerical differences).',
  plain: `Standard attention writes a very large table of scores to slow memory. FlashAttention processes it in small blocks that fit in the chip's fast memory, so the same answer is computed faster and with less memory.`,
  technical: `Dao et al. (2022) present an IO-aware exact attention using tiling and online softmax, reducing reads/writes between GPU HBM and SRAM; subsequent versions (FlashAttention-2, -3) improve parallelism and hardware utilisation. It is exact attention (not an approximation), so quality is unaffected apart from floating-point differences. Typically enabled through framework or library flags rather than hand-written.`,
  aliases: ['flash attention', 'FlashAttention-2', 'FlashAttention-3', 'IO-aware attention', 'efficient attention', 'fused attention', 'memory efficient attention'],
  intents: ['speed up training or inference', 'understand how longer contexts become feasible'],
  questions: ['What is FlashAttention?', 'Is FlashAttention approximate?', 'How do I enable FlashAttention?', 'Why is attention memory-bound?'],
  pre: ['transformers'], rel: ['kv-cache', 'gpus-and-ai-accelerators', 'distributed-training', 'state-space-models', 'vllm'],
  vs: [['state-space-models', 'SSMs change the model to avoid quadratic attention; FlashAttention keeps attention but computes it more efficiently.']],
  tech: ['flash-attn library', 'PyTorch scaled_dot_product_attention', 'Hugging Face attn_implementation', 'vLLM'],
  patterns: ['Enable via framework attention backend.', 'Combine with mixed precision.', 'Use with GQA and paged KV in serving.'],
  fails: ['Unsupported GPU/dtype combinations falling back silently.', 'Version mismatches between library, CUDA and PyTorch.', 'Expecting it to cut compute (it mainly cuts memory traffic).'],
  fix: [['Install/build errors', 'Match library, CUDA and PyTorch versions; prefer prebuilt wheels or the framework\'s built-in backend.'], ['No speedup', 'Check hardware support and that the backend is actually selected.']],
  guide: ['Use the framework\'s native fused attention if available.', 'Verify the backend in logs.', 'Benchmark with realistic sequence lengths.'],
  when: 'Use by default on supported GPUs for training and serving transformers.',
  sources: [['Dao et al., FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness (2022)', 'arXiv:2205.14135'], ['Dao, FlashAttention-2 (2023)', 'arXiv:2307.08691']],
  fresh: 'evolving', keywords: ['GPU', 'memory bandwidth', 'tiling']
}),

E('positional-encoding', 'Positional Encoding (Sinusoidal, RoPE, ALiBi)', 'technique', A, {
  summary: 'Attention has no built-in sense of order, so transformers add positional information. Methods like RoPE and ALiBi affect how well models handle long contexts.',
  short: 'Transformers need **explicit position information**. Sinusoidal/learned embeddings were original; **RoPE** and **ALiBi** are common in modern LLMs and shape how context can be extended beyond training length.',
  plain: `Attention sees a bag of tokens with no order, so models must be told where each token sits. Different schemes encode position differently, and the choice influences how well a model copes with inputs longer than it was trained on.`,
  technical: `Original transformers used sinusoidal absolute encodings (Vaswani et al., 2017). Rotary Position Embedding (RoFormer, Su et al., 2021) rotates query/key vectors by position-dependent angles to encode relative position; ALiBi (Press et al., 2021) adds distance-based biases to attention scores. Context-extension techniques (position interpolation, YaRN-style scaling) modify these at fine-tuning or inference time; effectiveness varies and claims about extended windows should be validated on long-context tasks.`,
  aliases: ['RoPE', 'rotary position embedding', 'ALiBi', 'sinusoidal encoding', 'position embeddings', 'context extension', 'position interpolation', 'YaRN', 'extend context window'],
  intents: ['understand how context length can be extended', 'debug long-context degradation'],
  questions: ['What is RoPE?', 'How do models know token order?', 'How can a context window be extended?', 'What is ALiBi?'],
  pre: ['transformers', 'tokens'], rel: ['context-windows', 'kv-cache', 'encoder-decoder-vs-decoder-only', 'flash-attention'],
  vs: [['context-windows', 'The context window is the limit; positional encoding is one mechanism that determines how it can be extended.']],
  tech: ['RoFormer / RoPE', 'ALiBi', 'YaRN', 'Hugging Face rope_scaling configs'],
  patterns: ['Use the model\'s published recommended scaling for longer contexts.', 'Fine-tune on long sequences after position interpolation.', 'Evaluate on needle-in-a-haystack and real long documents.'],
  fails: ['Extending beyond trained length without adaptation causing garbled output.', 'Passing "needle" tests while failing real long-document tasks.', 'Config mismatches between model and serving engine.'],
  fix: [['Quality collapses past a length', 'Use a model trained/extended for that length or apply the recommended scaling and test.'], ['Different outputs across engines', 'Verify rope parameters match the reference config.']],
  guide: ['Read the model card for supported length.', 'Use official scaling settings.', 'Test with your own long inputs.', 'Prefer retrieval over brute-force length when cheaper ([[rag]]).'],
  when: 'Useful when diagnosing or extending long-context behaviour.',
  sources: [['Su et al., RoFormer: Enhanced Transformer with Rotary Position Embedding (2021)', 'arXiv:2104.09864'], ['Press et al., Train Short, Test Long: Attention with Linear Biases (ALiBi) (2021)', 'arXiv:2108.12409'], ['Chen et al., Extending Context Window of LLMs via Positional Interpolation (2023)', 'arXiv:2306.15595']],
  fresh: 'evolving', keywords: ['rotary', 'long context', 'position']
})
];
