import { E } from './entity-model.mjs';
const L = 'LLM Techniques', V = 'Multimodal AI';
export const entities = [
E('scaling-laws', 'Scaling Laws', 'concept', L, {
  summary: 'Scaling laws describe how model loss tends to improve predictably with more parameters, data and compute — and guide how to split a training budget.',
  short: 'Empirical **power-law relationships between loss and model size, data and compute** let labs plan training runs. They predict loss, not every capability, and recommended ratios (e.g. Chinchilla) have been revisited as practice changed.',
  plain: `Researchers found that making models bigger, training them on more text and using more compute improves them in a surprisingly smooth, predictable way. Scaling laws are those relationships. They help decide how to spend a training budget — for example how big a model to train and on how much data.`,
  technical: `Kaplan et al. (2020) reported power-law scaling of cross-entropy loss with parameters, dataset size and compute. Hoffmann et al. (2022, "Chinchilla") argued that, for a fixed compute budget, parameters and training tokens should be scaled roughly in proportion, and that many earlier models were under-trained for their size. Scaling laws concern pre-training loss on a distribution; mapping to downstream capabilities is less reliable, and inference-time techniques add another axis ([[test-time-compute]]). Later work considers inference cost, data quality and repeated data, so "optimal" ratios depend on assumptions.`,
  aliases: ['neural scaling laws', 'Chinchilla scaling', 'compute optimal training', 'Kaplan scaling laws', 'bigger models better', 'power law loss', 'tokens per parameter'],
  intents: ['understand why bigger models improve', 'reason about training budgets'],
  questions: ['What are scaling laws in AI?', 'What is Chinchilla optimal?', 'Do scaling laws mean bigger is always better?', 'How many tokens should a model be trained on?'],
  pre: ['large-language-models', 'self-supervised-learning'], rel: ['test-time-compute', 'mixture-of-experts', 'small-language-models', 'knowledge-distillation', 'distributed-training'],
  vs: [['test-time-compute', 'Scaling laws relate training resources to loss; test-time compute adds resources per query after training.']],
  tech: ['training-run planning', 'compute budget calculators'],
  patterns: ['Fit scaling curves from small runs to extrapolate large-run loss.', 'Choose model size and token count jointly for a compute budget.', 'Over-train smaller models when inference cost dominates.'],
  fails: ['Extrapolating beyond the tested range.', 'Assuming loss improvements translate to every downstream skill.', 'Ignoring data quality and repetition.', 'Treating a published optimal ratio as universal.'],
  fix: [['Large run underperforms prediction', 'Check data quality, hyperparameters and instabilities; verify the fitted range.'], ['Unsure what size to train', 'Include inference cost in the objective, not training compute alone.']],
  guide: ['Run small-scale experiments across sizes.', 'Fit loss vs compute.', 'Account for data limits.', 'Weigh inference cost.', 'Validate on downstream evaluations.'],
  when: 'Relevant to people planning pre-training; for application builders it explains why model families come in size tiers.',
  sources: [['Kaplan et al., Scaling Laws for Neural Language Models (2020)', 'arXiv:2001.08361'], ['Hoffmann et al., Training Compute-Optimal Large Language Models (2022)', 'arXiv:2203.15556']],
  fresh: 'evolving', keywords: ['compute', 'parameters', 'data']
}),

E('instruction-tuning', 'Instruction Tuning', 'technique', L, {
  summary: 'Instruction tuning fine-tunes a pre-trained language model on many instruction-and-response examples so it follows requests instead of merely continuing text.',
  short: 'Instruction tuning is **supervised fine-tuning on instruction→response pairs**. It turns a base model into an assistant-style model; preference optimisation then refines tone, helpfulness and safety.',
  plain: `A raw pre-trained model just continues text. Instruction tuning teaches it, with lots of examples, to treat your text as a request and respond helpfully. It is a main step between a base model and a chat assistant.`,
  technical: `Supervised fine-tuning (SFT) on diverse task instructions (FLAN, Wei et al., 2021; T0; InstructGPT SFT stage, Ouyang et al., 2022), including synthetic instruction data (Self-Instruct, Wang et al., 2022). The standard pipeline is pre-training → instruction tuning → preference optimisation ([[rlhf]], [[preference-optimization]]). Data quality and diversity matter more than raw volume; narrow tuning can cause loss of general abilities.`,
  aliases: ['SFT', 'supervised fine-tuning', 'instruct model', 'instruction following training', 'FLAN', 'base model vs instruct model', 'chat tuning', 'assistant tuning'],
  intents: ['understand how base models become assistants', 'decide whether to use a base or instruct model'],
  questions: ['What is instruction tuning?', 'What is the difference between a base model and an instruct model?', 'What is SFT?', 'How are chat models trained?'],
  pre: ['large-language-models', 'fine-tuning'], rel: ['rlhf', 'preference-optimization', 'dpo', 'lora-and-peft', 'self-supervised-learning', 'open-weights-models'],
  vs: [['preference-optimization', 'Instruction tuning imitates demonstrations; preference optimisation learns from comparisons of better and worse responses.'], ['fine-tuning', 'Instruction tuning is a particular fine-tuning recipe aimed at general instruction following.']],
  tech: ['TRL SFTTrainer', 'Axolotl', 'LLaMA-Factory', 'Hugging Face datasets'],
  patterns: ['Curate a small, high-quality, diverse instruction set.', 'Use the model\'s chat template consistently.', 'Mask the prompt tokens in the loss where appropriate.', 'Hold out an evaluation set of unseen instructions.'],
  fails: ['Template mismatch between training and inference.', 'Low-quality or contaminated data.', 'Over-tuning leading to forgetting or style collapse.', 'Training on outputs whose licence forbids it.'],
  fix: [['Model rambles or ignores stop tokens', 'Check the chat template and end-of-sequence handling.'], ['General skills degrade', 'Lower learning rate/epochs; mix in general data; use LoRA.']],
  guide: ['Pick a base model and check its licence.', 'Collect/curate examples.', 'Apply its chat template.', 'Fine-tune (LoRA first).', 'Evaluate on held-out instructions and regressions ([[ai-evaluation]]).'],
  when: 'Relevant if you adapt open-weight base models; most users consume already-tuned models.',
  sources: [['Wei et al., Finetuned Language Models Are Zero-Shot Learners (FLAN) (2021)', 'arXiv:2109.01652'], ['Ouyang et al., Training language models to follow instructions with human feedback (2022)', 'arXiv:2203.02155'], ['Wang et al., Self-Instruct (2022)', 'arXiv:2212.10560']],
  fresh: 'evolving', keywords: ['SFT', 'chat model', 'base model']
}),

E('lora-and-peft', 'LoRA and Parameter-Efficient Fine-Tuning (PEFT)', 'technique', L, {
  summary: 'LoRA and other PEFT methods adapt a large model by training a small number of added parameters while the original weights stay frozen.',
  short: 'LoRA adds **small low-rank adapter matrices** to a frozen model and trains only those, cutting memory and storage dramatically. QLoRA combines it with a quantised base. Adapters can be swapped per task.',
  plain: `Fully fine-tuning a giant model means updating billions of numbers. LoRA freezes the original and trains a tiny add-on instead — often a small fraction of the size — so tuning fits on far smaller hardware and you can keep many small add-ons for different tasks.`,
  technical: `LoRA (Hu et al., 2021) reparameterises weight updates as ΔW = BA with low rank r, injected into attention (and often MLP) projections; at inference adapters can be merged into the base weights or served separately. QLoRA (Dettmers et al., 2023) fine-tunes adapters on a 4-bit quantised base. Other PEFT families: adapters (Houlsby et al., 2019), prefix/prompt tuning, DoRA. Quality is often close to full fine-tuning on many tasks but not always, particularly for large distribution shifts.`,
  aliases: ['LoRA', 'QLoRA', 'PEFT', 'low rank adaptation', 'adapter fine-tuning', 'parameter efficient fine tuning', 'DoRA', 'prompt tuning', 'adapters', 'fine-tune on one GPU'],
  intents: ['fine-tune with limited GPU memory', 'manage multiple task adapters'],
  questions: ['What is LoRA?', 'What is QLoRA?', 'How much GPU memory do I need to fine-tune with LoRA?', 'What rank should I use for LoRA?', 'LoRA vs full fine-tuning?'],
  pre: ['fine-tuning', 'neural-networks'], rel: ['lora-vs-full-fine-tuning', 'quantization', 'instruction-tuning', 'transfer-learning', 'hugging-face', 'local-ai'],
  vs: [['lora-vs-full-fine-tuning', 'Direct comparison and decision guide.'], ['fine-tuning', 'LoRA is one way to do fine-tuning.']],
  tech: ['Hugging Face PEFT', 'TRL', 'bitsandbytes', 'Axolotl', 'Unsloth'],
  patterns: ['Target attention (and optionally MLP) projections with rank 8–64 as a starting range to test.', 'QLoRA when memory is tight.', 'Merge adapters for deployment or serve multiple adapters on one base.', 'Keep an evaluation set per adapter.'],
  fails: ['Rank too low to learn the task, or alpha/LR mis-set.', 'Merging into a quantised base without care, degrading quality.', 'Adapter/base version mismatch.', 'Overfitting small datasets.'],
  fix: [['Adapter barely changes behaviour', 'Raise rank/learning rate, target more modules, check data formatting.'], ['Quality drops after merge', 'Merge into the full-precision base then quantise, and re-evaluate.']],
  guide: ['Choose a base model and licence.', 'Prepare chat-template-formatted data.', 'Start with a modest rank and standard LR.', 'Evaluate vs the base and a prompt-only baseline.', 'Decide merge vs separate serving.'],
  when: 'Default for adapting open models on modest hardware.',
  sources: [['Hu et al., LoRA: Low-Rank Adaptation of Large Language Models (2021)', 'arXiv:2106.09685'], ['Dettmers et al., QLoRA (2023)', 'arXiv:2305.14314'], ['Houlsby et al., Parameter-Efficient Transfer Learning for NLP (2019)', 'arXiv:1902.00751']],
  fresh: 'evolving', keywords: ['adapters', 'low rank', 'GPU memory']
}),

E('lora-vs-full-fine-tuning', 'LoRA vs Full Fine-Tuning', 'concept', L, {
  page_kind: 'comparison',
  summary: 'LoRA trains small adapters on a frozen model; full fine-tuning updates all weights. LoRA is cheaper and easier to manage; full fine-tuning can fit large shifts better.',
  short: '**LoRA**: low memory, small artefacts, swappable adapters, quality often close for many tasks. **Full fine-tuning**: highest capacity and potentially best on big domain shifts, but costly and heavier to store and serve. Start with LoRA and escalate only if evaluation shows a gap.',
  plain: `Full fine-tuning rewrites the whole model; LoRA adds a small trainable layer on top. LoRA is far cheaper and lets you keep many variants; full tuning has more freedom to change the model.`,
  technical: `| | LoRA / PEFT | Full fine-tuning |\n|---|---|---|\n| Trainable params | Small fraction | All |\n| GPU memory | Low (lower still with QLoRA) | High (weights, gradients, optimiser state) |\n| Artefact size | Adapter files | Full model copy |\n| Multi-task serving | Swap/merge adapters | One model per variant |\n| Large domain shifts | May underfit | Better capacity |\n| Forgetting risk | Lower | Higher |\n\nEmpirical differences are task- and model-dependent; measure on your evaluation set.`,
  aliases: ['LoRA vs fine-tuning', 'full fine-tuning vs LoRA', 'PEFT vs full finetune', 'should I use LoRA', 'LoRA or full finetuning'],
  intents: ['choose a fine-tuning method for hardware and quality needs', 'estimate GPU memory and storage for fine-tuning'],
  questions: ['Is LoRA as good as full fine-tuning?', 'When should I do full fine-tuning instead of LoRA?', 'How much cheaper is LoRA?', 'Can I serve multiple LoRA adapters?'],
  pre: ['lora-and-peft', 'fine-tuning'], rel: ['quantization', 'instruction-tuning'],
  vs: [['lora-and-peft', 'Adapter-based tuning.'], ['fine-tuning', 'The general idea.']],
  tech: ['Hugging Face PEFT', 'DeepSpeed', 'FSDP'],
  patterns: ['LoRA first; compare against full fine-tune only if the gap matters.', 'Full fine-tune when you have the hardware and a large domain shift.'],
  fails: ['Paying for full fine-tuning without proving a quality gap.', 'Under-ranking LoRA and concluding PEFT does not work.'],
  fix: [['LoRA underfits', 'Raise rank, target more modules or train longer before switching.']],
  guide: ['Estimate memory budget.', 'Run LoRA baseline.', 'Evaluate gap vs full tuning on a pilot.', 'Decide based on quality, cost and serving.'],
  when: 'Default to LoRA; escalate on measured need.',
  sources: [['Hu et al., LoRA (2021)', 'arXiv:2106.09685'], ['Biderman et al., LoRA Learns Less and Forgets Less (2024)', 'arXiv:2405.09673']],
  fresh: 'evolving', keywords: ['comparison', 'PEFT']
}),

E('quantization', 'Quantization of AI Models', 'technique', L, {
  summary: 'Quantisation stores and computes a model\'s numbers at lower precision — for example 8-bit or 4-bit — to cut memory and often speed up inference, at some quality cost.',
  short: 'Quantisation **reduces numeric precision** of weights (and sometimes activations or the KV cache). It lets bigger models fit on smaller hardware; 8-bit is usually safe, 4-bit needs checking, and quality loss varies by model, method and task.',
  plain: `Model weights are stored as numbers. Rounding them to fewer bits shrinks the model — sometimes by 2–4× or more — so it fits on a smaller GPU or laptop. The price is a small loss of accuracy that depends on how aggressively you round and which method you use.`,
  technical: `Methods: post-training quantisation (GPTQ, Frantar et al., 2022; AWQ, Lin et al., 2023; LLM.int8(), Dettmers et al., 2022), quantisation-aware training, and file formats such as GGUF used by llama.cpp with various k-quant schemes. Weight-only quantisation reduces memory and memory-bandwidth-bound decoding time; activation and KV-cache quantisation address other bottlenecks. Outlier activations are a known difficulty. Effects on quality, especially for reasoning and long context, must be measured per model.`,
  aliases: ['quantisation', '4-bit quantization', '8-bit', 'GPTQ', 'AWQ', 'GGUF', 'int8', 'int4', 'FP8', 'low precision inference', 'k-quants', 'model compression'],
  intents: ['fit a model in less memory', 'choose a quantisation level or format'],
  questions: ['What is model quantization?', 'What is GGUF?', 'Does quantization reduce quality?', 'What is the difference between GPTQ and AWQ?', 'How much VRAM do I need to run a 7B model?'],
  pre: ['large-language-models', 'neural-networks'], rel: ['local-ai', 'llama-cpp', 'ollama', 'lora-and-peft', 'knowledge-distillation', 'model-serving-and-inference', 'kv-cache'],
  vs: [['knowledge-distillation', 'Distillation trains a smaller model; quantisation shrinks the numbers of an existing model.']],
  tech: ['llama.cpp (GGUF)', 'bitsandbytes', 'AutoGPTQ / AWQ tooling', 'vLLM', 'ONNX Runtime'],
  patterns: ['Start with 8-bit; test 4-bit variants on your tasks.', 'Use pre-quantised checkpoints from trusted sources.', 'Quantise the KV cache for long contexts when supported.', 'Evaluate quality before and after on your own prompts.'],
  fails: ['Quality loss unnoticed because only perplexity was checked.', 'Tool-use or reasoning degrading more than chat.', 'Untrusted quantised files from unknown uploaders.', 'Format incompatible with the runtime.'],
  fix: [['Outputs degrade after quantising', 'Try a higher-bit variant or different method; evaluate on task-specific tests.'], ['Model will not load', 'Check that format and runtime versions match (e.g. GGUF with llama.cpp).']],
  guide: ['Estimate memory: parameters × bytes per weight plus KV cache and overhead.', 'Pick format for your runtime.', 'Benchmark quality and speed.', 'Verify provenance of downloaded weights ([[ai-privacy-and-security]]).'],
  when: 'Essential for local inference and cost-efficient serving.',
  sources: [['Frantar et al., GPTQ (2022)', 'arXiv:2210.17323'], ['Lin et al., AWQ (2023)', 'arXiv:2306.00978'], ['Dettmers et al., LLM.int8() (2022)', 'arXiv:2208.07339']],
  fresh: 'volatile', tsc: ['Which formats/methods are best supported by which runtimes.', 'Quality-vs-bits claims for specific models.', 'Memory requirement figures for specific models.'],
  keywords: ['GGUF', 'bits', 'VRAM', 'compression']
}),

E('knowledge-distillation', 'Knowledge Distillation', 'technique', L, {
  summary: 'Distillation trains a smaller student model to imitate a larger teacher, capturing much of its behaviour at lower cost.',
  short: 'Distillation = **train a small student on a big teacher\'s outputs** (soft probabilities or generated data). It can give cheaper, faster models for narrow tasks; check teacher licence terms and expect a quality gap on hard cases.',
  plain: `A large model is the teacher; a smaller model is the student that learns to copy the teacher\'s answers. The student ends up much cheaper to run while keeping much of the teacher\'s skill on the tasks it was taught.`,
  technical: `Classic distillation (Hinton et al., 2015) minimises divergence between student and teacher output distributions, often with temperature softening; DistilBERT (Sanh et al., 2019) is a well-known example. For LLMs, "distillation" often means supervised training on teacher-generated text or reasoning traces. Provider terms of service may restrict using model outputs to train competing models — verify before doing so.`,
  aliases: ['model distillation', 'teacher student', 'distilled model', 'DistilBERT', 'distill a large model', 'synthetic data from a bigger model'],
  intents: ['make a cheaper model for a narrow task', 'check legality of training on model outputs'],
  questions: ['What is knowledge distillation?', 'How do I distill a large model into a small one?', 'Can I train on GPT outputs?', 'Distillation vs quantization?'],
  pre: ['fine-tuning'], rel: ['small-language-models', 'quantization', 'instruction-tuning', 'llm-cost-optimization', 'reinforcement-learning-for-reasoning'],
  vs: [['quantization', 'Quantisation compresses numbers; distillation trains a different, smaller model.'], ['fine-tuning', 'Distillation is fine-tuning with a teacher\'s outputs as the target.']],
  tech: ['TRL', 'DistilBERT', 'synthetic data pipelines'],
  patterns: ['Generate task-specific data with a teacher, filter, fine-tune a small model.', 'Logit distillation where teacher logits are available (open models).', 'Evaluate student vs teacher on your task.'],
  fails: ['Student inherits teacher errors and biases.', 'Terms-of-use violations.', 'Distribution gap between synthetic and real inputs.', 'Over-claiming equivalence with the teacher.'],
  fix: [['Student weak on hard cases', 'Add more hard examples; keep the teacher for escalation.']],
  guide: ['Check the teacher\'s licence/terms.', 'Define the narrow task.', 'Generate and filter data.', 'Train and evaluate the student.', 'Route hard cases to the teacher.'],
  when: 'Use for high-volume narrow tasks where cost or latency matters.',
  sources: [['Hinton et al., Distilling the Knowledge in a Neural Network (2015)', 'arXiv:1503.02531'], ['Sanh et al., DistilBERT (2019)', 'arXiv:1910.01108'], ['Provider terms of use regarding training on outputs', null]],
  fresh: 'volatile', tsc: ['Provider terms about using outputs to train other models.'],
  keywords: ['teacher', 'student', 'compression']
}),

E('speculative-decoding', 'Speculative Decoding', 'technique', L, {
  summary: 'Speculative decoding speeds up generation by letting a small draft model propose several tokens that a large model verifies in one pass, without changing the output distribution.',
  short: 'A cheap **draft model proposes k tokens; the big model checks them in parallel** and accepts the matching prefix. Done correctly, output has the same distribution as the big model alone but arrives faster.',
  plain: `Generating one word at a time is slow. A small helper model guesses the next few words; the big model then checks all of them at once and keeps the correct ones. When the helper guesses well, you get several words for the price of one big-model step.`,
  technical: `Leviathan et al. (2022) and Chen et al. (2023) describe accept/reject sampling schemes that preserve the target model\'s distribution. Speedup depends on the draft\'s acceptance rate and relative cost. Variants include self-speculation (draft heads such as Medusa), n-gram/prompt-lookup drafts, and tree-based verification. Gains are workload-dependent and are largest on predictable text such as code or structured output.`,
  aliases: ['speculative sampling', 'draft model', 'assisted generation', 'Medusa', 'prompt lookup decoding', 'faster LLM inference', 'lookahead decoding'],
  intents: ['reduce LLM latency without changing outputs', 'check whether an inference engine feature will help my workload'],
  questions: ['What is speculative decoding?', 'How does a draft model speed up LLMs?', 'Does speculative decoding change the output?', 'When does speculative decoding not help?'],
  pre: ['sampling-and-decoding', 'kv-cache'], rel: ['model-serving-and-inference', 'vllm', 'quantization', 'llm-cost-optimization'],
  vs: [['quantization', 'Quantisation makes each step cheaper; speculative decoding reduces the number of expensive steps.']],
  tech: ['vLLM', 'llama.cpp', 'Hugging Face assisted generation', 'TensorRT-LLM'],
  patterns: ['Pair a small and large model from the same family.', 'Use n-gram drafts for structured or repetitive output.', 'Tune draft length by measured acceptance rate.'],
  fails: ['Low acceptance rate from a poorly matched draft.', 'Memory overhead of a second model.', 'Little gain at high batch sizes where the server is compute-bound.'],
  fix: [['No speedup', 'Measure acceptance rate; try a better draft or shorter speculation length.'], ['Higher memory use', 'Use self-speculative or n-gram methods.']],
  guide: ['Check your engine supports it.', 'Choose a draft from the same family.', 'Benchmark with realistic prompts and batch sizes.', 'Keep it only if latency improves.'],
  when: 'Use for latency-sensitive serving at low-to-moderate batch sizes.',
  sources: [['Leviathan et al., Fast Inference from Transformers via Speculative Decoding (2022)', 'arXiv:2211.17192'], ['Chen et al., Accelerating LLM Decoding with Speculative Sampling (2023)', 'arXiv:2302.01318']],
  fresh: 'evolving', keywords: ['latency', 'draft', 'verify']
}),

E('small-language-models', 'Small Language Models (SLMs)', 'concept', L, {
  summary: 'Small language models are compact LLMs — typically up to a few billion parameters — that run cheaply, often on laptops or phones, and can match larger models on narrow tasks.',
  short: 'SLMs trade **breadth for efficiency**: lower cost, latency and memory, easy local deployment, and strong results on focused tasks when fine-tuned. They are weaker on broad knowledge and hard reasoning.',
  plain: `Not every job needs the biggest model. Small language models are lighter versions that can run on a laptop or phone and, when tuned for a specific task like classification or extraction, can do it well, quickly and cheaply.`,
  technical: `No fixed boundary defines "small"; the term commonly covers models from hundreds of millions to a few billion parameters. Techniques include careful data curation ("textbook-quality" data, Gunasekar et al., 2023), distillation, pruning and quantisation. Examples of families from various vendors exist (Phi, Gemma and others) — names and capabilities change quickly and should be checked against current model cards.`,
  aliases: ['SLM', 'SLMs', 'small LLM', 'tiny models', 'on-device models', 'edge language models', 'compact language models', 'small models vs large models'],
  intents: ['pick a model for on-device or low-cost use', 'balance cost, latency and quality for narrow tasks'],
  questions: ['What is a small language model?', 'Can a small model replace a large LLM?', 'Which tasks suit small language models?', 'Can I run a language model on a phone?'],
  pre: ['large-language-models'], rel: ['local-ai', 'quantization', 'knowledge-distillation', 'lora-and-peft', 'open-weights-models', 'local-ai-vs-cloud-ai'],
  vs: [['large-language-models', 'Large models have broader knowledge and stronger reasoning; small models win on cost, latency and privacy.']],
  tech: ['Phi-family and Gemma-family models', 'llama.cpp', 'ONNX Runtime', 'Ollama'],
  patterns: ['Fine-tune an SLM on a narrow task.', 'Use SLM first with escalation to a large model.', 'On-device inference for privacy.', 'Pair with retrieval for knowledge.'],
  fails: ['Expecting broad world knowledge.', 'Weak multi-step reasoning.', 'Over-trusting benchmark numbers from vendor reports.', 'Licence restrictions overlooked.'],
  fix: [['Facts wrong', 'Add retrieval ([[rag]]) or escalate.'], ['Quality insufficient', 'Fine-tune on task data or move up a size.']],
  guide: ['Define the narrow task and quality bar.', 'Shortlist SLMs; read current model cards.', 'Evaluate on your data.', 'Quantise for the target device.', 'Add escalation path.'],
  when: 'Use for classification, extraction, routing, on-device assistants and cost-sensitive workloads.',
  sources: [['Gunasekar et al., Textbooks Are All You Need (2023)', 'arXiv:2306.11644'], ['Abdin et al., Phi-3 Technical Report (2024)', 'arXiv:2404.14219'], ['Gemma Team, Gemma: Open Models Based on Gemini Research and Technology (2024)', 'arXiv:2403.08295']],
  fresh: 'volatile', tsc: ['Current model names, sizes and capability claims.', 'Licences of specific small models.'],
  keywords: ['edge', 'on-device', 'efficient']
}),

E('open-weights-models', 'Open-Weights vs Closed Models', 'concept', L, {
  summary: 'Open-weights models publish their trained parameters for download and use under a licence; closed models are available only through a provider\'s service. "Open weights" is not the same as "open source".',
  short: '**Open weights**: you can download and run/adapt the model under its licence. **Closed**: access via API only. Licences vary widely, and "open source AI" has its own definition (OSI) that many open-weight releases do not meet.',
  plain: `Some AI models can be downloaded and run on your own machines — open-weights models. Others are only available through a company's service. Open weights give you control and privacy, but the licence terms differ and aren't always as free as the word "open" suggests.`,
  technical: `Open-weights releases publish parameters (and sometimes code), but training data and recipes may be undisclosed and licences may add use restrictions (field-of-use, size thresholds, attribution). The Open Source Initiative published an Open Source AI Definition (v1.0, 2024) with requirements beyond weights availability; whether a given release qualifies must be checked against current texts. Trade-offs vs closed APIs: control, privacy, customisation and cost structure versus capability, convenience and maintenance burden.`,
  aliases: ['open weights', 'open weight models', 'open source LLM', 'open-source AI', 'Llama licence', 'open vs closed models', 'self-hosted models', 'open source AI definition'],
  intents: ['choose between open and closed models', 'understand licences'],
  questions: ['What does open weights mean?', 'Is an open-weights model open source?', 'Open source vs closed source LLMs: which should I use?', 'Can I use open-weights models commercially?'],
  pre: ['large-language-models'], rel: ['local-ai', 'local-ai-vs-cloud-ai', 'fine-tuning', 'hugging-face', 'ai-governance', 'small-language-models'],
  vs: [['local-ai-vs-cloud-ai', 'A deployment decision that often follows the open/closed choice.']],
  tech: ['Hugging Face Hub', 'Llama family', 'Mistral family', 'Qwen family', 'OSI Open Source AI Definition'],
  patterns: ['Read the licence and acceptable-use policy before adoption.', 'Pin model revisions by hash.', 'Keep a fallback hosted model.', 'Scan downloaded artefacts and prefer safe formats.'],
  fails: ['Assuming commercial use is allowed.', 'Downloading unverified weights or pickled files from unknown sources.', 'Ignoring that data provenance is undisclosed.', 'Underestimating operating cost.'],
  fix: [['Unsure about licence', 'Have legal review; record the licence version at download.'], ['Supply-chain worry', 'Use safetensors, verify checksums, download from official organisations.']],
  guide: ['List requirements (privacy, cost, customisation).', 'Shortlist models; read licences.', 'Verify provenance and checksums.', 'Evaluate on your tasks.', 'Plan serving ([[model-serving-and-inference]]).'],
  when: 'Choose open weights when you need control, privacy or customisation; closed APIs when you need the strongest capability with minimal operations.',
  sources: [['Open Source Initiative, The Open Source AI Definition', 'opensource.org/ai'], ['Touvron et al., Llama 2: Open Foundation and Fine-Tuned Chat Models (2023)', 'arXiv:2307.09288'], ['Jiang et al., Mistral 7B (2023)', 'arXiv:2310.06825']],
  fresh: 'volatile', tsc: ['Licence terms of specific models.', 'Current OSI definition version and which releases qualify.', 'Which models are currently released as open weights.'],
  keywords: ['licence', 'download', 'self-host']
}),

// -------- Multimodal --------
E('vision-language-models', 'Vision-Language Models (VLMs)', 'concept', V, {
  summary: 'Vision-language models take images (and often video) together with text and answer questions, describe scenes, read documents and follow visual instructions.',
  short: 'A VLM pairs a **vision encoder with a language model** via a connector, so it can reason over images and text together. Strengths: description, OCR-like reading, chart/screenshot Q&A. Weaknesses: fine spatial detail, counting, and confident hallucination about image content.',
  plain: `A vision-language model can look at a picture and talk about it: describe it, answer questions about a chart, read text in a screenshot. Under the hood it converts the image into a form the language model can read alongside your words.`,
  technical: `Common architecture: a pre-trained image encoder (ViT/CLIP-style, [[vision-transformers]]) produces visual tokens; a projector or cross-attention maps them into the LLM\'s embedding space; the LLM generates text conditioned on both (Flamingo, Alayrac et al., 2022; BLIP-2, Li et al., 2023; LLaVA, Liu et al., 2023). Training typically involves image–text alignment then instruction tuning on visual instructions. Known issues: object hallucination, resolution limits, counting and spatial reasoning errors, and sensitivity to image crop/quality.`,
  aliases: ['VLM', 'VLMs', 'multimodal LLM', 'MLLM', 'image understanding model', 'LLaVA', 'vision language model', 'image to text model', 'visual question answering', 'VQA'],
  intents: ['pick a model for image+text tasks', 'diagnose visual hallucinations'],
  questions: ['What is a vision-language model?', 'How do VLMs read images?', 'Why does my VLM hallucinate objects?', 'Can a VLM read a chart or screenshot?'],
  pre: ['multimodal-ai', 'vision-transformers', 'large-language-models'], rel: ['contrastive-learning-clip', 'document-understanding-ai', 'computer-use-agents', 'vision-language-action-models', 'ai-evaluation'],
  vs: [['contrastive-learning-clip', 'CLIP embeds images and text for matching; VLMs generate text about images.'], ['document-understanding-ai', 'Document AI often adds OCR and layout steps that a general VLM may handle implicitly.']],
  tech: ['LLaVA family', 'BLIP-2', 'Hugging Face Transformers', 'provider multimodal APIs'],
  patterns: ['Send images at adequate resolution and crop regions of interest.', 'Ask for structured outputs and verify extracted values.', 'Combine OCR with a VLM for dense text.', 'Evaluate on your own image set.'],
  fails: ['Object hallucination.', 'Misreading small text or dense tables.', 'Counting errors.', 'Sending sensitive images to third parties.', 'Prompt injection through text embedded in images.'],
  fix: [['Wrong numbers read from a chart', 'Provide higher resolution or crop; cross-check with data when available.'], ['Invents details', 'Ask for what is visibly present only; require uncertainty statements; verify.']],
  guide: ['Define the visual task.', 'Test candidate models on 30–50 real images.', 'Optimise image size/cropping.', 'Validate outputs with rules or humans.', 'Review privacy ([[ai-privacy-and-security]]).'],
  when: 'Use for image/screenshot understanding, document and chart Q&A, accessibility description.',
  sources: [['Alayrac et al., Flamingo (2022)', 'arXiv:2204.14198'], ['Li et al., BLIP-2 (2023)', 'arXiv:2301.12597'], ['Liu et al., Visual Instruction Tuning (LLaVA) (2023)', 'arXiv:2304.08485']],
  fresh: 'evolving', keywords: ['image', 'visual question answering', 'screenshots']
}),

E('contrastive-learning-clip', 'Contrastive Learning and CLIP', 'model', V, {
  summary: 'CLIP learns a shared embedding space for images and text by training matching image–caption pairs to be close together, enabling zero-shot image classification and cross-modal search.',
  short: 'CLIP trains an **image encoder and a text encoder so matching pairs land close** in one vector space. That enables zero-shot classification by text prompts, image search by text, and serves as a building block in generators and VLMs.',
  plain: `CLIP learned from huge numbers of images with captions to put pictures and their descriptions near each other in a shared "meaning space". So you can search images with words, or classify images by comparing them with text labels you write.`,
  technical: `Radford et al. (2021) train dual encoders with a symmetric InfoNCE contrastive loss over in-batch image–text pairs. Zero-shot classification embeds label prompts and picks the nearest. Related: SimCLR (image-only contrastive learning), SigLIP-style sigmoid losses, and OpenCLIP reproductions. Limitations: bag-of-concepts behaviour, weak compositional and counting ability, and biases inherited from web data.`,
  aliases: ['CLIP', 'contrastive language-image pretraining', 'contrastive learning', 'InfoNCE', 'SigLIP', 'OpenCLIP', 'zero-shot image classification', 'image text embeddings', 'SimCLR', 'text to image search'],
  intents: ['search images by text', 'understand the building block behind multimodal models'],
  questions: ['What is CLIP?', 'What is contrastive learning?', 'How does zero-shot image classification work?', 'How do I do text-to-image search with embeddings?'],
  pre: ['embeddings', 'vision-transformers'], rel: ['vision-language-models', 'diffusion-models', 'multimodal-ai', 'self-supervised-learning', 'vector-databases'],
  vs: [['vision-language-models', 'VLMs generate language about images; CLIP produces comparable embeddings.'], ['embeddings', 'CLIP is an embedding model spanning two modalities.']],
  tech: ['OpenCLIP', 'Hugging Face Transformers', 'FAISS / vector databases'],
  patterns: ['Embed images and text once; search by cosine similarity.', 'Prompt ensembles for zero-shot labels ("a photo of a {label}").', 'Fine-tune or linear-probe for domain accuracy.', 'Store image embeddings in a vector index.'],
  fails: ['Poor on fine-grained or compositional queries.', 'Bias from web-scale training data.', 'Mixing embeddings from different CLIP checkpoints.', 'Assuming high similarity equals semantic correctness.'],
  fix: [['Search returns loosely related images', 'Use a stronger checkpoint, rerank, or add metadata filters.'], ['Zero-shot accuracy low', 'Try prompt templates or fine-tune a linear probe.']],
  guide: ['Choose one checkpoint and use it for all embeddings.', 'Embed and index.', 'Evaluate recall on labelled queries.', 'Add reranking if needed.'],
  when: 'Use for cross-modal retrieval and zero-shot labelling.',
  sources: [['Radford et al., Learning Transferable Visual Models From Natural Language Supervision (CLIP) (2021)', 'arXiv:2103.00020'], ['Chen et al., A Simple Framework for Contrastive Learning of Visual Representations (SimCLR) (2020)', 'arXiv:2002.05709'], ['van den Oord et al., Representation Learning with Contrastive Predictive Coding (2018)', 'arXiv:1807.03748']],
  fresh: 'evolving', keywords: ['image text embedding', 'zero-shot']
}),

E('speech-ai', 'Speech AI: Speech Recognition and Text-to-Speech', 'concept', V, {
  summary: 'Speech AI turns audio into text (automatic speech recognition) and text into audio (text-to-speech); modern systems use large neural models and can power voice assistants.',
  short: '**ASR** converts speech to text; **TTS** converts text to speech; voice assistants chain ASR → LLM → TTS or use end-to-end speech models. Accuracy varies with accent, noise and domain terms; voice cloning raises consent and fraud concerns.',
  plain: `Speech AI covers two directions: listening (turning spoken words into text) and talking (turning text into natural-sounding speech). Put them around a language model and you get a voice assistant.`,
  technical: `ASR models such as Whisper (Radford et al., 2022; large-scale weak supervision) and wav2vec 2.0 (Baevski et al., 2020, self-supervised) map audio to text, often with timestamps and optional diarisation by separate components. TTS uses neural vocoders and sequence models; some systems clone voices from short samples. Voice agents trade latency (streaming, endpointing, interruption handling) against quality. Evaluation uses word error rate (WER) on representative audio.`,
  aliases: ['ASR', 'speech to text', 'text to speech', 'TTS', 'Whisper', 'voice assistant', 'speech recognition', 'voice cloning', 'wav2vec', 'diarization', 'WER'],
  intents: ['transcribe audio', 'build a voice assistant', 'assess voice cloning risk'],
  questions: ['What is speech recognition?', 'How does Whisper work?', 'How do I build a voice assistant with an LLM?', 'What is word error rate?', 'Is voice cloning legal?'],
  pre: ['multimodal-ai', 'transformers'], rel: ['self-supervised-learning', 'ai-privacy-and-security', 'c2pa-content-provenance', 'ai-governance', 'multimodal-ai'],
  vs: [['multimodal-ai', 'Speech is one modality within the broader multimodal picture.']],
  tech: ['Whisper', 'wav2vec 2.0', 'streaming ASR services', 'neural TTS engines'],
  patterns: ['Streaming ASR with endpoint detection feeding an LLM, then streaming TTS.', 'Custom vocabulary lists for domain terms.', 'Diarisation for meeting transcripts.', 'Consent capture and disclosure for synthetic voices.'],
  fails: ['High WER on noisy audio, accents or jargon.', 'Latency making conversation feel unnatural.', 'Hallucinated text in silent segments.', 'Voice-clone fraud and consent violations.', 'Recording-consent law non-compliance.'],
  fix: [['Domain terms mistranscribed', 'Add vocabulary biasing or post-correct with a glossary.'], ['Laggy voice agent', 'Stream each stage, tune endpointing, shorten responses.']],
  guide: ['Collect representative audio.', 'Measure WER per condition.', 'Pick streaming vs batch.', 'Add consent and disclosure.', 'Protect recordings ([[ai-privacy-and-security]]).'],
  when: 'Use for transcription, captions, accessibility, voice interfaces.',
  sources: [['Radford et al., Robust Speech Recognition via Large-Scale Weak Supervision (Whisper) (2022)', 'arXiv:2212.04356'], ['Baevski et al., wav2vec 2.0 (2020)', 'arXiv:2006.11477']],
  fresh: 'evolving', keywords: ['audio', 'transcription', 'voice']
}),

E('document-understanding-ai', 'Document Understanding AI (OCR, Layout, Extraction)', 'concept', V, {
  summary: 'Document understanding combines OCR, layout analysis and language models to extract structured information from PDFs, scans and forms.',
  short: 'Pipeline options: **classical OCR + parser**, **layout-aware models**, or **VLM extraction**. Always validate extracted numbers and keep source references; sensitive documents need privacy controls.',
  plain: `Businesses run on documents — invoices, contracts, forms. Document AI reads them: it recognises the text, understands the layout (tables, headings, fields) and pulls out the data you need in a structured form.`,
  technical: `Approaches: OCR engines followed by rule/ML parsers; layout-aware transformers (LayoutLM, Xu et al., 2019); OCR-free end-to-end models (Donut, Kim et al., 2021); and general VLMs with structured output ([[vision-language-models]], [[structured-outputs]]). Evaluation metrics include field-level precision/recall and table structure accuracy. Typical failure points are scan quality, multi-column and table layouts, handwriting, and numeric misreads.`,
  aliases: ['OCR', 'document AI', 'intelligent document processing', 'IDP', 'invoice extraction', 'PDF data extraction', 'layout analysis', 'LayoutLM', 'table extraction', 'form understanding'],
  intents: ['extract data from PDFs and scans', 'choose between OCR and a VLM'],
  questions: ['How do I extract data from PDFs with AI?', 'What is document AI?', 'OCR vs vision-language model for documents?', 'How do I extract tables from scanned documents?'],
  pre: ['multimodal-ai'], rel: ['vision-language-models', 'structured-outputs', 'rag', 'chunking', 'ai-privacy-and-security', 'ai-evaluation'],
  vs: [['vision-language-models', 'General VLMs are flexible but need validation; dedicated pipelines can be more auditable.']],
  tech: ['Tesseract', 'LayoutLM', 'Donut', 'PDF parsers', 'provider document APIs'],
  patterns: ['Text-layer extraction first for digital PDFs; OCR for scans.', 'Structured output with field confidence/evidence.', 'Cross-field checks (totals add up).', 'Human review queue for low-confidence fields.'],
  fails: ['Numeric misreads.', 'Table structure lost.', 'Silent truncation of long documents.', 'Leaking sensitive documents to third-party services.'],
  fix: [['Wrong totals', 'Add arithmetic validation and human review for mismatches.'], ['Tables garbled', 'Use a layout-aware tool or higher resolution rendering.']],
  guide: ['Classify document types.', 'Pick pipeline per type.', 'Define a schema with evidence fields.', 'Validate with rules.', 'Measure field accuracy on a labelled set.'],
  when: 'Use for finance, legal, logistics and any document-heavy workflow.',
  sources: [['Xu et al., LayoutLM: Pre-training of Text and Layout for Document Image Understanding (2019)', 'arXiv:1912.13318'], ['Kim et al., OCR-free Document Understanding Transformer (Donut) (2021)', 'arXiv:2111.15664']],
  fresh: 'evolving', keywords: ['PDF', 'scan', 'invoice']
}),

E('video-generation-models', 'Video Generation and Video Understanding Models', 'concept', V, {
  summary: 'Video models generate or analyse moving images, typically by extending image diffusion or transformer methods across time. Quality, controllability and cost vary widely.',
  short: 'Video generation extends image generation with **temporal consistency**; video understanding samples frames or tokens over time. Current systems differ greatly in length, coherence and physical plausibility — verify capabilities from the vendor\'s documentation.',
  plain: `Video AI comes in two flavours: models that create video from text or images, and models that watch video and describe or answer questions about it. Both are harder than images because things must stay consistent across time.`,
  technical: `Generation commonly uses latent diffusion with spatio-temporal attention or diffusion transformers ([[diffusion-models]]), trained on large video–text datasets; understanding uses frame sampling plus vision encoders feeding a language model ([[vision-language-models]]). Products in this area change fast: OpenAI's Sora, for example, was discontinued as an app on 26 April 2026 and its API was scheduled to shut down on 24 September 2026 ([[sora-ai-video]]), so confirm that any service you plan to use still exists. Open-weight alternatives for physical-AI video exist, such as NVIDIA Cosmos ([[nvidia-cosmos]]). Open problems include long-range consistency, physical plausibility, text/hand rendering, evaluation (human preference dominates), compute cost, and provenance of synthetic media ([[c2pa-content-provenance]]).`,
  aliases: ['text to video', 'AI video generation', 'video diffusion', 'Sora', 'video understanding', 'video LLM', 'video captioning', 'world simulators'],
  intents: ['understand what video AI can and cannot do', 'assess risks of synthetic video'],
  questions: ['How does AI video generation work?', 'What is a video diffusion model?', 'Can AI understand video?', 'How do I tell if a video is AI-generated?'],
  pre: ['diffusion-models', 'multimodal-ai'], rel: ['world-models', 'sora-ai-video', 'nvidia-cosmos', 'c2pa-content-provenance', 'ai-governance', 'vision-language-models'],
  vs: [['diffusion-models', 'Image diffusion is the base; video adds temporal modelling and far higher cost.']],
  tech: ['video diffusion transformers', 'frame-sampling VLM pipelines'],
  patterns: ['Image-to-video for controllability.', 'Short clips stitched with consistent references.', 'Frame sampling plus transcript for video Q&A.', 'Embed provenance metadata/watermarks.'],
  fails: ['Temporal flicker and identity drift.', 'Physically implausible motion.', 'Missed events between sampled frames.', 'Deepfake misuse.'],
  fix: [['Characters change between shots', 'Use reference images and shorter clips.'], ['Video Q&A misses short events', 'Sample more frames around candidate moments or use event detection first.']],
  guide: ['Define the use and review capabilities from vendor docs.', 'Prototype with short clips.', 'Add provenance and disclosure.', 'Review legal/consent issues.'],
  when: 'Use for creative drafts and analysis with human review; avoid unverified claims about capabilities.',
  sources: [['Ho et al., Video Diffusion Models (2022)', 'arXiv:2204.03458'], ['Provider technical reports for current video models (identify current documents)', null]],
  fresh: 'volatile', tsc: ['Model names, durations, resolutions and capabilities.', 'Detection and watermarking reliability claims.'],
  keywords: ['text to video', 'temporal']
})
];
