import json
C=[]  # concepts: (id, terms, [(page, boost)])
def c(i,terms,*pages): C.append({"id":"v3-"+i,"terms":terms,"pages":[{"id":p,"boost":b} for p,b in pages]})
I=[]
def it(i,phrases,*pages): I.append({"id":"v3-"+i,"phrases":phrases,"pages":[{"id":p,"boost":b} for p,b in pages]})

# ---------------- concepts ----------------
c("test-time-compute",["test time compute","inference time compute","inference time scaling","test time scaling","inference scaling"],("test-time-compute",34))
c("reasoning-models",["reasoning model","reasoning models","thinking model","thinking models","reasoning llm","reasoning llms","large reasoning model"],("reasoning-models",30))
c("cot",["chain of thought","cot","step by step prompting","think step by step"],("chain-of-thought",30))
c("hidden-reasoning",["hidden reasoning","hidden chain of thought","reasoning trace","reasoning traces","reasoning tokens","reasoning summary","reasoning summaries","private reasoning","hidden thoughts"],("reasoning-transparency",36))
c("self-consistency",["self consistency","majority voting","majority vote"],("self-consistency",34))
c("best-of-n",["best of n","rejection sampling","n best","sample several answers","pick the best of several"],("best-of-n-sampling",34))
c("search-reasoning",["tree of thoughts","tree search reasoning","mcts","monte carlo tree search","beam search reasoning"],("search-over-reasoning",34))
c("orm",["outcome reward model","outcome reward models","outcome supervision","outcome based reward","final answer verifier"],("outcome-reward-model",34))
c("prm",["process reward model","process reward models","process supervision","step level reward","grade each step","step by step verifier"],("process-reward-model",34))
c("prm-vs-orm",["prm vs orm","orm vs prm","process vs outcome","process or outcome reward","outcome vs process","process supervision vs outcome supervision"],("prm-vs-orm",46))
c("rlvr",["grpo","rlvr","group relative policy optimization","verifiable rewards","rule based rewards"],("reinforcement-learning-for-reasoning",34))
c("thinking-budget",["thinking budget","reasoning effort","budget tokens","extended thinking","thinking budgets"],("thinking-budgets",34))
c("constrained",["constrained decoding","guided generation","guided decoding","logit masking","constrained generation","structured generation"],("constrained-decoding",34))
c("structured",["structured output","structured outputs","json mode","json output","valid json","schema output","enforce a schema"],("structured-outputs",30),("constrained-decoding",8))
c("grammar",["grammar constrained","grammar guided","grammar guided generation","cfg decoding","regex constrained","regex constrained generation","grammar sampling"],("grammar-guided-generation",34))
c("gbnf",["gbnf","llama cpp grammar","json schema to gbnf"],("gbnf-grammars",36))
c("json-schema",["json schema"],("json-schema",28))
c("sampling",["temperature setting","llm temperature","temperature in an llm","temperature parameter","top p","top k","nucleus sampling","greedy decoding","beam search","decoding strategies","sampling parameters","repetition penalty","min p"],("sampling-and-decoding",30))
c("vla",["vla","vla model","vla models","vision language action","rt 2","openvla","pi0","robot foundation model","language conditioned robot","robots that follow natural language"],("vision-language-action-models",36))
c("world-models",["world model","world models","dreamer","jepa","model based reinforcement learning","learned simulator","learned simulators"],("world-models",34))
c("embodied",["embodied ai","embodied intelligence","physical ai","robot learning"],("embodied-ai",30))
c("imitation",["imitation learning","behavior cloning","behaviour cloning","dagger","learning from demonstration","learn from demonstrations","teleoperation data","diffusion policy"],("imitation-learning",34))
c("sim2real",["sim to real","sim2real","domain randomization","domain randomisation","reality gap"],("sim-to-real-transfer",34))
c("benchmarks",["benchmark","benchmarks","leaderboard","leaderboards","benchmark scores"],("benchmarks-and-leaderboards",26))
c("contamination",["contamination","data contamination","test set leakage","trained on the test","benchmark leakage","train on the test"],("benchmark-contamination",36))
c("judge",["llm as a judge","llm judge","model graded","ai judge","gpt as judge","g eval","mt bench"],("llm-as-a-judge",34))
c("arena",["chatbot arena","lmarena","elo rating","elo ratings","bradley terry","human preference evaluation"],("human-preference-evaluation",34))
c("mmlu",["mmlu","mmlu pro","gpqa"],("mmlu",36))
c("humaneval",["humaneval","pass at k","pass k","mbpp","evalplus"],("humaneval",34))
c("swebench",["swe bench","swe agent"],("swe-bench",36))
c("gsm8k",["gsm8k","math benchmark","aime"],("gsm8k-and-math-benchmarks",34))
c("metrics",["f1 score","precision and recall","bleu","rouge","perplexity","roc auc","confusion matrix"],("evaluation-metrics-for-ai",30))
c("rag-eval",["rag evaluation","evaluate rag","ragas","faithfulness","recall at k","context precision"],("rag-evaluation",34))
c("agent-eval",["agent evaluation","evaluate an agent","evaluate agents","tau bench","agentbench","trajectory evaluation"],("agent-evaluation",34))
c("a2a",["a2a","agent2agent","agent to agent","agent card","a2a protocol"],("a2a-protocol",34))
c("a2a-vs-mcp",["a2a vs mcp","mcp vs a2a","a2a and mcp","mcp and a2a","a2a versus mcp"],("a2a-vs-mcp",46))
c("agent-protocols",["agent protocols","agent protocol","agent interoperability","agent communication standards"],("agent-protocol-landscape",34))
c("mcp-security",["mcp security","secure mcp","mcp risks","tool poisoning","malicious mcp","mcp permissions","mcp authorization"],("mcp-security",38))
c("langgraph",["langgraph"],("langgraph",36))
c("dspy",["dspy"],("dspy",36))
c("crewai",["crewai","crew ai"],("crewai",36))
c("autogen",["autogen","ag2","autogen studio"],("autogen",36))
c("semantic-kernel",["semantic kernel"],("semantic-kernel",36))
c("agents-sdk",["openai agents sdk","agents sdk"],("openai-agents-sdk",36))
c("agent-frameworks",["agent framework comparison","which agent framework","best agent framework","langchain alternatives","framework comparison","langgraph vs","crewai vs","autogen vs"],("agent-frameworks-compared",44))
c("vllm",["vllm","pagedattention","paged attention","continuous batching"],("vllm",40))
c("llamacpp",["llama cpp","llamacpp","gguf"],("llama-cpp",38))
c("ollama",["ollama"],("ollama",36))
c("onnx",["onnx","onnx runtime","onnxruntime","execution provider","transformers js"],("onnx-runtime",36))
c("pytorch",["pytorch","torch compile","autograd","pytorch vs tensorflow","tensorflow vs pytorch"],("pytorch",34))
c("runtimes",["ollama vs","vllm vs","llama cpp vs","which inference engine","self host llm","self hosted llm"],("local-runtimes-compared",44))
c("alphafold",["alphafold","protein folding","protein structure prediction","plddt","esmfold"],("alphafold",36))
c("pinn",["pinn","pinns","physics informed","neural operator","neural operators"],("physics-informed-neural-networks",36))
c("weather",["graphcast","pangu weather","fourcastnet","aifs","ai weather","weather forecasting model"],("ai-weather-forecasting",36))
c("drug",["drug discovery","virtual screening","admet","molecule generation","generative chemistry"],("ai-drug-discovery",34))
c("materials",["materials discovery","gnome","interatomic potential","materials informatics","new materials"],("ai-materials-discovery",34))
c("ai4science",["ai for science","scientific machine learning","sciml","ai4science","surrogate model","surrogate models"],("ai-for-science",34))
c("supervised",["supervised learning","classification and regression","labelled data","labeled data","classification vs regression"],("supervised-learning",30))
c("unsupervised",["unsupervised learning","clustering","k means","kmeans"],("unsupervised-learning",30))
c("selfsup",["self supervised","self supervised learning","masked language modeling","masked language modelling","pretext task"],("self-supervised-learning",32))
c("neural-nets",["neural network","neural networks","neural net","activation function","multilayer perceptron"],("neural-networks",24))
c("deep-learning",["deep learning"],("deep-learning",22))
c("backprop",["backpropagation","backprop","gradient descent","learning rate","adam optimizer","loss function","sgd"],("backpropagation-and-gradient-descent",34))
c("overfit",["overfitting","overfit","underfitting","regularization","regularisation","dropout","weight decay","bias variance","generalization gap","early stopping"],("overfitting-and-regularization",34))
c("transfer",["transfer learning","pretrained model","pre trained model","feature extraction","domain adaptation","catastrophic forgetting"],("transfer-learning",30))
c("rl",["reinforcement learning","exploration vs exploitation","reward function","policy gradient"],("reinforcement-learning",24))
c("mdp",["markov decision process","mdp","bellman equation","pomdp","value function"],("markov-decision-processes",34))
c("ppo",["proximal policy optimization","actor critic","trpo","ppo reinforcement learning","ppo rl","ppo algorithm","ppo rlhf","ppo training"],("proximal-policy-optimization",36))
c("dqn",["dqn","deep q network","deep q networks","q learning","experience replay"],("deep-q-networks",34))
c("cnn",["convolutional neural network","convolutional neural networks","convnet","resnet","cnn deep learning","cnn image","cnn model","cnn architecture","cnn neural"],("convolutional-neural-networks",34))
c("rnn",["rnn","lstm","gru","recurrent neural network","long short term memory","vanishing gradient"],("recurrent-neural-networks",34))
c("vit",["vit","vision transformer","vision transformers","swin transformer"],("vision-transformers",34))
c("cnn-vs-vit",["cnn vs vit","cnn vs vision transformer","convnet vs transformer","vit vs resnet","vit vs cnn","cnn or vit"],("cnn-vs-vision-transformer",46))
c("moe",["mixture of experts","moe","sparse mixture","switch transformer","mixtral"],("mixture-of-experts",34))
c("ssm",["state space model","state space models","mamba model","mamba architecture","mamba llm","mamba ssm","ssm mamba","mamba 2","selective state space","structured state space"],("state-space-models",36))
c("ssm-vs",["mamba vs transformer","transformer vs mamba","ssm vs transformer","attention vs ssm","transformer alternatives","state space vs transformer","mamba transformer"],("transformers-vs-state-space-models",46))
c("diffusion",["diffusion model","diffusion models","stable diffusion","latent diffusion","ddpm","denoising diffusion","classifier free guidance","text to image generation","text to image generators"],("diffusion-models",34))
c("gan",["gan","gans","generative adversarial","mode collapse","stylegan"],("generative-adversarial-networks",34))
c("vae",["vae","variational autoencoder","autoencoder","latent space","vq vae"],("variational-autoencoders",34))
c("gnn",["gnn","gnns","graph neural network","graph neural networks","message passing","graph convolutional"],("graph-neural-networks",34))
c("enc-dec",["encoder decoder","decoder only","encoder only","bert vs gpt","gpt vs bert","t5 model"],("encoder-decoder-vs-decoder-only",40))
c("kv",["kv cache","key value cache","grouped query attention","gqa","multi query attention","prefix caching"],("kv-cache",36))
c("flash",["flashattention","flash attention","flash attn"],("flash-attention",36))
c("pos",["positional encoding","position embeddings","rope","rotary position embedding","rotary embeddings","alibi","token order","context extension","position interpolation"],("positional-encoding",34))
c("scaling",["scaling laws","scaling law","chinchilla","compute optimal","tokens per parameter"],("scaling-laws",34))
c("instruct",["instruction tuning","instruct model","base model vs chat model","base vs instruct","supervised fine tuning","sft"],("instruction-tuning",34))
c("lora",["lora","qlora","peft","low rank adaptation","adapter fine tuning","parameter efficient"],("lora-and-peft",36))
c("lora-vs-full",["lora vs full","lora or full","full fine tuning vs lora","lora vs fine tuning","peft vs full"],("lora-vs-full-fine-tuning",46))
c("quant",["quantization","quantisation","gptq","awq","int4","4 bit","8 bit","k quants"],("quantization",34))
c("distill",["distillation","distill","distilled","teacher student","distilbert"],("knowledge-distillation",34))
c("spec",["speculative decoding","speculative sampling","draft model","assisted generation","medusa decoding"],("speculative-decoding",36))
c("slm",["slm","slms","small language model","small language models","small llm","on device model","on device models"],("small-language-models",34))
c("openweights",["open weights","open weight","open source llm","open source vs closed","closed source llm","open vs closed models","open source vs closed llms"],("open-weights-models",34))
c("vlm",["vlm","vlms","vision language model","vision language models","llava","multimodal llm","visual question answering","image understanding model"],("vision-language-models",34))
c("clip",["clip embeddings","clip model","openai clip","contrastive learning","zero shot image classification","openclip","siglip","image text embeddings","text to image search"],("contrastive-learning-clip",34))
c("speech",["speech recognition","speech to text","text to speech","whisper","asr","tts","voice assistant","word error rate","voice cloning","transcribe audio","transcription","wer"],("speech-ai",34))
c("docai",["document ai","ocr","invoice extraction","pdf extraction","extract data from pdf","extract data from pdfs","table extraction","intelligent document processing","layoutlm"],("document-understanding-ai",34))
c("video",["video generation","text to video","video diffusion","ai video"],("video-generation-models",34))
c("alignment",["ai alignment","alignment problem","value alignment","scalable oversight","outer alignment"],("ai-alignment",32))
c("prefopt",["preference optimization","preference optimisation","preference tuning","preference data","chosen and rejected","kto","orpo","simpo"],("preference-optimization",34))
c("dpo",["dpo loss","dpo training","dpo beta","dpo trainer","direct preference optimization","direct preference optimisation","dpo algorithm","what is dpo","dpo model","dpo alignment"],("dpo",40))
c("dpo-vs",["dpo vs rlhf","rlhf vs dpo","dpo vs ppo","ppo vs dpo","dpo or rlhf","dpo versus ppo","dpo or ppo"],("dpo-vs-rlhf",48))
c("rlhf",["rlhf","reinforcement learning from human feedback","reward model training","human feedback training","kl penalty"],("rlhf",34))
c("cai",["constitutional ai","rlaif","ai feedback","self critique","principle based alignment"],("constitutional-ai-and-rlaif",34))
c("rewardhack",["reward hacking","specification gaming","goodharts law","goodhart","reward overoptimization","reward over optimization","gaming the metric","exploits the scoring","exploits the reward"],("reward-hacking",36))
c("sycophancy",["sycophancy","sycophantic","flattery","yes man ai","agrees with everything","tells me what i want to hear","telling users what they want to hear"],("sycophancy",38))
c("redteam",["red teaming","red team","adversarial testing","jailbreak testing","automated red teaming"],("red-teaming",34))
c("guardrails",["guardrails","guardrail","llama guard","nemo guardrails","content moderation","output validation"],("ai-guardrails",34))
c("interp",["interpretability","mechanistic interpretability","sparse autoencoders","explainable ai","xai","shap lime","activation patching"],("mechanistic-interpretability",34))
c("bias",["algorithmic bias","ai bias","bias in ai","fairness metric","fairness metrics","demographic parity","equalized odds","bias audit","ai fairness","disparate impact"],("ai-bias-and-fairness",34))
c("governance",["ai governance","responsible ai","ai policy","ai risk management","ai compliance","ai accountability","ai impact assessment","trustworthy ai"],("ai-governance",32))
c("euact",["eu ai act","ai act","european ai regulation","regulation 2024 1689","high risk ai","prohibited ai practices","gpai","banned in europe"],("eu-ai-act",36))
c("nist",["nist ai rmf","ai rmf","nist ai","nist ai 100 1","generative ai profile"],("nist-ai-rmf",36))
c("iso",["iso 42001","iso iec 42001","ai management system","iso ai standard"],("iso-iec-42001",36))
c("modelcards",["model card","model cards","datasheets for datasets","system card","ai documentation","dataset card"],("model-cards",34))
c("c2pa",["c2pa","content credentials","content provenance","ai watermarking","synthid","deepfake detection","detect ai generated","label ai generated"],("c2pa-content-provenance",36))
c("owasp",["owasp llm","owasp top 10 for llm","llm01","owasp genai","excessive agency","insecure output handling"],("owasp-llm-top-10",36))
c("mlops",["mlops","llmops","ml pipeline","model lifecycle","ci cd for ml"],("mlops",34))
c("serving",["model serving","llm serving","inference server","time to first token","ttft","tokens per second","inference optimization","inference endpoint","serve an llm","serving an llm"],("model-serving-and-inference",34))
c("gpus",["gpu for ai","vram","cuda","tpu","hbm","ai accelerators","which gpu","what gpu","memory bandwidth","tensor cores"],("gpus-and-ai-accelerators",34))
c("distributed",["distributed training","fsdp","zero optimizer","deepspeed","megatron","data parallel","tensor parallelism","pipeline parallelism","multi gpu training","model sharding"],("distributed-training",36))
c("observability",["llm observability","llm monitoring","tracing llm","llm tracing","opentelemetry","langsmith","langfuse","prompt logging","token usage tracking","monitor an llm","monitoring llm","debug llm app"],("llm-observability",34))
c("drift",["model drift","data drift","concept drift","model decay","training serving skew","psi","drift monitoring","performance degradation"],("model-drift-and-monitoring",34))
c("promptcache",["prompt caching","context caching","cached tokens","cache control","prompt cache"],("prompt-caching",36))
c("cost",["llm cost","reduce llm cost","llm costs","token cost","api cost","model routing","frugalgpt","batch api","cheaper llm","ai cost","token spend","llm pricing"],("llm-cost-optimization",34))
c("mlflow",["mlflow","experiment tracking","track ml experiments","model registry","wandb","weights and biases"],("mlflow",36))
c("ray",["ray serve","ray train","rllib","kuberay","anyscale","ray tune","distributed python"],("ray",34))
c("pgvector",["pgvector","postgres vector","postgres embeddings","hnsw index","ivfflat","vector search in postgres"],("pgvector",36))
c("hybrid",["hybrid search","reranker","reranking","rerank","bm25","reciprocal rank fusion","cross encoder","colbert"],("hybrid-search-and-reranking",34))
c("graphrag",["graphrag","graph rag","knowledge graph rag","knowledge graph for retrieval","knowledge graph retrieval","multi hop retrieval","community summaries"],("graph-rag",36))
c("agentic-rag",["agentic rag","self rag","corrective rag","adaptive rag","iterative retrieval","query decomposition","multi hop rag"],("agentic-rag",36))
c("ctx-eng",["context engineering","context compaction","context management","context rot","manage context for agents"],("context-engineering",38))
c("react",["react pattern","react agent","react prompting","reason and act","agent loop","thought action observation"],("react-agent-pattern",44))
c("planning",["agent planning","plan and execute","task decomposition","plan and solve","reflexion","replanning"],("agent-planning",34))
c("computer-use",["computer use","browser agent","browser agents","web agents","gui agents","operator agent","control my computer","operate my browser","webarena","osworld"],("computer-use-agents",36))
c("sandbox",["sandbox","sandboxing","code interpreter","gvisor","firecracker"],("code-execution-sandboxing",34))

# ---------------- intents ----------------
it("invalid-json",["invalid json","returning invalid json","broken json","json parse error","llm returns json with extra text","force valid json","output valid json","valid json output","enforce json","guarantee json","json from a model","get json from","force an llm to output"],("structured-outputs",42),("constrained-decoding",30),("structured-output-methods-compared",14))
it("truncated-reasoning",["answer get cut off","answer cut off","response cut off","output cut off","truncated output","output truncated","empty final answer"],("thinking-budgets",34),("reasoning-models",24))
it("reasoning-cost",["why do reasoning models cost more","reasoning models cost more","reasoning tokens cost","reasoning model cost","reasoning model expensive"],("reasoning-models",36),("test-time-compute",30),("thinking-budgets",30))
it("repetition",["repeat itself","repeating itself","repeats itself","repeats phrases","repetition loop","repetitive output","stop repeating"],("sampling-and-decoding",42))
it("loss-nan",["loss is nan","nan loss","loss nan","loss not decreasing","loss exploding","training diverges","loss does not decrease","loss stuck"],("backpropagation-and-gradient-descent",42))
it("overfit-symptoms",["model overfit","overfits","training accuracy high","test accuracy low","good on training bad on test","does well on training data","poor generalization","validation loss rising","validation loss increasing","memorizing training data"],("overfitting-and-regularization",42))
it("worse-over-time",["model got worse","model getting worse","worse over time","accuracy dropped after deployment","degrades after launch","degrade after launch","model degradation","performance dropped in production","model degrades"],("model-drift-and-monitoring",42))
it("gpu-oom",["out of memory","cuda out of memory","oom","gpu memory","run out of vram","not enough vram","vram requirements","how much vram","how much gpu memory"],("model-serving-and-inference",28),("gpus-and-ai-accelerators",28),("kv-cache",24),("quantization",20),("vllm",16))
it("cache-miss",["cache not hitting","cache miss","cache hit rate","cheaper repeated prompts","long system prompt cost","repeated prompt cost","cheap across requests","repeated prefix","same prefix"],("prompt-caching",42))
it("agrees-everything",["agree with everything","agrees with everything","flatters me","caves to pushback","changes its answer when i push back","yes man"],("sycophancy",44))
it("sim-fails-real",["works in simulation","fails on the real robot","fails on hardware","sim to real gap","works in sim","simulation but fails","real robot fails"],("sim-to-real-transfer",46))
it("agent-loops",["loops forever","looping forever","infinite loop agent","agent loops","agent stuck in a loop","agent keeps looping","repeats the same tool call","never stops","runaway agent","step limit"],("react-agent-pattern",36),("ai-agents",20),("agentic-workflows",20),("agent-planning",14))
it("rag-wrong-passages",["wrong passages","retrieval returning wrong","retrieval returns irrelevant","irrelevant chunks","rag retrieval wrong","poor retrieval","rag gives wrong answers"],("hybrid-search-and-reranking",30),("rag-evaluation",30),("chunking",20))
it("vlm-hallucinate",["hallucinate objects","hallucinates objects in images","image hallucination","vlm hallucination","describes things that are not in the image","misreads image text"],("vision-language-models",46))
it("quant-quality",["after quantizing","after quantization","quantized model worse","quantization quality","quality dropped after quantiz","quantised model worse","4 bit quality"],("quantization",46))
it("langchain-upgrade",["after upgrading langchain","langchain upgrade","langchain deprecated","langchain import error","langchain breaking changes","langchain code broke"],("langchain",40),("agent-frameworks-compared",20))
it("eval-not-reproduce",["scores do not reproduce","cannot reproduce benchmark","reproduce benchmark scores","evaluation scores differ","different benchmark scores","scores differ from paper","evaluation not reproducible"],("benchmarks-and-leaderboards",36),("ai-evaluation",20),("llm-as-a-judge",18))
it("lora-practical",["adapter barely changes","lora has no effect","lora not working","lora rank","what rank for lora","lora hyperparameters","lora learning rate","lora memory","reduce memory for fine tuning","fine tune on one gpu","fine tune on a single gpu","fine tune with limited gpu","fine tune with limited memory","fine tune on consumer gpu","how does lora"],("lora-and-peft",46),("lora-vs-full-fine-tuning",20))
it("bench-vs-product",["high on benchmarks but fails","benchmark score does not match","benchmarks do not reflect","benchmarks fail in production","good benchmarks bad results","fails in my product"],("llm-benchmarks-vs-task-evals",42),("benchmark-contamination",28),("benchmarks-and-leaderboards",24))
it("mcp-perms",["too many permissions","asked for permissions","excessive permissions","how to secure mcp","secure an mcp server","securing mcp","is mcp secure","is mcp safe","mcp safe to install","install community mcp"],("mcp-security",46))
it("multi-gpu",["scales poorly","poor scaling","multi gpu","multiple gpus","across multiple gpus","several gpus","multi node training","train on many gpus","fine tune on multiple gpus"],("distributed-training",42))
it("judge-bias",["prefers longer answers","length bias","verbosity bias","position bias","judge bias","biases of llm judges","grade answers with an llm","grade model outputs","using gpt to grade","use gpt to grade","ai to grade","llm to grade","score outputs automatically","gpt to grade"],("llm-as-a-judge",46))
it("ollama-conn",["connection refused","port 11434","ollama not working","ollama api","call ollama","ollama server"],("ollama",40))
it("token-order",["order of tokens","word order","sequence order","how transformers know order","positions in transformers","how do models know the order"],("positional-encoding",40))
it("moe-routing",["route tokens","routes tokens","router in moe","expert routing","active parameters","few active parameters","many experts"],("mixture-of-experts",42))
it("clip-align",["align images and text","images and text embeddings","image and text in the same space","shared embedding space","search images using","search images by text","image search with text"],("contrastive-learning-clip",42))
it("rag-eval-e2e",["evaluate a rag","rag evaluated","how to test rag","testing a rag","rag test set","measure rag quality","rag quality","rag metrics","measure retrieval quality","evaluate a rag system"],("rag-evaluation",46))
it("agents-plan",["agents plan","how do agents plan","agent plan multi step","multi step tasks","break a goal into sub tasks","break down tasks","decompose tasks","task breakdown agents"],("agent-planning",42))
it("which-alignment",["dpo or ppo","dpo or rlhf","which alignment method","choose an alignment method","align my model","preference tuning method","should i use dpo"],("dpo-vs-rlhf",48),("dpo",20),("rlhf",16))
it("is-dpo-rl",["is dpo reinforcement learning","is dpo rl","dpo reinforcement learning","dpo a form of reinforcement learning"],("dpo",56),("preference-optimization",32),("dpo-vs-rlhf",30))
it("need-framework",["do i need an agent framework","do i need a framework","need a framework for agents","agent framework or direct","agent framework should i use","which framework for agents","framework for ai agents","framework for llm apps"],("agent-frameworks-compared",42),("choosing-an-agent-framework",22),("framework-vs-direct-api",22))
it("lora-or-full",["lora or full","full fine tuning or lora","lora or fine tune","full fine tune","fine tune with lora or"],("lora-vs-full-fine-tuning",48))
it("bias-test",["test for bias","test an ai system for bias","bias in my model","audit for bias","audit a model for bias","check for bias","which fairness","measure fairness","evaluate fairness"],("ai-bias-and-fairness",46))
it("eval-agent",["evaluate an ai agent","test an agent","test my agent","agent testing","measure agent","agent reliability","agent benchmark"],("agent-evaluation",46))
it("cpu-only",["on cpu","cpu only","without a gpu","no gpu","on a laptop","on my laptop","on a mac","apple silicon","run an llm on cpu","run llm on cpu","run llm locally on a mac"],("llama-cpp",32),("local-runtimes-compared",28),("ollama",24),("local-ai",16),("quantization",16))
it("monitor-llm",["monitor an llm","monitor llm application","monitor an ai application","llm application in production","monitoring ai in production","production monitoring llm","track token spend","log prompts","log llm calls","tracing prompts","tracking prompts"],("llm-observability",46),("model-drift-and-monitoring",20),("llm-cost-optimization",20))
it("improve-retrieval",["improve rag retrieval","rag retrieval accuracy","improve retrieval accuracy","better rag retrieval","retrieval accuracy","retrieval quality","keyword plus semantic retrieval"],("hybrid-search-and-reranking",42),("rag-evaluation",24),("chunking",20))
it("robot-demos",["learn from demonstrations","robot learn from demonstrations","teach a robot","show a robot","by demonstration","demonstrations to a robot","teach a robot arm","robot arm by showing"],("imitation-learning",46))
it("kg-retrieval",["build a knowledge graph","knowledge graph from documents","graph for rag"],("graph-rag",46))
it("redteam-app",["red team an llm","red team my app","red team a chatbot","test chatbot for abuse","adversarial testing of chatbots","jailbreak my own app","pen test llm","penetration testing llm","security testing llm"],("red-teaming",46))
it("track-experiments",["track experiments","track training runs","compare training runs","log experiments"],("mlflow",42),("mlops",20))
it("run-code-safely",["run code safely","run generated code","run model generated code","execute generated code","run llm generated code","safely execute code","code from an llm","sandbox code","sandbox for agents","isolation for agent code","stop a model from reading private files"],("code-execution-sandboxing",46))
it("pick-lr",["pick a learning rate","choose a learning rate","tune learning rate","how to choose learning rate","learning rate too high","learning rate schedule"],("backpropagation-and-gradient-descent",42))
it("label-ai-images",["label ai generated images","label ai images","watermark ai images","mark ai generated content","tag ai generated","disclose ai generated content","detect ai generated images","is this image ai generated"],("c2pa-content-provenance",46))
it("vision-backbone",["vision backbone","image model for small dataset","image classification small dataset","cnn or transformer for images","backbone for small datasets","which image model","edge device vision model"],("cnn-vs-vision-transformer",42),("convolutional-neural-networks",24),("transfer-learning",24))
it("serve-many-users",["serve an open model","serve open models","many users","multiple users","concurrent users","high throughput serving","self hosted inference","self host an llm","self hosting llm","host an open model","production inference server"],("vllm",34),("local-runtimes-compared",36),("model-serving-and-inference",24))
it("gpu-7b",["run a 7b model","7b model","13b model","70b model","gpu for llm","gpu do i need","gpu requirements","hardware requirements llm","memory for a 7b"],("gpus-and-ai-accelerators",34),("quantization",28),("local-ai",20),("local-runtimes-compared",16))
it("choose-llm",["choose an llm","pick an llm","which llm","select a model for my use case","choose a model for my use case","how to choose a model","choose a model","model selection","evaluate llms for my use case","which model should i use"],("llm-benchmarks-vs-task-evals",38),("benchmarks-and-leaderboards",24),("ai-evaluation",16))
it("dl-framework",["framework for deep learning","deep learning framework","pytorch or tensorflow","tensorflow or pytorch","which deep learning framework","library for neural networks","framework to train models"],("pytorch",46))
it("metric-choice",["which metric","what metric","choose a metric","metric for classification","metrics for classification","metric for summarization","accuracy or f1","evaluation metric","evaluation metrics","what does f1","f1 score tell"],("evaluation-metrics-for-ai",46))
it("graph-vs-plain",["graphrag vs rag","graphrag or plain rag","graph rag vs rag","plain rag or graph","when do i need a knowledge graph","knowledge graph or vector"],("graph-rag",42),("rag",10))
it("pgvector-or",["pgvector or","pgvector vs","vector database or postgres","postgres or a vector database"],("pgvector",42),("vector-databases",20))
it("risk-standard",["standard for ai risk","ai risk framework","which standard","ai risk management standard","framework for ai risk","follow for ai risk"],("nist-ai-rmf",30),("iso-iec-42001",30),("ai-governance",24))
it("mcp-or-a2a",["mcp or a2a","a2a or mcp","use mcp or a2a","mcp or agent to agent"],("a2a-vs-mcp",52))
it("protocols-compared",["mcp vs a2a vs function calling","protocols compared","which agent protocol","agent protocol stack"],("agent-protocol-landscape",42))
it("reasoning-vs",["reasoning model vs regular","reasoning vs regular","reasoning vs standard","reasoning vs non reasoning","thinking vs non thinking","reasoning model or regular","reasoning model or standard","should i use a reasoning model","when to use a reasoning model","regular llm vs reasoning","reasoning model vs llm"],("reasoning-vs-standard-models",50),("reasoning-models",16))
it("json-mode-vs",["json mode vs structured","json mode or","structured outputs vs json mode","best way to get json","way to get structured","which structured output","structured output method","function calling or structured"],("structured-output-methods-compared",48),("structured-outputs",16))
it("bench-vs-custom",["benchmarks vs custom","benchmarks vs evals","custom evals vs benchmarks","benchmark or custom eval","build my own evals","own evals","custom evaluation set","task specific eval"],("llm-benchmarks-vs-task-evals",48))
it("quant-vs-distill",["quantization vs distillation","quantisation vs distillation","distillation vs quantization","quantize or distill","distill or quantize"],("quantization",32),("knowledge-distillation",32))
it("sup-vs-unsup",["supervised vs unsupervised","supervised or unsupervised","supervised versus unsupervised"],("supervised-learning",36),("unsupervised-learning",36))
it("gan-vs-diff",["gan vs diffusion","diffusion vs gan","gans vs diffusion","gan or diffusion"],("generative-adversarial-networks",36),("diffusion-models",36))
it("ppo-vs-dqn",["ppo vs dqn","dqn vs ppo"],("proximal-policy-optimization",36),("deep-q-networks",36))
it("nist-vs-iso",["nist vs iso","iso 42001 vs nist","nist ai rmf vs iso","iso vs nist"],("nist-ai-rmf",40),("iso-iec-42001",40))
it("lc-vs-li",["langchain vs llamaindex","langchain vs llama index","llamaindex vs langchain","langchain or llamaindex"],("langchain",38),("llamaindex",38),("agent-frameworks-compared",30))
it("rag-vs-fine-tuning-guard",["lora or full fine tuning"],("lora-vs-full-fine-tuning",48))
it("how-tokens-words",["how do language models turn probabilities into words","turn probabilities into words","probabilities into tokens"],("sampling-and-decoding",44))
it("how-train-weights",["how do neural networks learn","neural networks learn weights","how networks learn"],("backpropagation-and-gradient-descent",40),("neural-networks",30))


# ---- round 2: fixes driven by the TUNING set only (holdout deliberately untouched) ----
c("cnn-context",["cnn deep learning","cnn image","cnn model","cnn architecture","cnn neural","cnn vs","what is a cnn"],("convolutional-neural-networks",52))
c("ppo-context",["ppo reinforcement learning","ppo rl","ppo algorithm","ppo rlhf","ppo training","ppo vs","what is ppo"],("proximal-policy-optimization",52))
c("runtimes-vs",["ollama vs vllm","vllm vs ollama","vllm vs llama cpp","llama cpp vs ollama","ollama vs llama cpp","llama cpp vs vllm","which runtime"],("local-runtimes-compared",56))
c("frameworks-vs",["langgraph vs crewai","crewai vs langgraph","langgraph vs autogen","autogen vs langgraph","crewai vs autogen","autogen vs crewai"],("agent-frameworks-compared",56))
c("jsonmode-vs",["json mode vs structured outputs","json mode vs structured output","structured outputs vs json mode"],("structured-output-methods-compared",56))
c("token-order-ctx",["token order","handle token order","know token order","how transformers handle token order"],("positional-encoding",50))
it("rag-eval-more",["rag system evaluated","evaluated end to end","rag system is evaluated","evaluating a rag","evaluating rag","end to end rag evaluation"],("rag-evaluation",50))
it("one-gpu",["model on one gpu","on one gpu","on a single gpu","on 1 gpu","one gpu"],("lora-and-peft",46))
it("gbnf-howto",["grammars in llama cpp","llama cpp grammars","grammar in llama cpp","use grammars"],("gbnf-grammars",50))
it("share-trace",["share a trace","leaking customer data","leak customer data","sensitive data in logs","redact logs","sensitive data in traces","pii in logs","customer data in logs"],("llm-observability",38),("ai-privacy-and-security",32))
it("dl-framework-more",["for deep learning","use for deep learning"],("pytorch",46))

# ---------------- synonyms ----------------
syn={"quantisation":["quantization"],"optimisation":["optimization"],"behaviour":["behavior"],"regularisation":["regularization"],"generalisation":["generalization"],"guardrail":["guardrails"],"tokeniser":["tokenizer"],"labelled":["labeled"],"normalisation":["normalization"],"modelling":["modeling"],"summarisation":["summarization"],"reranker":["rerank","reranking"],"rerankers":["reranker","reranking"],"hallucinated":["hallucination"],"gpus":["gpu"],"llms":["llm"]}
# ---------------- coverage gaps: ambiguity guard (only demotes when no topical concept/intent matched) ----------------
gaps=[{"id":"v3-not-ai-context","phrases":["data protection officer","project management","snake","venom","toy","toys","for kids","animal facts","job role"],"message":"This looks like it may be about something other than AI. Knowledge covers AI and developer topics.","suppressTools":True,"demoteWithoutTopic":True}]
# ---------------- page technologies (what you'll need) ----------------
def pt(p,*items): PT[p]=[{"name":n,"kind":k} for n,k in items]
PT={}
pt("vllm",("A GPU server with enough memory for the model weights plus KV cache","hardware"),("Python","language"))
pt("llama-cpp",("Enough RAM or VRAM for the quantized model file","hardware"),("A GGUF model file from a source you trust","model"))
pt("ollama",("A computer with enough memory for the model you pull","hardware"),("A downloaded model","model"))
pt("pytorch",("Python","language"),("Optional: a CUDA-capable GPU","hardware"))
pt("onnx-runtime",("A model exported to ONNX","model"))
pt("lora-and-peft",("A base model whose licence allows fine-tuning","model"),("A GPU with enough memory for the base model","hardware"),("A fine-tuning library such as Hugging Face PEFT or TRL","library"))
pt("dpo",("An SFT model to start from and keep as the reference","model"),("A preference-pair dataset (chosen and rejected responses)","data"),("A training library such as TRL","library"))
pt("constrained-decoding",("An engine or library that supports constraints (for example Outlines, XGrammar or llama.cpp grammars)","library"),("A schema, regex or grammar","specification"))
pt("structured-outputs",("A JSON Schema or typed model","specification"),("A validator in your code","library"))
pt("rag-evaluation",("A labelled question set with gold passages and answers","data"))
pt("agent-evaluation",("A resettable sandbox environment and programmatic success checks","environment"))
pt("mlflow",("A tracking server with a database and artifact store","infrastructure"))
pt("pgvector",("PostgreSQL with the pgvector extension","database"),("An embedding model","model"))
pt("distributed-training",("Multiple GPUs with a fast interconnect","hardware"),("PyTorch or another framework with distributed support","framework"))
pt("code-execution-sandboxing",("A container or microVM runtime","infrastructure"))
pt("a2a-protocol",("An A2A SDK or implementation of the current specification","library"),("An HTTPS endpoint and authentication","infrastructure"))
pt("langgraph",("Python or JavaScript","language"),("A model provider and tools","service"))
pt("dspy",("Python","language"),("Labelled examples and a metric","data"))
pt("crewai",("Python","language"),("A model provider","service"))
pt("dpo-vs-rlhf",("Preference data in pairs or scalar rewards","data"))
pt("hybrid-search-and-reranking",("A keyword index (BM25) and a vector index","infrastructure"),("A labelled retrieval test set","data"))
pt("graph-rag",("An LLM for entity and relationship extraction","service"),("A graph store or index","infrastructure"))
pt("alphafold",("Access to the AlphaFold database or a supported implementation","service"))
pt("imitation-learning",("Teleoperated demonstrations","data"),("A robot or simulator","hardware"))
pt("sim-to-real-transfer",("A physics simulator such as MuJoCo or Isaac Sim","software"),("A real robot for validation","hardware"))
out={"version":1,"synonyms":syn,"intents":I,"concepts":C,"pageTechnologies":PT,"queryTechnologies":[],"coverageGaps":gaps}
json.dump(out,open("knowledge/src/lexicon-part-d.json","w"),indent=2)
print(len(I),len(C),len(PT))
